### ISSUE TITLE
It would be nice if you added these functions.

### ISSUE THREAD

**Issue by azunamc** [WWBN/AVideo#1519]
It would be nice if you added these functions.
It does not matter if they are free and payment, but it would be very good and attractive at the same time, it is only a suggestion.

Functionality to be able to donate some money to the channels.
functionality to have verified channels, sending documents to the administration.
Two-factor authentication.emoticons in the comments.
Full Ads system (User End), advertiser + Publisher (Monetization).
GEO blocking, user can restrict a video from being viewed from blocked locations.
paid videos system, user can sell his own videos to other viewers + admin commission
Identify the speed of the internet and select the quality based on that.
Messaging system (Websockets / Ajax).

**Comment by SubjectXXX** [comment]
1. You have channel subscriptions, same as donating..
2. what documents? You mean, that administrator needs to approve uploaded video?
3. Two factor auth is not really needed tbh, at least not in terms this software should be used..
4. Commentary function is there to comment. Maybe emoticons should be pushed up where Like and Dislike are located, facebook style?
5. ADs are really nicely implemented already alongside monetization. What are you missing? Dont forget about extra plugins: https://www.youphptube.com/plugins/
6. GEO blocking is pointless with all the (free) VPN services around lately. And as I understand author, he wants to have open video portal, limiting it to some countries already looks like political restrictions..
7. Same as 5th point
8. Author already works on developing streaming functionality via HLS, stay tuned on payable plugins page.
9. Yes. I agree on this one.

**Comment by gregorymcewanmarriot** [comment]
lol - may i add to the list ;)

**playlists**
linear, scheduled and random
allow users to add playlists to favs

**channels**
allow users to subscribe paid or free

**media**
allow jpegs (set time to show as in 7sec)
tags eg keywords. demographics 

**ads**
video or jpeg ads
allow weighting of ads and media eg weight 5 shows 5 times per hour/day
ads can be assigned to keywords or demographics 
ads can be assigned to playlists or channels all or by category 

**users**
location based content and ads
pay to view or paid subs (monthly or per channel, playlist)

**devices**
play fullscreen on iphone.android or pc/mac only the channels they chose
allow text ticker of extra info eg sales message or info or user messaging feeds from say social 

**media**
allow overlays of branding bars eg widescreen bars with logo across all media
allow register of devices as in MAC address or phone number 

**demographics**
content to be tagged by type and demographics

**import sync complete youtube or vimeo playlists or channels?**

users get full screen player with playlists sent by default and then can add remove or choose content based on type of content eg surfing or channels/playlists

each channel/playlist have ads in between based on demographics and content relevancy - users get rewards for watching ads

menu allows users to browse channels/playlist or vod stuff  to add or watch - bills if paid for channel or video

when player launched is fscreen so that when used at restaurants or as ad screens it plays channels that were allocated to device on these closed players press escape to pop up pwd box allowing player to be exited and new content chosen

logs of what file played when on what user/player

mobile apps allows users to see rewards - buy channels and send messages to other users (friends or family) AND CHOOSE  social media or new ticker feeds rss etc

when users choose playlist or channel to watch it plays all fullscreen by default in linear or random mode repeating until user or schedule changes
