### ISSUE TITLE
Share videos -> path to file directly

### ISSUE THREAD

**Issue by SubjectXXX** [WWBN/AVideo#1549]
You have two options to embed videos:
- iframe
- SEO friendly URL

I would like to link directly to video file. Its a nice feature in Moodle, to just paste URL link to file, Moodle then does all the work with embedding video player for serving this file..

How could I achieve this?

**Comment by DanielnetoDotCom** [comment]
I guess you already have this, just paste an mp4 file URL and you will be fine

**Comment by SubjectXXX** [comment]
Well, yeah, me as admin I have this, but regular user doesnt.

Is there a way to add this link directly to mp4 file to share part of video?

**Comment by SubjectXXX** [comment]
here:
![share](https://user-images.githubusercontent.com/2082595/53813688-7e4d9480-3f5e-11e9-8118-8beaa5b516fa.png)

**Comment by DanielnetoDotCom** [comment]
Sorry, do you want a direct link to the hosted mp4 file?

if is it, we do not have it done yet, maybe if you enable the download your users can see your files

![image](https://user-images.githubusercontent.com/18009293/53814104-c4dec700-3f3d-11e9-9a9a-bddff2f0e40b.png)

**Comment by RapFan89** [comment]
Hi,
i have the same need, as we too are using moodle to share our videos. So we would like to share a playable version of the video that is saved in the streamer site. We do not want to share the direct link, as we don't want to let people download the videos.

**Comment by DanielnetoDotCom** [comment]
@RapFan89 it should work for you, is it not?

**Comment by RapFan89** [comment]
Yes it  works, but while using a YouTube link the video keeps protection from right click save as, using the direct link provided by YouPHPTube, the videos become downloadable and we want to prevent this behaviour.

Let me explain this better:
In moodle there's a section called glossary, it is pretty convenient because let the user to search a video using a search box, instead of having a limitless list of videos to scroll down everytime. The issue is that in this section we are not able to insert embedded code, just links. We have tried by pasting  both URL Friendly and  the permanent link but the moodle form was not able to load a player (it shows an underlined string that lead to the streamer server), we were successful by pasting the direct video mp4 link, but as explained before when using right click we are able to save the video. Doing the same with a youtube link leads to download an html file that does not contain the video. How to reproduce this behaviour on YouPHPTube?

**Comment by SubjectXXX** [comment]
Moodle doesnt have filter for this kind of url type. Also, if you would want to use Moodle's player, you would need to stream video on youphptube side, which is enabled only recently and only by buying HLS plugin and configuring it corectly. 

Also, for streaming videos, you need a bit more juice in your hardware. YouTube streams its videos, youtube's link is recognized by out-of-the-box filter that comes with moodle installation. 

Which means, in theory, you need HLS plugin, create custom Moodle filter plugin and enable it. First half is ine theory done, second not.

**Comment by DanielnetoDotCom** [comment]
If you mean embed youtube link, you will not be able to download it, once when it is embedded we do not use our player, we use YouTube player
