### ISSUE TITLE
size of navbar

### ISSUE THREAD

**Issue by codelabinf** [WWBN/AVideo#1662]
Hi, I need to double the height of the navbar. How could I do it? Thank you very much for your explanations. The program is excellent!

**Comment by SubjectXXX** [comment]
Using CSS and solution that I pointed out to you in your previous ticket..

**Comment by codelabinf** [comment]
Hi, I can not find the .css file or the line that I have to change. Could you please tell me what file and what line is it? Thank you so much!

**Comment by SubjectXXX** [comment]
This section is meant for reporting bugs and errors or problems with installation. If you dont have any knowledge in css, then please use this page: https://www.youphptube.com/services

**Comment by tgd1973** [comment]
I tried to modify navbar too, but for what concerns css for navbar, a virtual css is created that in practice does not exist otherwise in the browser cache navbar.less
Some things about css can be inserted in 
https://www.youphpsite.xxx/siteConfigurations in the section <Script Code> 
or make changes directly in the file navbar.php ... but you have to see if you can also control navbar.

**Comment by codelabinf** [comment]
tgd1973, Thank you very much for your explanations.
