### ISSUE TITLE
Site only refreshes after Clear Cache - Can we setup a Cron to do this?

### ISSUE THREAD

**Issue by JDucommun** [WWBN/AVideo#1761]
Site only refreshes after Clear Cache - Can we setup a Cron to do this?
![Screenshot_4](https://user-images.githubusercontent.com/5632064/58339879-865bf880-7e18-11e9-949a-001988b20f86.jpg)

**Comment by KenRHill** [comment]
I noticed and was actually thinking the same thing.  When you are logged in and browsing in "My Videos" I noticed that videos say that they are still Encoding, even though they are already on the streamer and visible and available to watch.  Clicking Clear Clear Cache Directory button usually allows it to show as Active at that point.  I remember I had worked with YouPHPTube version 7.0 on another server and it did not do that, but then once upgraded to version 7.2 the issue was there.  My guess is it happened somewhere between version 7.0 and version 7.2.

**Comment by JDucommun** [comment]
MIne wont even show new videos sometimes with out a cache clear ... Doesn't seem like it would be that hard, many other platforms utilize cron to keep content fresh ...

**Comment by DanielnetoDotCom** [comment]
Make sure you uncheck those 2 options

![image](https://user-images.githubusercontent.com/18009293/58417270-a549cd00-805a-11e9-9e7a-e0eb8c5f087b.png)

**Comment by JDucommun** [comment]
SO I can use Cache, but leave those two options unchecked?

**Comment by DanielnetoDotCom** [comment]
If you leave it checked even the admin user will have the cache and you will not be able to see instant modifications.

**Comment by JDucommun** [comment]
ok.

**Comment by soapstreams** [comment]
I have had either of those options selected and I just double-checked: they are not checked now, either. Yet, I have this same problem. Any other ideas?

jdr

**Comment by DanielnetoDotCom** [comment]
Hi, are you talking about the clear cache button?
