### ISSUE TITLE
Major Problem

### ISSUE THREAD

**Issue by soapstreams** [WWBN/AVideo#1825]
I just spent almost $115 on plugins. I installed and activated all 4. I created a subscription plan, but instead of being prompted to pay for access when a user tries to play a video, the videos just aren't there. I took four videos out of the "subscription" group I created and one of the videos is now acting very, very strange. Check this out: https://soappirat.es/video/santa-barbara-ep-75-f110984

Can you please tell me what it is I did wrong? I followed your instructions on the wiki for setting up the subscriptions plugin.

**Comment by soapstreams** [comment]
It also dumped my playlist settings somehow. The plugin is activated, but it doesn't work anymore. My playlists have vanished. Poof! Hours and hours of work setting them up, organizing the videos (I have 171 videos for 3 different playlists), seemingly wasted for no apparent reason that I can figure out.

**Comment by soapstreams** [comment]
Nor do I see anything in the log that would explain this behavior.

**Comment by DanielnetoDotCom** [comment]
I am going to check your installation

**Comment by DanielnetoDotCom** [comment]
Hi I sent you an email requesting your credentials to check your site.

Also I notice the message "Sign Up Disabled"

It is required for paid contents

**Comment by soapstreams** [comment]
Does disabling signup cause this? I am not ready to have people sign up, but I am trying to get there.

**Comment by soapstreams** [comment]
credentials sent. Thanks. Sorry to bother you on a saturday.

**Comment by DanielnetoDotCom** [comment]
Ok

Some things...

1 - I made all your videos private, associate them to the user groups "subscribers", so no one will be able to watch them, only admins and subscribers

2 - In your PayPal plugin you are using the sandbox, you should use your real account

the sandbox you are using is mine, and I am only allowed to charge in BRL, your wallet is in USD. so that is the reason that raises an error when you are trying to charge.

`PayPal Error executeBillingAgreement: {"name":"CANNOT_MIX_CURRENCIES","message":"Invalid currency code, all currency codes must match","information_link":"https://developer.paypal.com/docs/api/payments.billing-agreements#errors","debug_id":"7a6fd8356f90c"}`

Go to your PayPalYPT plugin and do this:

1. Go to Paypal developer Site here https://developer.paypal.com/developer/applications (you must have Paypal account, of course)
2. Click on Create App on right side of page 
3. Choose name of your app and click Create App 
4. Now you can see and manage everything include client ID and secret.

Make sure you are using a live account, NOT the sandbox account

**Comment by DanielnetoDotCom** [comment]
Also, I checked and your playlists are there

**Comment by soapstreams** [comment]
There is still a problem with this video: https://soappirat.es/video/santa-barbara-ep-75-f110984

You will need to log in using the credentials I sent. What is causing that?

**Comment by DanielnetoDotCom** [comment]
For this video looks like you embed the own video page

I am not sure what link did you use to generate it.
