### ISSUE TITLE
Settings in Cloudflare to use Video CDN

### ISSUE THREAD

**Issue by sipero** [WWBN/AVideo#1868]
I am very familiar in using Cloudflare but I  do not follow how to setup it up so I can use this as described with YouPHPTube.

I am thinking that I need to have a domain setup for my main site with YouPHPTube installed and cannot simply use the IP address like I do now.

Inside of Cloudflare when I use CNAME it needs me to enter the actual domain name that I want to point the new domain or sub-domain to

**Comment by akhilleusuggo** [comment]
Answering your question , if you have your domain seted as www.example.com/YouPHPTube , you can go to redirection rection and redirect all traffic from www.example.com/YouPHPTube to www.example.com
This can be done . If you're using a panel , it's easier , since you can setup your root directory at the location /YouPHPTube as the root directory ( the public_html )

Ps: Is not recommended to use cloudflare , it makes useless the YouPHPTube since you can't upload files over 100mb . Even if you pay ( too much ) , the cap of upload are 500mb for enterprise plan ( Not recommended )

**Comment by sipero** [comment]
Yes but there is solution mention where you use the CNAME only to host the videos so the rest of the site works without using Cloudflare.

**Comment by sipero** [comment]
So I have figured it out now. What I did was install Let's Encrypt so I could get SSL certificate for my domain so I could then use that as a CNAME inside of Cloudflare when I used my new CDN sub-domain. So now my traffic for my videos goes through Cloudflare's CDN and not my VPS.

**Comment by akhilleusuggo** [comment]
Got it nice .
