### ISSUE TITLE
need help doing update to latest version

### ISSUE THREAD

**Issue by loso20p** [WWBN/AVideo#1917]
@DanielnetoDotCom  can u help me update to latest version

**Comment by akhilleusuggo** [comment]
1-Go to the installation directory and type :
`git pull 
2- Go to your admin site > ADMIN MENU > Update version > Select and install it 

Ps: Not always you will find an update version , since that one only applies when it updates the directory /YouPHPTube/updatedb . If you find nothing on Update version , then no worries .

**Comment by DanielnetoDotCom** [comment]
@loso20p first make sure what is your installation directory.
