### ISSUE TITLE
SSL on EC2 Server at AWS

### ISSUE THREAD

**Issue by piratesignal** [WWBN/AVideo#1935]
Anyone know how to do a SSL at AWS on EC2 server?  Amazon tech support is non-existent and I cant really find any help files on it.

Other than that, youphptube is up and running just fine now and many thanks to dan and akill for all their help!

**Comment by akhilleusuggo** [comment]
I repeat again. You have a wrong understanding about SSL and provider. AWS has nothing special so you need to do extra work or different stuff to make it work . Forget that you're using AWS if that makes you feed better . (the only thing on aws is very expensive )

What you need to get it's a VALID certificate . What does mean valid certificate  , I certificate (SSL) that the browsers recognize . You can create your own certificate to secure your site , but since there's no authority that your certificate is valid , the browsers will pop up that your site is ''not secure'' . This is a monopoly btw , but finally comes to it end with Let's Encrypt
1- You can create a free certificate that you need to renew every 90days with Let's Encrypt
2- You can buy a cheap one from your own provider ( if I remember it was GoDaddy ) . I think on GoDaddy cost around 5$ for a year( the first year at the least )

I don't know if you're using a panel or not . In case of not , you should google how to install your certificate on your server ( it's not hard )
