### ISSUE TITLE
Trouble with encoding

### ISSUE THREAD

**Issue by AKNightHawk** [WWBN/AVideo#1939]
Hello, I just found this awesome youPHPtube and I am having problems with the encoder submitting the video back to my site? The video's time always says EE:EE:EE and after the video is encoded it does not play. I have found a few things about this. But it does not seem to send the video back to the video folder. Even though my file size is set to 1 gig. I also looked in the video folder and did not find any videos. Just a bunch of jpgs and gifs. including the gif for the file I submitted.

anyway, hope someone can help me. Also, my encoder is just using the default ones from encoder.youphptube.com and encoder2.youphptube.com as I didn't know how to set up my own for myself. Though I would like to learn how later.

also my site link https://assaultknights.biz/DNVN/
Thanks.

**Comment by AKNightHawk** [comment]
Also, I know yall will want my log is it youphptube.log?

**Comment by DanielnetoDotCom** [comment]
hey, yes you need to check your log file

https://github.com/YouPHPTube/YouPHPTube/wiki/How-to-find-errors-on-YouPHPTube

**Comment by AKNightHawk** [comment]
here ya go
[youphptube.log](https://github.com/YouPHPTube/YouPHPTube/files/3488147/youphptube.log)

**Comment by akhilleusuggo** [comment]
I don't see any errors that has to do with your problem here . I assume that you have linked the log file of your streaming site . You should have linked the logs of your encoder site .
In anyway , the encoder and streaming , can have 1 principal problem :
- Not enough permission to receive the file ( on your installation folder , you should chmod 755 ( or 777 ) depending on the of your config system .

Before you do any of this , make your to update the script , you may be missing something :
`cd /var/www/html/YouPHPTube > git pull`

Try to clear the cache of your server and change the password ( I didn't saw that you have DM5 errors but another possible solution )
Good luck

**Comment by AKNightHawk** [comment]
I am using chmod 777 on the folder I dont know where the log file is for the encoder? My encoder is in its own folder though. where would the log file be?

**Comment by AKNightHawk** [comment]
Do I need to use the same password for my ftp by chance.?

**Comment by akhilleusuggo** [comment]
FTP has nothing to do with this . The log file should be on /var/www/html/YouPHPTube-Encoder/videos

**Comment by guymass** [comment]
I have been having also the EE:EE:EE error. System is fully updated. I dont have a   YouPHPTube-Encoder folder. Everything was working fine but recently I move my main domain of www.flatearth.co.il to sit on the same server as my subdomain fetube so I don't know if that has anything to do with it. Cannot see anything in the error logs either.

This is a screenshot of a video after encoding.
![Screen Shot 2020-02-18 at 17 53 01](https://user-images.githubusercontent.com/58882903/74752870-fc8e6e00-5277-11ea-87e4-035ac3067445.png)

**Comment by guymass** [comment]
I think this is my log.
[avideo.log](https://github.com/WWBN/AVideo/files/4220707/avideo.log)

**Comment by guymass** [comment]
In my case I have found that the solution was MediaFlare limiting my uploads causing all files larger than 100MB to appear with a duration of EE:EE:EE.
