### ISSUE TITLE
Delete User 

### ISSUE THREAD

**Issue by mikweb2017** [WWBN/AVideo#1983]
cay you enable option deleting user  in the  Gui ?

now ist possible  on  only Mysql Database

**Comment by akhilleusuggo** [comment]
Delete is not enough . Ban people , suspend account , and ban IP . Since we have the plugin User_Location we also should be able to cancel request from some countries . Giving as example , I don't want that people/IPs coming from USA to access to my webpage . Many other open sources have this option enabled thanks to User_Location plugin .

**Comment by SubjectXXX** [comment]
You cannot delete user, since user has some statistics tied to him. Also deleting statistics could make further problems. Just disable user.
