### ISSUE TITLE
Adding Custom Fields to Video

### ISSUE THREAD

**Issue by menzer2015** [WWBN/AVideo#2038]
Hi Daniel, thanks for letting me know about this page, I was wondering.. is there a way to add custom fields to the video? I would like to add some basic text fields and possibly an additional image field, I read in your log you use $_Server to store extra fields but I was unsure if that relates to what I need, any help would be appreciated

**Comment by DanielnetoDotCom** [comment]
Hi,  yes you can add, building plugins or modifying the source code and database (not recommended).

**Comment by menzer2015** [comment]
How do you add custom fields

Many thanks

**Comment by DanielnetoDotCom** [comment]
If you want to build a plugin you will need to take a look into the code 

you must know PHP and figure it out because we do not have a documentation for it.

just a Tip you can create custom tabs on the profile with this https://github.com/YouPHPTube/YouPHPTube/blob/master/plugin/YouPHPTubePlugin.php#L979

alternatively, you can send us a detailed email then we can quote this development for you.
