### ISSUE TITLE
Future request 

### ISSUE THREAD

**Issue by akhilleusuggo** [WWBN/AVideo#2077]
1- Plugin for Send Upload Video To Encoder
2- Remove the encoder ( for public usage , as an option )

Would be nice , thanks :)

**Comment by Donnerstein** [comment]
I would like to join the wish list.

-> A way for individual users to give a selectable icon confirmation token that is displayed behind their name. As with Youtube.
![image](https://user-images.githubusercontent.com/52116237/66245825-716d6b00-e710-11e9-89f6-8c12df1906cd.png)


-> The option to display the subscribed channels on a separate page. If a user has subscribed to a large number of channels, the loading time and data consumption for the start page is increased.

-> The possibility that a user can adjust the order of the tables for the most viewed, the most popular and the latest videos on the start page of the gallery, and the setting for the user e.g. saved with cookie.

-> For uploaders, the option Block individual users for commenting and rating their own videos. Everyone has trolls and haters on the internet.

-> A note to a comment because this was edited.

But it is not a criticism, it nevertheless an excellent project.
