### ISSUE TITLE
Pay Per View

### ISSUE THREAD

**Issue by mrtick2002** [WWBN/AVideo#2141]
The pay per view plugin offers no way to track sales. It should honestly have a way for content creators to upload video, set a price, and the admin get a commission off the video sale. But they/we have to know how many sales we've made so that we can pay commissions on content. That's basic...unless you're stealing other movies and selling them.

**Comment by DanielnetoDotCom** [comment]
For now, all the sales go to the site owner only, it was not designed to be used by creators.

we are currently updating the PPV so we will allow creators to set prices and directly get the payment from their sales. 

for now, we are building it for stripe only, so the creators will need to add their Stripe API credentials. 

When someone PPV one of their videos the payment will go directly to them. you will need to find a way to bill the creator, because the payment gateway does not allow us to split the payment into 2 accounts

I will appreciate if you  place here the requirements you think is important to have, so I will make sure I can build the best option


after that, we will also probably update the subscription.
