### ISSUE TITLE
Latency of 30 seconds with my current portable video live streaming

### ISSUE THREAD

**Issue by rkomar6121** [WWBN/AVideo#2317]
I fly drones for public safety agencies and am experiencing latency from my drone video to my YouPHPTube site of 20  to 30 seconds when seconds count. I would like to get the latency a low as possible and here is the explanation of my situation.

Picture this:

Standing in front of a burning building.

I send the drone up so I can see the whole building with a thermal camera.

I only have a HDMI port out of the controller and need to get the video to my YouPHPTube site.

So I plug the HDMI out from the controller into the HDMI in of the Cam Link 4K encoder and then I need to use some sort of rtmp to send it.

I can use a laptop or a phone. Both will need to have constant charging from my vehicle, so I use the Samsung S10 and CameraFI which has a Custom RTMP or I can just click on some predefined buttons, like YouTube, Facebook, Twitch etc and Wosza or the Custom RTMP button to send it to my YouPHPTube.

So I am portable, need a good internet / phone data and a way to charge everything from the vehicle even the drone, Presently working on tethering power to the drone.

Same situation for a police operation,  Still portable and sometime moving from one place to another.

**Comment by DanielnetoDotCom** [comment]
Hi

I guess the Latency comes from: 
1. Drone -> Controller
2. Controller -> Cam Link
3. Cam Link -> Phone
4. Phone -> server RTMP
5. Server RTMP -> HLS format
6. HLS -> Browser

The first thing is if you can reduce some steps, for example, send from the drone directly to the server, so jump from step 1 to 5, but I guess it will not be possible.

The RTMP will be converted to HLS in the server, but you said you were sending a 4K video, you may want to reduce the source to a 720p video, so the conversion will be faster

The best way to reduce the latency is using RTMP directly instead convert it to HLS.
But it is not a good idea for a web page, the problem with that is because RTMP is not compatible with HTML5, as long as I know you will need a flash player to play RTMP . but flash is almost dead and the support is being removed from the current browsers.
