### ISSUE TITLE
 The meaning and usage of the Google ads IMA Plugin

### ISSUE THREAD

**Issue by XemTube-TV** [WWBN/AVideo#2337]
Can you tell me the meaning and usage of the lines in the red circle? I don't know how those lines are used.

![image](https://user-images.githubusercontent.com/50126312/70447649-a5c72400-1ad1-11ea-8cf6-06b2049ddd34.png)

**Comment by DanielnetoDotCom** [comment]
in the video or in the VMAP or VAST URL if you pass &optionalAdTagUrl1=true or optionalAdTagUrl2 or optionalAdTagUrl3 or optionalAdTagUrl4, the plugin will use the Ad tag you put in the field.

For example, if you need to use a different ad tag in another device or site, just pass the optionalAdTagUrl[1234] in the URL then the script will use this URL instead of the URL defined in in the adTagUrl
