### ISSUE TITLE
REQUEST: Make videos not recommendable

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#2432]
We need a way to make certain videos not able to be recommended on the home page and in Auto Play.

**Comment by akhilleusuggo** [comment]
![image](https://user-images.githubusercontent.com/52116577/71361297-3d7d4580-259b-11ea-9e5b-0f091e58cf30.png)

Just put a lit of suggested videos , and other videos will never be suggested

**Comment by JoshWho** [comment]
That is not how that feature works at all.

**Comment by DanielnetoDotCom** [comment]
can you make them unlisted?

**Comment by akhilleusuggo** [comment]
@JoshWho I've said to use the start on all videos that you wanna recommend , the one that you don't wanna , just leave them without the star

**Comment by JoshWho** [comment]
We have thousands of videos. That would be really intense to go around all videos and unselect the ones I do not want recomended, Sounds like a pain in the butt especially with new videos added daily. 

@DanielnetoDotCom  Making them Unlisted is not a viable option for admin because a user can just relist it again. I do not want it missing from the search, I just do not want it recommended in auto gen play and random on home pages. 

For example: If someone wanted to do a documentary on History or something gory or something that is just not a normal recommendation but you still want it to be findable.

[Budd Dwyer](https://en.wikipedia.org/wiki/R._Budd_Dwyer) is a good example. This guy shoots himself on Live tv because he was accused of embezzling and was going to get a 50 year sentence. I do not want this video censored and not findabable but I also do not want it recommended as the next video. Do u see what I mean?

**Comment by maxlinux2000** [comment]
But this function could also be used on the contrary to make a white censorship as Twitter and Facebook does ... and Youtube is working on this.

Let us give an example that instead of Budd Dwyer, all videos made by Catholics are not recommended. What would happen? Simply that only those subscribed to their channels would find out that there are new videos of these Catholic channels and therefore could not grow and increase their number of subscribers.

Daniel ... Personally I would not consider this suggestion, although I do not doubt that the author has the best intentions.

I think life must be taken as it is ... there are good things and bad things.
For example, I cannot choose on TV and in the newspapers which news, movies and programs, they will propose to me daily.
Why should Avideo be censured, then?

Not everyone lives in the United States and in Europe, where lately it has become fashionable to be puritanical and politically correct on the one hand and propose authentic barbarities on the other.

**Comment by JoshWho** [comment]
I would just make it work with the rating system similar to NSFW environment. Let users choose in their accounts what they are will to get recommended. 

But My suggestion at the top is not for censorship but for more engagement views with auto play. You do not want people leaving your site if you can help it. Quality is what this is about. I want all videos findable and users should be able to find what they like without having to change the video by just working with the rating system or a new way to control what is recommended by ratings.
