### ISSUE TITLE
Improvement: More robust ffmpeg operations for Avideo Encoder

### ISSUE THREAD

**Issue by maxlinux2000** [WWBN/AVideo#2449]
Yesterday while encoding a 1.5GB video I had to re-launch apache (service apache2 restart) to make a minor modification.
The result has been that after a while I realized that the ffmpeg process had stopped and the Encoder has stood still waiting.

My proposal:
Put a timer in the Encoder that checks every X time if its process is still running and if it is not that of a warning to the administrator (email), and recover it automatically starting from the beginning the missing operations.

**Comment by akhilleusuggo** [comment]
@maxlinux2000 It's normal that the encoding has stopped if you restart apache . Since apache ( user-data ) is the user that has launched the ffmpeg process .
The encoding will stop , the video that was encoding will be ''lost'' . To keep going with the queue the only was is to manually remove the video from the encoder , and after that the queue will continue normally .
