### ISSUE TITLE
Custom port for SSL

### ISSUE THREAD

**Issue by SergejGrin** [WWBN/AVideo#2475]
Hello!  Happy New Year 2020!
The AVideo program installs and works on an **http** (80 port) connection wonderful.
I had a problem displaying the site when using SSL **https** on a non-standard port.
Configuration: several virtual servers are installed on the physical server.
 Server for AVideo (YouPHPTube):
            Ubuntu Server 18.04
            nginx version: nginx / 1.14.0 (Ubuntu)
            mysql Ver 14.14 Distrib 5.7.28
            PHP 7.2.24-0ubuntu0.18.04.1
            Certbot Nginx plugin - TLS certificate issued from Let’s Encrypt
Installed on the manual:
https://www.linuxbabe.com/ubuntu/install-youphptube-ubuntu-18-04-server
Since it is impossible to use port 443 on this virtual server (it is occupied by another web virtual server) it has been replaced in youphptube.conf by port 8443.
The streamer installation page worked correctly, as for the encoder (see screen 2), but after the installation, the panel login page is displayed incorrectly (see screen 1). I tried several different server configurations - always the same result. What could be the problem?
![YouPHP1](https://user-images.githubusercontent.com/59236880/71741216-9a5fe200-2e5e-11ea-8dea-85509e30e830.png)
![YouPHP2](https://user-images.githubusercontent.com/59236880/71741218-9a5fe200-2e5e-11ea-9dd3-0a2a0d31bc09.png)

**Comment by akhilleusuggo** [comment]
the 443 should work for all SSL ( you can use 444 ) . But why you're using for your domain name a custom port ? When you type https:// on the server automatically does the redirect to 443 port . You don't have to type it .

Regardless to your first screen it's a miss configuration on your /videos/configuration.php

**Comment by SergejGrin** [comment]
The problem is that YouPHPTube is installed on a separate server and port 443 is unavailable (it is already taken by another web server).
 That is why there was a need to change the port. What can be done in such a situation?

**Comment by republicus** [comment]
You only have one available public IP?
And, the other web server is one under your control?

If you have multiple public IP's then you can easily use 443 (et al) for each IP.

You may also configure a reverse proxy and put it in front of your aVideo platform.
[That could be your existing web server with port 443 as the reverse proxy if you wish.]

I have several static IP's but have also configured an apache reverse proxy for my aVideo Network and Encoders so that I may use dozens of encoders and only using one IP.

Reference:
[Apache Reverse Proxy on ubuntu 16.04](https://www.digitalocean.com/community/tutorials/how-to-use-apache-as-a-reverse-proxy-with-mod_proxy-on-ubuntu-16-04)

Here is an example virtual host that should work after setting up apache's mod_proxy on your webserver listening on port 443:

```
<VirtualHost *:443>
        ServerName tube.wakesoft.info
        ServerAlias tube.wakesoft.info

        SSLEngine On
        SSLProxyEngine On
        SSLProxyVerify none
        SSLProxyCheckPeerCN Off
        SSLProxyCheckPeerName Off

        SSLCertificateFile /local/path/to/letsencrypt/tube.wakesoft.info.cer
        SSLCertificateKeyFile /local/path/to/letsencrypt/tube.wakesoft.info.key

        RequestHeader set X-Forwarded-Proto expr=%{REQUEST_SCHEME}

        ProxyVia On
        ProxyRequests Off
        ProxyPreserveHost On

        <Proxy *>
            Options FollowSymLinks MultiViews
            AllowOverride All
            Order allow,deny
            allow from all
        </Proxy>

        ProxyPass / https://192.168.0.100:8443/
        ProxyPassReverse / https://192.168.0.100:8443/
</VirtualHost>
```
Change path to Letsencrypt and the ProxyPass IP
You can also revert the ports back to default https port 443 on your streamer if you wish, no need to keep the port 8443.

**Comment by SergejGrin** [comment]
Thank you for your reply. I have one public IP address, if there were at least two, then there would be no problem. All servers are installed on my physical server and at my complete disposal. There is a web server with an ISPmanager panel which uses port 443 for sites, the web server is located behind NAT. I tried on a separate server for YouPHPTube to configure Nginx as a web server and a reverse proxy server for Apache with mod-rpaf on a separate Ubuntu 18.04 server.
https://quasar.site/tutorials/701/kak-nastroit-nginx-v-kachestve-veb-servera-i-obratnogo-proksi-servera-dlya-apache-na-odnom-servere-ubuntu-1804
But due to the inability to use 443, I had to use an alternative, but this has not yet succeeded. I will try the configuration option for your link.

**Comment by republicus** [comment]
If you're on discord feel free to reach me @ Republicus#2744 if you need assistance

**Comment by SergejGrin** [comment]
I don’t want to put YouPHPTube on one server with sites (this is very undesirable) for two reasons:
- The web server is backed up daily + 5 weekly copies - the total amount of backups is about 250 GB.
- From YouPHPTube there will be a big load on the web server and plus backup ... access to sites may be affected. Therefore, only the option with a separate independent server, but using an alternative port.

**Comment by republicus** [comment]
Are you using virtualization?
I use KVM/QEMU and the visualized network interface can operate exceeding 20Gbps between VMs

By using a reverse proxy your webserver will not host the YouPHPTube/aVideo services whatsoever. Only the virtualhost file/configuration as I shared above. So your backup increase would be trivial in size -- which may be as little as 1KB

```
                                              [Internet]
                                                  |
                                                  |
                              [Firewall port forward 80/443] 
                                                  |
                                                  |
                                    [Hosted webserver]  -- [Hosted sites]
                                              | 
                                              | 
                                          [aVideo via Reverse Proxy]
```

else.. you could create an apache reverse proxy that sits in front of ALL your webservers

```
                                              [Internet]
                                                  |
                                                  |
                              [Firewall port forward 80/443] 
                                                  |
                                                  |
                                    [Apache Reverse Proxy]
                                       |               | 
                                       |               | 
                           [Hosted webserver]        [aVideo]
                                       | 
                                       | 
                              [Hosted sites]
```

As the second option, your hosted websever then would be untouched as well as backups. No configuration changes on either avideo or your hosted webserver would be needed.

My reverse proxy server is currently using 0.39% CPU utilization and is communicating at better than 10Gbpe over the virtual Ethernet interface.

If you are hosting several sites/domains then the first option of reverse proxy on your main webserver would be easiest because you would only need to create that single virtualhost with ProxyPass for the subdomain tube.*

Otherwise the second option would require you to create individual virtualhosts for all domains as well.

This is about your only option to use the same port for multiple servers having only one public IP.

I see little or no degradation in performance and no sizeable change in configuration that would affect

**Comment by SergejGrin** [comment]
I have the following server configuration:
                                                      [Internet]
                                                            |
                                                            |
                                                  __ [Router]__  (Port Forwarding)
                               (443 port)  |          |          |  80, 8443 port
                                                 |          |          |
   Nginx, Apache on ISPmanaager)  (xxx)    (Nginx, Apache, mod_rpaf of ...??)           
                                                 |          |          |
                                                 |          |          |
                         [VM1 web-server]  [VM2]  [VM3 YouPHPTube]  ( ProLiant DL160 whit VMWARE ESXI)
                           |    |    |    |    |    |                    |                    |
                           |    |    |    |    |    |                    |                    |
                           [site 1.... site 10]              [streamer]     [encoder]

**Comment by SergejGrin** [comment]
It would be the best way for me to try your first option, my configuration option is complicated. But I have little experience and I don’t know how to most easily and correctly implement it. Perhaps there is a manual. where, in detail, an example shows how this is installed and how the configuration is prescribed? I will be very grateful.

**Comment by ngmdat** [comment]
Hi Guy,
I'm facing a similar issue with the nginx proxy.
Could you please share your knowledge on how to fix it?
