### ISSUE TITLE
Why the repository name has changed ? 

### ISSUE THREAD

**Issue by nazimboudeffa** [WWBN/AVideo#2517]
Hi,

I am a user of YouPHPTube and I am a little bit confused with the new name

Is it possible to bring back the original name because the name YouPHPTube raises the idea of respecting the copyrights of the videos one should add to his site like it is used to be on YouTube

And I really love the idea of a clone of YouTube made in PHP and of course developed in GitHub

Thank you

**Comment by alexious** [comment]
YouTube is a brand and trademark owned by Google.  To use the YouTube brand in any way, you MUST have permission from Google/YouTube.

For several years we worked on our platform as a YouTube Clone, but really it is a media platform for audio and video. 

 If you think about it is the same like the following examples: 

- for copies = Xerox 

- Google for searching = google it

- for soda = cocacola

- video platform = youtube clone, 

What is it called when a brand becomes a noun?
A generic trademark, also known as a genericized trademark or proprietary eponym, is a trademark or brand name that, due to its popularity or significance, has become the generic name for, or synonymous with, a general class of product or service, usually against the intentions of the trademark's holder.

AVideo is the name and brand of our original audio video platform project, and so as to avoid any further brand and trademark issues with Google, we decided to use our own branding for audio and video platform "AVideo". 

Also we are adding many new features and value added services to our platform customers enterprise or open source that are not cloned.  We feel this platform is strong enough to stand on its own brand and merit.   

Let me know if you have any further comments or questions.  

Thanks.

**Comment by nazimboudeffa** [comment]
I have always find it funny to see You and Tube in the name of the project and I thought that it was Google who develop it with a taste of branding the YouTube trademark in this way and making an opensource version of it

The meaning of my argument is that if someone see this name refering to the original one he will keep in mind to distribute legal videos like on YouTube

My question is : How do you plan to replace all the YouPHPTube instances in the code by AVideo ?

**Comment by DanielnetoDotCom** [comment]
@nazimboudeffa If you check the code since version 8.0 all the YouPHPTube reference was changed to AVideo.

if you updated your code, you probably only have the directory installation name YouPHPTube, if you make a clean installation now, your directory name will be AVideo
