### ISSUE TITLE
Pay-per-view

### ISSUE THREAD

**Issue by heiress01** [WWBN/AVideo#2545]
Is it possible for the admin to set-up PPV for the videos that the user (content creator) chooses.  Collect the payment then disburse a share back to the content creator?

**Comment by DanielnetoDotCom** [comment]
You can let only admin to be able to set up PPV. So all the money will go to the site owner wallet. then the site owner needs to manually distribute the share

**Comment by joeqrakz** [comment]
If a user is paying per view, is it possible for them to pay from their wallet balance instead of creating a credit card transaction every time they want to pay for a video? In other words, can they use their credit card to add $10 to their wallet balance and then use their wallet to pay $0.04 to view a short video?

**Comment by DanielnetoDotCom** [comment]
> If a user is paying per view, is it possible for them to pay from their wallet balance instead of creating a credit card transaction every time they want to pay for a video? In other words, can they use their credit card to add $10 to their wallet balance and then use their wallet to pay $0.04 to view a short video?


yes it is.

It will ask to add funds only if your wallet ballance is insuficient.
