### ISSUE TITLE
Feature Request: Built In Multi Restream - Lets you broadcast to your FB, YT, ETC...

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#2682]
A user would be able to rebroadcast to other platforms from the A Video site all at the same time when Live. 

Some way to add your stream key and RTMP link to other services in your account and when you broadcast to the Avideo platform it will restream to the other accounts as well.

**Comment by akhilleusuggo** [comment]
@JoshWho That's not possible to do from the same server . You need at the least 2 nginx servers , one for the streamer site , the other one for restream.

**Comment by JoshWho** [comment]
That's not a prb. You can run multiple Nginx on one machine or just deploy another server if necessary.  

I use to do this with my old Nginx for me personally but not sure how I would implement something like that in this script. 

Here is a example of it.

https://www.youtube.com/watch?v=VHUPGfgkIgw

**Comment by akhilleusuggo** [comment]
@JoshWho Have you read my message ? Is not about HOW to do it , I'm doing it already . The problem is that , you can't use the same nginx RTMP server for more then 1 server .
You have only 1 config file rtmp , pointing to 1 IP . In that case , you will at the least need an additional IP . 
In that case you will need to create too many applications and that gonna overload your server . Not only bandwidth but disk .
What you want basically is what https://restream.io/ offers

**Comment by JoshWho** [comment]
Please watch that youtube video I posted. I want what restream is already doing but use my own dedicated servers instead of theirs.

**Comment by akhilleusuggo** [comment]
I've told you already , that I've watched that video 2-3 years ago .
 Is not about the pushes , it's about the applications 
The application gonna push the same statements to all users ...
You will need to add maybe some db tables otherwise all users gonna be restreaming to the same key .

If you wanna do it a dirty work , you can create a new app , but that one is only for 1 users , so for each you need to create one . 
You can restrict with IP streamer ( in case static ) , but recommended to take a look here . 
https://smartshitter.com/musings/2018/06/nginx-rtmp-streaming-with-slightly-improved-authentication/

**Comment by maxlinux2000** [comment]
Hello, I think what I am doing can be useful for you.
It can be done with ffmpeg, youtube-dl and a little bash + cgi.

At this moment I am using one of these scripts to take a YouTube live and re-transmit it in AVideo, without recoding and with a retrs of half a second or less.
If I do this, I can also do the opposite, I mean take the Avideo Live output and forward it to YouTube and Facebook at the same time.

I'm I have sent Daniel this script for evaluation and if it seems feasible to incorporate it into Avideo as a plugin.

Right now my system works like this:

I have a raspberry server in my parish church that using ffmpeg and a usb microphone transmits the audio to an icecast server to the second server.
On the second server I have the server icecast and a script with ffmpeg, which takes the audio and video output of a Chinese h264 ip camera ($ 30), syncs audio and video.
The first server and the second server share the same internet line.
The other servers have their own connection.

 The second server sends the flow to a third raspberry pi4 server with AVideo (complete with the entire suite).


From there you can see the live of the masses.

At the same time another script, always with ffmpeg, takes the audio output from the second server with iceast icecast, and transmits it to a fourth server with libretime (a web radio). So I also have a web radio that transmits.

But it doesn't end here. The third Avideo server does not have enough bandwidth for everything, so with another script I take the live output of the third server and send it to a fifth server with Avideo (and a lot of bandwidth) for mass broadcast.

You can do a lot of things with ffmpeg outside of nginx ....

**Comment by maxlinux2000** [comment]
but... I think you can do the same with VLC... in a confortable desktop

**Comment by akhilleusuggo** [comment]
@JoshWho I think I have found some way . I'll update it to the wiki .
