### ISSUE TITLE
Feature Request: Go Live from the Browser

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#2685]
Basicly a update to the old flash version you use to have on here. Maybe in HTML5 and Java now. 

Should still be the same principles. Just not using flash anymore.

**Comment by DanielnetoDotCom** [comment]
I still not find any rtmp publisher to work directly from the browser

**Comment by maxlinux2000** [comment]
an idea I don't know if can be help... we can use a bash script on cgi-bin folder that will be  trigeed from html+javascript interface.

If you think that can be a valid method, I can share with you my interface that I use in order to transmit the celebrations from a church.. on my smarhphone.

It's a simple bash script that geerate an html page a pressing a button fun anocher script with ffmpeg.
Pressing another button, it stop the process.

**Comment by maxlinux2000** [comment]
![Captura de pantalla_2020-03-09_14-10-34](https://user-images.githubusercontent.com/5683921/76215991-1c2e0c00-6210-11ea-80c0-a8aa81f62c4e.png)
![Captura de pantalla_2020-03-09_14-11-38](https://user-images.githubusercontent.com/5683921/76215993-1cc6a280-6210-11ea-9895-5db0ed939171.png)

**Comment by DanielnetoDotCom** [comment]
what script is that?

can you share it?

**Comment by maxlinux2000** [comment]
please look the email
