### ISSUE TITLE
Video thumbnails aren't generated

### ISSUE THREAD

**Issue by vapblack** [WWBN/AVideo#2692]
Greetings. I recently installed youphptube and all seems to be working, save for the thumbnail creation

    Poster (JPG) Generates well
    Portrait Poster (JPG) shows only white
    Mouse Over Poster (GIF) shows only white
    Mouse Over Portrait Poster (GIF) shows only white.

![image](https://user-images.githubusercontent.com/61056547/76127557-f61a2900-5fcf-11ea-9c25-093690d98222.png)

ffmpeg version 3.3.9
youphptube 7.8
debian 9

**Comment by DanielnetoDotCom** [comment]
Are you direct uploading or using the encoder?

please check this https://github.com/WWBN/AVideo/wiki/Automatic-Thumbs-(JPG-GIF)-on-direct-uploaded-MP4-videos

**Comment by vapblack** [comment]
I'm using the 'embed video' option. I have't tried uploading yet, embed was the first thing I tried. I'll check your link now

**Comment by akhilleusuggo** [comment]
@vapblack embed video should download the images ( I tested it from youtube API ) and work without problems

**Comment by vapblack** [comment]
> @vapblack embed video should download the images ( I tested it from youtube API ) and work without problems

well it doesn't seem to work in my installations, so any idea what I should be looking for?

**Comment by DanielnetoDotCom** [comment]
Check your streamer and encoder logs

**Comment by guymass** [comment]
Hi Daniel, I have purchased the MP4ThumbsAndGif plugin in hopes for it to fix some of my thumbnails issue on some videos probably those uploaded directly which do not have a thumbnail. Can you please advise on how to use the plugin because when I click the small icon nothing happens really. I then open the post and re save and it seems that the thumbnail appears again in the dashboard but when I refresh the site it still remains your yellow thumbnail. It doesn't fix the video's thumbnail. Can you please help.

**Comment by DanielnetoDotCom** [comment]
Are you using HLS format or MP4?

check your encoder log.

**Comment by Krystian95** [comment]
> @vapblack embed video should download the images ( I tested it from youtube API ) and work without problems

Hi, I've tried to upload many videos from YouTube, but seems that the GIF (shown on hover) are not generated/works, is it right or there's an error?

**Comment by DanielnetoDotCom** [comment]
@Krystian95 embed videos do not have GIF images.
