### ISSUE TITLE
How does cdn work with this software? is it already included on the platform or is a separate hosting account required?  

### ISSUE THREAD

**Issue by heiress01** [WWBN/AVideo#2756]

**Comment by akhilleusuggo** [comment]
https://github.com/WWBN/AVideo/wiki/Using-CDN-for-Videos-Only

**Comment by heiress01** [comment]
I read the wiki, it's what prompted my question.  I'm a newby so I asked to get clarification.  If that is something that is on the platform already?  do I have to create a separate site? how does it work?

**Comment by DanielnetoDotCom** [comment]
@heiress01 you can have 2 domains pointing to the same server.
one will be with CDN and another one dont.

BTW, It is not well tested, but since a recent update (chunk transfer between encoder and streamer), maybe you can use the CDN in the main domain, and a secondary domain will not be necessary. so  the CDN for videos Only is deprecated.

**Comment by akhilleusuggo** [comment]
I can confirm it . The CDN videos only is not needed anymore .
Encoder and videos working well under cdn ( tested with cloudflare )

**Comment by DanielnetoDotCom** [comment]
thanks for confirm it :)

**Comment by heiress01** [comment]
Got it! Thanks
