### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by krvam** [WWBN/AVideo#2847]
Hello i have this error, i dont know what is..
My server look fine. 
![image](https://user-images.githubusercontent.com/38817643/78859677-71735e00-7a06-11ea-8bc4-327fe18d148e.png)

I complete all the data that the installation asks me and when I go to install now, this appears to me

![image](https://user-images.githubusercontent.com/38817643/78859651-61f41500-7a06-11ea-8ef0-54ad00fde7a9.png)

**Comment by TakeAchance365** [comment]
Hmmm I don’t really know but I got that once to so what I did Was basically Killed  that operating system and reinstall a fresh new one like I use Ubuntu server on my  raspberry pi 3 b + because I believe it might not be it but I think something went wrong with the installation of the Avideo platform Somewhere I don’t know hey @DanielnetoDotCom can you confirm if I’m right or not

**Comment by akhilleusuggo** [comment]
I'm pretty sure the answer of @DanielnetoDotCom is this :
We're sorry , we do not give support to CentOS

**Comment by fvlasie** [comment]
yum install php-mysqli php-json

**Comment by mauriciojafer** [comment]
Hi @krvam Did you solve the error?.
I'm having the same error with ubuntu
