### ISSUE TITLE
Facebook login configuration Error

### ISSUE THREAD

**Issue by shebanet** [WWBN/AVideo#2892]
The Facebook Login configuration is not working for me. I entered the details (app id and key and the Valid OAuth Redirect URIs) however I am getting the following error when testing  the log in:
 
Unable to exchange code for API access token. HTTP error 400. Raw Provider API response: {error:{message:Error validating client secret.,type:OAuthException,code:1,fbtrace_id:
 
Also, when I attempt to edit or re-enter the credentials the input boxes become disabled and cannot be edited any more
![8715A70C-B69D-4EDA-8553-FECE43137097](https://user-images.githubusercontent.com/63685226/79589426-61f9b200-80a3-11ea-9cf8-933c53d1dd10.png)

**Comment by akhilleusuggo** [comment]
Not a bug for sure , because I'm using Facebook login without any problems .
1) You're setting your admin configuration from a phone ... ( seriously ? )
2) Error 400 : Bad Request response . Maybe Facebook did not approve your API
3) Don't change setting from the admin panel , but from plugins : 

![image](https://user-images.githubusercontent.com/52116577/79593583-57abd800-80e4-11ea-8df2-fe9f457fb007.png)

**Comment by DanielnetoDotCom** [comment]
Hi

Looks like your text fields turned on into a boolean field. For some unknown reason, this happens some times.
to fix it you must go to the plugin page, edit parameters and edit the code directly, or just remove all code. if you remove all the code the plugin will be reset to the default.

![image](https://user-images.githubusercontent.com/18009293/79593819-67122d80-80b2-11ea-9e74-54baa835c0c3.png)

**Comment by shebanet** [comment]
Daniel, you nailed it! Problem fixed.
akhilleusuggo, I didn't use my phone. I only used my phone just to take sceenshot. I wouldn't open a ticket without doing basic stuff like getting facebook api approval ;)
Thanks again Daniel!
