### ISSUE TITLE
Fonts don't change when selecting different themes 

### ISSUE THREAD

**Issue by tonuzo** [WWBN/AVideo#2953]
Hey,

should the fonts change when you select a bootstrap theme? If you choose any of themes the font style stays the same..

**Comment by DanielnetoDotCom** [comment]
Hi,

If you have the Customize plugin, and you update it recently it may be because of the custom CSS we add on it.

we just add a new option on the customize plugin to disable the custom colors. if you enable it will overwrite the colors and fonts.

if that is your case, please update your code and also download the plugin again to be able to disable this option.

![image](https://user-images.githubusercontent.com/18009293/80309239-26996a80-87aa-11ea-8e5e-c10e1ff4df49.png)
