### ISSUE TITLE
Sorry ! This streamer site is not allowed / Webhosting / https

### ISSUE THREAD

**Issue by TurboAnonym** [WWBN/AVideo#2980]
Hi ;)

**What worked:**
I successfully installed AVideo via git on my Webhosting managed with Plesk (It includes following Ressources https://www.netcup.de/bestellen/produkt.php?produkt=2221). The free TLD has a valid SSL certificate by lets encrypt (screenshot).
![image](https://user-images.githubusercontent.com/63397666/80761954-da4c8280-8b3b-11ea-95e2-af50c6608632.png)

**I noticed a similar isssue #516 ?**

**My Problem**
I am unable to access the encoder (screenshot).
![image](https://user-images.githubusercontent.com/63397666/80761282-8beab400-8b3a-11ea-8a62-10389ef62464.png)

**What i tried**
I read somewere to turn "allow_url_fopen" off - no effect.

I'd really appreciate any help!
Thanks for the great project!

TurboAnonym

**Comment by akhilleusuggo** [comment]
Try to add it manually to the database
I'm talking about your database encoder , on the table configurations , allowedStreamersURL

On your php.ini add this:
```
allow_url_fopen = On
allow_url_include = On

```
If still you having a problem , the actual problem is your host and hostname .
I had this problem before , you have to configure it and fix it .
Re-installing the encoder did not solved it for me , until I found the problem on my host and hostname .

**Comment by TurboAnonym** [comment]
**puplic encoder**
Sorry I didnt mention that i have only a Webhosting and i want to use the puplic encoder: https://encoder2.avideo.com/

**Comment by DanielnetoDotCom** [comment]
@TurboAnonym https://encoder2.avideo.com/ is not public anymore

Check our Network https://network.avideo.com/

you can use https://encoder1.avideo.com/ or https://encoder4.avideo.com/ or https://encoder5.avideo.com/

**Comment by TurboAnonym** [comment]
Thank you for your response and for keeping this project puplic!
