### ISSUE TITLE
wanted to run AVideo on docker

### ISSUE THREAD

**Issue by daoguey** [WWBN/AVideo#3034]
How to tutorial to run AVideo on Docker. can i get som help on this one? as the container I am trying to run (from the docker file in AVideo gives me an error

![image](https://user-images.githubusercontent.com/15695109/81464876-9f250180-9182-11ea-8f9e-d5c7585566fd.png)

if we have a tutorial please provide the link as i also see this as 3 years old.

thank you in advance.

**Comment by ronaldod** [comment]
Did not tried it lately but did you tried : [Other docker](https://hub.docker.com/r/leejoneshane/youphptube) I did not test it yet as docker workstation gives problems with vmware workstation.

**Comment by daoguey** [comment]
i tried it, was trying to find a newer version, as the files pull from a older youphptube github. I am also trying to build my own but i am just learning this how docker works and work with github. so if you have another how to that would be helpful thank you.

**Comment by ronaldod** [comment]
Needed a lot of fixing the one i posted. Busy at the moment to get a complete new compose file ready.

**Comment by daoguey** [comment]
Ok thank you, let me know.

**Comment by ronaldod** [comment]
Hi got it running on docker. There is a startup delay because of a large `chown` command. Just it takes like 5-10 minutes so just wait.
[mine repo for this](https://github.com/ronaldod/docker-youphptube)
Just grab the docker-compose.yml  and edit the obvious options as: 

- MYSQL_ROOT_PASSWORD (keep them all the same)
- DB_PASSWORD (As it uses root same as above)
- ADMIN_PASSWORD (keep the answer the same else you have a hard time to get admin on the encoder).
- ADMIN_EMAIL
- DOMAIN (Type in your hostname of your server where you run docker to reach it or other fqdn for that ip adress)

At the end you will have 4 containers:
- mysql - DB server
- sqladmin - phpmyadmin on port 8080
- avideo - on port 80 and optional later 443
- encoder - on port 8000 and optional later on 8443

At the moment encoder and streamer are split but is possible to combine them. Still under consideration.

Enjoy.

**Comment by ronaldod** [comment]
Still some bugs with the encoder. Continue later this week.

**Comment by daoguey** [comment]
ok no worries that is a good starting point to test. thank you!

**Comment by akhilleusuggo** [comment]
Can I ask what is the usefulness of it ? 
Multi-sites using the same directory ?

**Comment by ronaldod** [comment]
@akhilleusuggo You could do that but did not looked into that. But for that to we need to change things within the database and such.That can maybe a plugin for multi site support. 

The first idea behind a docker implementation is that people can easy test Avideo just by running with a few edits a file a complete site with all the basic option. You do not need to install a KVM or machine with ubuntu and then do all the commands.

**Comment by ronaldod** [comment]
@daoguey Found the issue and it gives some food for thought. It is related to the option that i have 2 docker images both for seperated function. One for the site itself and one for the encoding. Fastest solution is to put both functions in one container but that surpasses the idea of microservices. Curious what do you think as a user.

**Comment by daoguey** [comment]
well so far it looks excellent as a user. I think this is very good progress! I personally want to test it on a production site and see how it performs (even encoding) I looked at the docker file and you are building under ubuntu image. the guy you mentioned before is under: FROM alpine:3.8 any particular difference? 

Let me know what the manual fix is so i can check it also.

thank you for all your hard work.

**Comment by ronaldod** [comment]
This is build under alpine 3.8. At the moment it only supports http and not https yet but need to change some things for it in the source code for the encoder. I sended in already some fixes for the encoder so it is more compatible with docker. Still 2 problems with some js file. As these are hosted on the server and  it is now done with absolute links i want to change those to relative links.

**Comment by ronaldod** [comment]
I have it fixed. If you use the composer file from [mine repo](https://github.com/ronaldod/docker-youphptube). Change the variables like i spoke about in the previous post and run that with `docker-compose up -d` it should download. 

To fix it i had to fork and edit the form.php. The absolute links blocked it from working properly.

@DanielnetoDotCom If you could edit the proposed relative url changes to all links in the form.php 
Meaning instead of linking the JS files to an CDN. I can point the GIT back to your master GIT so the docker files stays up to date.

**Comment by daoguey** [comment]
I will be testing this now in my external server and see how it works. thank you @DanielnetoDotCom for providing also input. will post my website in a few min.

**Comment by daoguey** [comment]
providing some info. As AVideo has 2 sites one for the regular site and one for the encoder i think this will be beneficial: https://medium.com/@francoisromain/host-multiple-websites-with-https-inside-docker-containers-on-a-single-server-18467484ab95

And if wanted to run a clone with this would be a lot easier or a multi site for AVideo with HTTPS enabled automatically.

let me know what you think.

**Comment by ronaldod** [comment]
Sounds interesting. Will look into some extra yaml files for https and other one for the same but then with multisite support. And after also attaching the storage correctly to the image.

**Comment by daoguey** [comment]
ok let me know when i can test it. thank you.

**Comment by daoguey** [comment]
closing as it is a good way to test but not proceding into this anymore.

thank you

**Comment by ronaldod** [comment]
Docker has some limited issues as location for storage. It is a great concept for deploying large environments and for testing. For a "small" environment to medium environments it is better at the moment to go for vps or barebone installations. But for spinning up many encoders you can use docker.
It al depends on the size an purpose.

**Comment by lordforbes** [comment]
thanks for this. More of a general issue with AVideo than this docker fork, but can we add the rtmp streaming function? can we not include something like  https://hub.docker.com/r/tiangolo/nginx-rtmp/ 
It seems strange that this not built in to Avideo any more.
