### ISSUE TITLE
SecureVideosDirectory 

### ISSUE THREAD

**Issue by GodgivenButhelezi** [WWBN/AVideo#3197]
Today I bough the secure videos directory plugin, but as I used this comand sudo ln -s /home/daniel/Documentos/videos /home/daniel/Dropbox/htdocs/YouPHPTube/videos I was automatically loged out of my platform and redirected to the first install page what can I do I'm afraid i lost all my work

**Comment by GodgivenButhelezi** [comment]
![Videos](https://user-images.githubusercontent.com/59503924/83714211-0c14a580-a622-11ea-836a-b6ef2771005a.png)
Please help it's urgent

**Comment by ronaldod** [comment]
This page popups because the server has no access to the configuration.php.
If followed the instruction to delete the install directory it should not even pop-up but that is an other issue.
Normally you can not softlink over an existing directory. It will give an error like "file exists".

Did you rename the "/home/daniel/Dropbox/htdocs/YouPHPTube/videos" before executing this command ? 

And curious where you found the instruction to execute that command. I could not find it in the [wiki](https://github.com/WWBN/AVideo/wiki/SecureVideosDirectory-Plugin) or in the plugin.

**Comment by ronaldod** [comment]
There is an easy way to see if you lost your files and that is checking if you disk space is still used.
As the directory you placed a softlink on is the main directory for the video files.
