### ISSUE TITLE
I'm Having a Problem installing Avideo on Ubuntu Server 18.04 Please Help 

### ISSUE THREAD

**Issue by TakeAchance365** [WWBN/AVideo#3270]
I've been trying to install Avideo on Ubuntu Server 18.04 and i keep running into this problem  can you help @DanielnetoDotCom 

**Screenshots**
![Termius 6_21_2020 9_29_14 AM](https://user-images.githubusercontent.com/45086315/85227323-5b88fe80-b3a2-11ea-913a-9969a8cca17b.png)

**Comment by syldri** [comment]
@TakeAchance365 
hello 
before launching the installation you must first install

```
 sudo apt-get install software-properties-common
 sudo add-apt-repository ppa:ondrej/php
 sudo apt-get update
```

once installed starts the Avideo instaltion

**Comment by TakeAchance365** [comment]
![Annotation 2020-06-21 102236](https://user-images.githubusercontent.com/45086315/85228525-6f842e80-b3a9-11ea-9b8b-79aaa1906a65.png)

![Annotation 2020-06-21 1022361](https://user-images.githubusercontent.com/45086315/85228530-7ad75a00-b3a9-11ea-9234-
d7b08c865981.png)

i did it and it didn't work

**Comment by TakeAchance365** [comment]
![Annotation 2020-06-21 102236](https://user-images.githubusercontent.com/45086315/85228600-d3a6f280-b3a9-11ea-9d2e-28badba48541.png)
![Annotation 2020-06-21 1022361](https://user-images.githubusercontent.com/45086315/85228601-d4d81f80-b3a9-11ea-8b99-c1b9294e1490.png)


i did it still doesn't work

**Comment by ronaldod** [comment]
The error says that apache can not find a page to show. Please follow the manual to the letter and do not skip any step. You can also follow this one : [lamp install](https://github.com/ronaldod/Documentation/wiki/LAMP-(Linux-Apache-Mysql-and-PHP)-installation-on-ubuntu-20.04-LTS) and then [avideo](https://github.com/ronaldod/Documentation/wiki/AVideo-and-Encoder-installation-on-an-Ubuntu-LAMP-server).
The only problem change is that ubuntu 18.04 is using php 7.2 so you need to check if there is a reference to 7.4 to change it 7.2.

**Comment by syldri** [comment]
@TakeAchance365   I did a tutorial to show you how I installed on  Ubuntu 20.04 LTS 

all i put is live so it works perfectly 

I hope this can help you



- when you connect to your SSH, make a `cd ..` and press Enter

![image](https://user-images.githubusercontent.com/39193219/85230455-89952f80-b3f0-11ea-9f1b-433add2bed6e.png)


- .you redo a "cd .." to be like on the photo we don't see the house anymore

![image](https://user-images.githubusercontent.com/39193219/85230494-e2fd5e80-b3f0-11ea-81d0-e5205cb046df.png)


- you do a ``sudo su`   and enter the password of your  `shsh`   is to have administrator access

![image](https://user-images.githubusercontent.com/39193219/85230578-6e76ef80-b3f1-11ea-8cfe-776c4aa71c23.png)

. when it's done you should be root as in the picture
 
 ![image](https://user-images.githubusercontent.com/39193219/85230613-a3834200-b3f1-11ea-864f-5b654beb4a80.png)



- we have not launched the installation of the site before, it is necessary to install the components that are missing for apache

you have to follow what I did and copy the elements well


everything you see as in the picture makes you Y and enter

![image](https://user-images.githubusercontent.com/39193219/85230801-fad5e200-b3f2-11ea-8302-e7e1d1d49b27.png)


```
 sudo apt-get install software-properties-common   

 sudo add-apt-repository ppa:ondrej/php

 sudo apt-get updat
```


`sudo apt install curl`


`apt-get install zlib1g-dev `



`sudo apt-get install apache2 php7.4 libapache2-mod-php7.4 php7.4-mysql php7.4-curl php7.4-gd php7.4-intl mysql-server mysql-client ffmpeg git libimage-exiftool-perl && cd /var/www/html && cd /var/www/html && sudo git clone https://github.com/WWBN/AVideo.git && cd /var/www/html && sudo git clone https://github.com/WWBN/AVideo-Encoder.git && sudo apt-get install python && sudo curl -L https://yt-dl.org/downloads/latest/youtube-dl -o /usr/local/bin/youtube-dl && sudo chmod a+rx /usr/local/bin/youtube-dl && sudo a2enmod rewrite`


- `sudo apt-get install -y build-essential libpcre3 libpcre3-dev zlib1g zlib1g-dev libssl-dev php7.4-xml`


when everything is well installed

you make a   ` sudo mysql `

you should have the same thing on the picture

![image](https://user-images.githubusercontent.com/39193219/85230870-45575e80-b3f3-11ea-9901-4daa0a2ebfce.png)


ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'NEWPASSWORD';

Replace NEWPASSWORD with your password.  


![image](https://user-images.githubusercontent.com/39193219/85230990-f958e980-b3f3-11ea-85d7-f9d4d2fc6144.png)


when you click enter, it should look like the picture

![image](https://user-images.githubusercontent.com/39193219/85231032-53f24580-b3f4-11ea-8b76-b23a9f7e1c3b.png)


you will be blocked you must leave Mysql for that you must look at the photo and do the same

![image](https://user-images.githubusercontent.com/39193219/85231095-b64b4600-b3f4-11ea-8ae2-a44733867928.png)


and you should get back to normal

![image](https://user-images.githubusercontent.com/39193219/85231109-d1b65100-b3f4-11ea-8742-e25773f065bf.png)



now you do

sudo nano /etc/apache2/apache2.conf

![image](https://user-images.githubusercontent.com/39193219/85231149-35407e80-b3f5-11ea-99ce-e1bfdca38a2f.png)


- you should change the None to All as in the picture

<Directory /var/www/>
          Options Indexes FollowSymLinks
          AllowOverride None
          Require all granted
  </Directory>

![image](https://user-images.githubusercontent.com/39193219/85231209-87819f80-b3f5-11ea-918e-17a2748df83a.png)


- you do a Crtl + x for recording and you do Y


- In order to use mod_rewrite you can type the following command in the terminal:

`sudo a2enmod rewrite`



- sudo /etc/init.d/apache2 restart




you do with the ip address of your serverur

 http://12.12.12.12.12/AVideo/

![image](https://user-images.githubusercontent.com/39193219/85231472-9406f780-b3f7-11ea-9faf-5b520cc6a194.png)

**Comment by TakeAchance365** [comment]
Thank you @syldri i have Bad ADHD and very detailed step by step on what to do really helps i'm typing the code now and it's father's day so it might by awhile before i can update you guys

**Comment by akhilleusuggo** [comment]
@TakeAchance365 if your problem is the ABORTED , it's easy to fix . Just type : 

`apt-get install -y` whatveryouwanthere

the flag `-y` will force it to install . This issue happens sometimes , and `-y `does fix it .

**Comment by TakeAchance365** [comment]
hey everyone i just thought of a question for you guys after i get my server setup is there a way to make a clone of the ubuntu server iso file with all the plugins  and everything that i add to my server in case i want to make a upgrade to my server like right now i'm running this on a test server using a Raspberry pi and i'm saving money for an actually sever like a Synology Rackstation  is that possible

**Comment by TakeAchance365** [comment]
![avidoe](https://user-images.githubusercontent.com/45086315/85333503-4cd44180-b49f-11ea-816c-b039ce32f459.png)

i get this error now

**Comment by akhilleusuggo** [comment]
Your site url is not correct ! Should not point to /install 
Should point to http://IP/Avideo/
