### ISSUE TITLE
Will  these server specs work?

### ISSUE THREAD

**Issue by freedomshare** [WWBN/AVideo#3441]
Hi there everyone I am changing hosting company's and I have a few questions about server specs, I am changing because freedomshare.net dose not work very well when live stream it lags alot so these are the server I am looking at

Main server spects 

Xeon E5-1410 v2 
2.8 GHz 4 cores

64 GB

DDR3

2× 2 TB (HDD SATA) or

2× 300 GB (HDD SAS) or

2× 500 GB (SSD SATA)

1 Gbps

Unmetered

   This one for live streaming?

 

Xeon E3-1220 
3.1 GHz 4 cores

16 GB

DDR3

2× 2 TB (HDD SATA) or

2× 450 GB (HDD SAS)

1 Gbps

Or this one for live streaming or main site:

Atom C2350 
1.7 GHz 2 cores

4 GB

DDR3

1× 128 GB (SSD SATA) or

1× 1 TB (HDD SATA)

1 Gbps

Unmetered

I am looking pick up 2 new servers one for main server and one for live streaming  the first server is a lil bit pricey but the other 2 are definitely affordable 

These are off shore servers my selection is limited as the server must be off share and my currency exchange rate is terrible.

**Comment by jyrihovila** [comment]
Hi!

Both of the Xeon based servers seem fine to me, although 16 GB RAM on the live streamer could be raised to 32. 

Performance wise, it's **very** good if you can have a separate hard drive (preferably SSD or NVMe) for the operating system and the database, and separate (traditional HD) for the YouPHPTube (including the video) files. Even better If you can afford having a true hardware RAID controller and use RAID 1 for both OS and the data (video) drives.

Some other important factors to take into account:

- PHP-FPM can give you much better performance than Apache's mod_php. Unfortunately, the current version (9.2) of YouPHPTube has an issue that prevents you from using PHP-FPM -- however that will most likely be fixed very soon.

- Which ever you use (PHP-FPM or mod_php), finding the right parameters for Apache and PHP is essential when it comes to fully utilizing the power your hardware can provide. Good places to get you started with this are https://www.liquidweb.com/kb/series/apache-performance-tuning/, https://medium.com/@Alibaba_Cloud/apache-performance-tuning-on-linux-93f5330f7808 and https://medium.com/@sbuckpesch/apache2-and-php-fpm-performance-optimization-step-by-step-guide-1bfecf161534

- Using MariaDB can give you better performance than MySQL. MariaDB is a drop-in replacement for MySQL, so using it instead of MySQL should be very easy. Which ever you choose to use, you must optimize the database server settings to get the best possible performance out of it. The MySQLTuner Perl script helps a lot in finding the best settings: https://github.com/major/MySQLTuner-perl

- Optimizing Linux kernel parameters can also give you a significant performance boost especially on the network (TCP/IP) level. There are some good ideas to start with at https://easyengine.io/tutorials/linux/sysctl-conf/ and at https://gist.github.com/voluntas/bc54c60aaa7ad6856e6f6a928b79ab6c 

- Also, make sure you have the PHP opcache module installed and enabled. You may want to increase the amount of memory opcache can utilize, especially on servers with 32 or more GB or RAM. If you have a separate SSD or NVMe drive for the OS and the database, you should use the same drive for opcache temporary files too. See https://www.ionos.com/community/hosting/php/php-7-opcache-speed-up-websites-noticeably/ for further details.

**Comment by DanielnetoDotCom** [comment]
Hi, all of them look good for me, I would just go yo SSD drives always.

and for Livestream and encoders, I would install RAID 0 if you get more then 1 SSD drive.
On live and Encoder a backup HD drive is not important, as long as there is no critical data stored on them. in case one of them fail, you just reinstall it and your service is back.

For your hardware please check this:
https://github.com/WWBN/AVideo/wiki/AVideo-Platform-Hardware-Requirements

To understand what you need for live stream, please read this: 
https://github.com/WWBN/AVideo/wiki/Live-Plugin#how-many-livestream-can-i-make

**Comment by akhilleusuggo** [comment]
Sorry but I don't agree with any of the comment above .
The live-stream will require 2 things . You said ''it's lagging'' . You need to define more that . Lagging because you're using adaptive stream ( encoding it ) , or because it buffers .

Most likely is buffering , and that's because of the packet-lost . In this case you will want a provider that have **_multi-region architecture_** . This service providers have the solution for you , improving latency , data replication etc . The most known is AWS , gcloud etc etc .

It doesn't mater how much is your bandwidth , if you're having tons of packet lost . Most of the CDNs does not support rtmp , that's why your solution for that is multi-region architecture .

If I'm located on France , and I'm streamer to a server on USA , doesn't matter if I have 1gb/s or 100mb/s , it will lag .
If I were you , i'll first focus on the server location and quality ISP , then take a look at the hardware .

**Comment by DanielnetoDotCom** [comment]
@akhilleusuggo the 1gbps is regarding multiple users connections.

Regarding the pack loss, a solution would be a re-streaming process, with a (multi-region architecture) like you said. that can be configured on Nginx.

I have plans in a soon future, add a restream option that will use the FFmpeg on the encoder or maybe on the live server itself.

BTW, what do you guys think will be the best server to restream? (encoder or Live or Streamer?)

**Comment by freedomshare** [comment]
Thank you everyone for the reply 

Here is a live stream that was " lagging" https://freedomshare.net/v/2879?channelName=FreeDomShare+Live

My current server is in US.

It has 70gb ram 4 core 2.8 2tb hard drive not SSD 
CPU goes up to 20% when one live stream is going 
I currently pay 100 us for this server on a ROT it would cost another 20us to add a SSD drive 

I would like to move there server off share tho

**Comment by DanielnetoDotCom** [comment]
Check servers from OVH, I am pretty sure you can get a better deal  https://www.ovh.com/

**Comment by freedomshare** [comment]
The first server I listed is 60 us in France 
The 2and is 32us in France 
And the last one is 10us france 
1gbs unmeter on all server ovh offer 300gb to 500gb for the prices

**Comment by DanielnetoDotCom** [comment]
try to get the server as close as possible from your audience.

**Comment by freedomshare** [comment]
I currently have no traffic I have not been promote the site at all because live streaming hasn't work correctly from day one so I have no traffic also I am looking for off share for  copyright reason when I do get traffic I dont monitor my sites for the most part so I want to be safe then sorry later

**Comment by freedomshare** [comment]
My server is a 5he drive away from me an still have this issue

**Comment by DanielnetoDotCom** [comment]
The proximity is just one of the points to consider.

You MUST consider also all hardware, including HD Drives, RAM, Bandwidth, and CPU (if you are transcoding)

**Comment by freedomshare** [comment]
I use 70gb ram right now unmeter 1gb ban with 4 cores 

Only thing I dont have right now is SSD

**Comment by freedomshare** [comment]
I am a bit scared to add one because 256gb ssd will extend my ROT for 6months at another 20$ and not 100% sure it will fix this issue

**Comment by DanielnetoDotCom** [comment]
I just went to your server and this is what I found

4 Cores and 20 GB

![image](https://user-images.githubusercontent.com/18009293/88550313-d07dd280-cff7-11ea-9607-27eb39519503.png)

so I guess, this is not a dedicated server,  you are using a VM, what already will slow you down a lot.

If you really want to have a good performance, avoid using VMs (especially without fast drives)

**Comment by freedomshare** [comment]
Yes I use vm but why 20gb should be 2tb harddrive 
I use cm because I use to use this server for web hosting an have to keep the vm for the files that I need

**Comment by freedomshare** [comment]
My plan is to move it to one of those server up top and not use vm on it and keep my vm server for saving files as the rent to own is ending soon

**Comment by DanielnetoDotCom** [comment]
FYI, 

Tested in a Dedicated server with SSD drives
![image](https://user-images.githubusercontent.com/18009293/88551355-2737dc00-cff9-11ea-9c51-50d68f6eae3f.png)

Tested in your server
![image](https://user-images.githubusercontent.com/18009293/88551421-39b21580-cff9-11ea-914a-d26bad803a3c.png)

**Comment by freedomshare** [comment]
My sever is a dedicated server it just I use windows vm on it because I use to host other websites like play tube and I cant remove vm because my other server files are saved on that server

**Comment by DanielnetoDotCom** [comment]
So your Streamer/Encoder/Live are NOT dedicated, also they share all the resources with your other sites and VM Host.

that explains why you are having problems with the hardware performance.

**Comment by freedomshare** [comment]
All other servers have been turned off since I got you to do reinstall so they are not using anything at the moment

**Comment by freedomshare** [comment]
What if I was to buy the 10$ server and use it for live streaming? Would that work? Or would it be very limited amount of streams? I'd get the ssd drive on it

**Comment by DanielnetoDotCom** [comment]
Please, I am keeping saying. use VM in a slow disk is not a good idea and your servers are NOT dedicated, does not matter how much resources you give to them.

I guess right now your problem is your disk but also maybe something else because you have a windows host for your VMs. and sorry I cannot help you configure it.

If you want, you can upgrade your hardware, but there is no guarantee you will have a good performance as long as you still using VMs over windows host. for me, I always choose a dedicated server directly installed in the hardware, so I always avoid VMs.

I am not saying it will not work in a VM, it probably will, but you have to have the correct hardware and have it properly configured for performance.

**Comment by DanielnetoDotCom** [comment]
I can tell you this...

At home I use VMs for my test servers. I use VMware on Windows 10.

I have one SSD drive dedicated for the Windows and another SSD just for the VMWare. and I  still think it is slow, the live does not work 100%. (maybe CPU? I have an i5 9gen). but they work good if I use my dedicated servers.

**Comment by freedomshare** [comment]
That's why I was going to pick up a 2and server let the vm server host main platform use a non vm server for live streaming

**Comment by DanielnetoDotCom** [comment]
This may work. but a 10 USD server for me is not a Dedicated.

The 10 USD maybe a VPS on SSD drives. I guess it will work better.

**Comment by freedomshare** [comment]
It dedicated server not a vps  server 
Atom C2350 
1.7 GHz 2 cores

4 GB

DDR3

1× 128 GB (SSD SATA) or

1× 1 TB (HDD SATA)

1 Gbps

Unmetered


Nothing fancy about it the cores is only 2 ram is 4gb

**Comment by akhilleusuggo** [comment]
This server should be used for NGINX + YPT-Storage . Is the best use for it .

**Comment by freedomshare** [comment]
> This server should be used for NGINX + YPT-Storage . Is the best use for it .

Witch server the current one I am hosting the site on?

**Comment by freedomshare** [comment]
Oneprovidor they have a summer sale and the prices depend on what location you want right now france has the cheapest prices for what you are getting and they are all 1gb unmeter

**Comment by DanielnetoDotCom** [comment]
If it is a 10 USD server, I guess it is a very good start.

**Comment by freedomshare** [comment]
I could actually pick all 3 servers I listed up top for 2$ more then what I pay now for my rent to own server witch it contract is almost over so I'll be shutting down this current server regardless as it will have to be shipped here when the contract is over then I will have physically access to the current server but I will need a back up server well my current one is being shipped here

**Comment by akhilleusuggo** [comment]
is not 1gb ... cmon . Is a SHARED 1gb . Shared with 18 users xD

**Comment by freedomshare** [comment]
> is not 1gb ... cmon . Is a SHARED 1gb . Shared with 18 users xD
> edit 8 server*

Why would it be shared it not a shared server or a vps?

**Comment by DanielnetoDotCom** [comment]
To be honest, the price is very out of market for a dedicated 1gbps connection.
that is why I am asking you the company.

**Comment by freedomshare** [comment]
> To be honest, the price is very out of the market for a dedicated 1gbps connection.
> that is why I am asking you about the company.

This I do agree with also the reason why I am asking before buying

**Comment by freedomshare** [comment]
The company is called oneprovider

**Comment by DanielnetoDotCom** [comment]
Still a good price, but ...

![image](https://user-images.githubusercontent.com/18009293/88557641-daf09a00-d000-11ea-82ba-141333590d7b.png)

**Comment by freedomshare** [comment]
https://oneprovider.com/dedicated-servers/paris-france

**Comment by freedomshare** [comment]
> Still a good price, but ...
> 
> ![image](https://user-images.githubusercontent.com/18009293/88557641-daf09a00-d000-11ea-82ba-141333590d7b.png)

Ah I didnt see that at all

**Comment by freedomshare** [comment]
Is it worth grabbing it to test to see if it fixes the issue on live streaming? As a test? 10 is cheaper then 20 and wont have to redo my vm server 
If I have I guess I got move all my server files to my pc an remove the vm from my current server but not sure if that gonna fix the issue I am having

**Comment by DanielnetoDotCom** [comment]
I think worth to get the SSD drive one.

use this only for the Live (It will require an NGINX + RTMP installation over a subdomain with SSL)

and test it. I guess it will fluid well if you do not transcode it

**Comment by freedomshare** [comment]
> I think worth to get the SSD drive one.
> 
> use this only for the Live (It will require an NGINX + RTMP installation over a subdomain with SSL)
> 
> and test it. I guess it will fluid well if you do not transcode it

Ok I think I will give this a try because removing vm from current server I would be flushing 200$ in install fees down the drain 
I dont mind putting a SSD in current server but removing the vm would be a big L on the money spent

**Comment by freedomshare** [comment]
> I think worth to get the SSD drive one.
> 
> use this only for the Live (It will require an NGINX + RTMP installation over a subdomain with SSL)
> 
> and test it. I guess it will fluid well if you do not transcode it

I'm probably gonna back my server files up tonight an remove vm and get SSD drive added

**Comment by jyrihovila** [comment]
> The proximity is just one of the points to consider.
> 
> You MUST consider also all hardware, including HD Drives, RAM, Bandwidth, and CPU (if you are transcoding)

True. As well as the configuration of all the related components. The default settings of Linux, Apache, PHP and MySQL / MariaDB are not too good.

**Comment by freedomshare** [comment]
> > The proximity is just one of the points to consider.
> > You MUST consider also all hardware, including HD Drives, RAM, Bandwidth, and CPU (if you are transcoding)
> 
> True. As well as the configuration of all the related components. The default settings of Linux, Apache, PHP and MySQL / MariaDB are not too good.

Ugh now it getting a little bit more complex, not to good with line commands :( more of a cpanel kind or person, 

I guess I better start learning more an researching :( I love this platform just wish I could get it running correctly, problem is not the software it is me and my lack of knowledge and well server set up is not correct too from what I am understanding, 

Thank you everyone for the knowledge! You are good people!

**Comment by freedomshare** [comment]
I might just shut down the site for the time being until I get more  knowledge on linux servers and setting them up correctly.

**Comment by jyrihovila** [comment]
> I might just shut down the site for the time being until I get more knowledge on linux servers and setting them up correctly.

I'll be happy to help you with the configuration. Please email me: jyri dot hovila at turvamies dot fi

**Comment by freedomshare** [comment]
Thank you I have shipped my current server to me so currently my site is down well that process go on, how ever I plan to use the one being shipped to be as a 2and server I am going to buy this server as the main server

And hopefully start fresh again 
![20200804_174902](https://user-images.githubusercontent.com/60738260/89343746-1fbca680-d67b-11ea-8d5a-c865e8753561.jpg)


Hopefully this server spec can run it smooth with 1 cpu?

**Comment by freedomshare** [comment]
Has anyone had any issues with ovh and DMCA?

**Comment by DanielnetoDotCom** [comment]
Where is this server from?

I use OVH for myself and I never had any problem

**Comment by akhilleusuggo** [comment]
DMCA for what ?
Did some company reported you ? In any case , they should take down the domain first ( for my understanding )

**Comment by freedomshare** [comment]
Ok I literally just got done emailing you, the one I listed is from oneprovider but read there terms after post and they forward copyright to online.net which is where they get there servers from, 

I'm looking for a netherlands or Russian server company because they normally offer bulletproof service as they do not follow us laws, I'm not really trying to copyright but I do not monitor my sites so there is always a chance that users will upload copyright videos and may not comply I n time

**Comment by freedomshare** [comment]
> DMCA for what ?
> Did some company reported you ? In any case , they should take down the domain first ( for my understanding )

I use to run other video sites before and got alot of copyright notices it was simply a pain in the but to comply 
Was at one point get 5 copyrights a day, from what I was reading with ovh some people has had there service cancelled due to copyright 
And this is the reason I'm looking for bulletproof server company they do not need to comply at all 
Due to there country laws 
I'm not looking to do copyright but I'm also not trying to spend my hole day trying to sort out fake copyrights vs real ones

**Comment by akhilleusuggo** [comment]
Anyway the img you have posted is NOT from OVH 
https://user-images.githubusercontent.com/60738260/89343746-1fbca680-d67b-11ea-8d5a-c865e8753561.jpg

That's very over priced to be from OVH ( and I can't find it on OVH )

**Comment by freedomshare** [comment]
The one in imgur is from oneprovider I haven't looked at ovh prices yet.

**Comment by freedomshare** [comment]
![Screenshot_20200806-171438_Samsung Internet](https://user-images.githubusercontent.com/60738260/89578349-5c69d880-d808-11ea-9b6b-c43af5fd0edf.jpg)
I found this witch is do able for the price rang I'm looking for but will it work fine?

**Comment by akhilleusuggo** [comment]
man , you're over killing your server really . For what do you need that much specs ?

https://www.ovh.ie/dedicated_servers/prices/

**Comment by freedomshare** [comment]
My last server was 2 cpu 70gb gaming server is my site had so much lag to it when streaming not trying to take any more chances had the last server redone 2x with no luck so I'm trying to make sure it runs smoothly all the ways around

**Comment by akhilleusuggo** [comment]
lags has nothing to do with ''really specs'' . it's about the IPS routing bandwidth and IOps . For live-streaming a VPS ( 1 core ) with NVME is more then enough . Unless you wanna transcode then yes you may even want a GPU .

**Comment by freedomshare** [comment]
Thanks everyone the issue was the company's bandwidth was bad I moved my server and there no more lag as far as I can tell  when live streaming
