### ISSUE TITLE
No more previews

### ISSUE THREAD

**Issue by ra3ggy** [WWBN/AVideo#3445]
Good day.
Recently, when inserting a video from YouTube, a preview of the video has ceased to be created.
FreeBSD 12
php74
ffmpeg-4.3.1,1
youtube_dl-2020.06.16.1 
Tell me where to look for debugging.

**Comment by akhilleusuggo** [comment]
provide some logs , or JavaScript errors 
https://github.com/WWBN/AVideo/wiki/How-to-find-errors-on-AVideo-Platform
https://github.com/WWBN/AVideo/wiki/Using-Your-Browser-Console-to-Diagnose-JavaScript-Errors

Without detail hard to know what's wrong

**Comment by ra3ggy** [comment]
[youphptube.js.log](https://github.com/WWBN/AVideo/files/4990345/youphptube.js.log)
[youphptube.log](https://github.com/WWBN/AVideo/files/4990348/youphptube.log)

**Comment by akhilleusuggo** [comment]
I think you're really outdated ... What version is that ?

**Comment by ra3ggy** [comment]
YouPHPTube 7.8

**Comment by akhilleusuggo** [comment]
I see ... Anyway your issue is not related to your version ( we're at 9.2 )
Your issue is related to YouTube API latest release ( I believe ) . Take a look here and read it . This email you should find it under the email you're using for YouTube API : 

![youtube-API](https://user-images.githubusercontent.com/52116577/88706098-12526a00-d119-11ea-8c33-ae6a9680ea16.png)

**Comment by ra3ggy** [comment]
Got it. Thank.
