### ISSUE TITLE
Share the price for joint projects

### ISSUE THREAD

**Issue by syldri** [WWBN/AVideo#3450]
hello, I wanted to make a proposal I don't know if I have the right to post this message

many of us want to make changes to our site,  the price may be too high for many

what i propose if we want to add a feature to our site  is to share the financial cost  

if we have a project that might appeal to other people, it's to split the price

I give you an example = if your project costs 300 $ there are 6 people who are interested, each person will pay 50 $

 the project remains with @DanielnetoDotCom   for future updates he can add it to the shop 

everyone who paid for this project will have full access to the source code
(the sourse code will not be encrypted)

it all depends on @DanielnetoDotCom

**Comment by jengajenga** [comment]
i like this

**Comment by jyrihovila** [comment]
I have actually been thinking about something like this too, since I have an AVideo customer with many enhancement ideas and customization needs.

The AVideo project has grown quite big and just maintaining the code base must already take lots of time -- not to mention adding new features etc. We could crowd source some additional work force for @DanielnetoDotCom through, for example, Freelancer. Only if he likes the idea, of course.
