### ISSUE TITLE
Reverse proxy HTTPS to HTTP

### ISSUE THREAD

**Issue by guitarpound** [WWBN/AVideo#3455]
**Describe the question**
Hi Daniel,

I setup the Avideo server as HTTP into my customer network.  
They use Reverse proxy to redirect HTTPS domain name to the AVideo Server.
But the web page display incorrect layout.

So, I tried to edit URL in /videos/configuration.php & /Encoder/videos/configuration.php to https://media.camt.cmu.ac.th/
But the web page still display incorrect layout.

Could you please kindly suggest me how to fix this problem.

**Screenshots**
![Untitled-1](https://user-images.githubusercontent.com/57282919/89123768-1bb64a80-d4fc-11ea-8096-3c78478872e5.jpg)

**Comment by akhilleusuggo** [comment]
you should not change the config file to https if you don't have an SSL certificate on your local . 
Anyway why not installing an SSL certificate with let's encrypt ( it's free and 2mn setup ) , to avoid this issues .

**Comment by jyrihovila** [comment]
> you should not change the config file to https if you don't have an SSL certificate on your local .

From the client browser's point of view, there is https, so the links should point to https.

> Anyway why not installing an SSL certificate with let's encrypt ( it's free and 2mn setup ) , to avoid this issues .

Because, as @guitarpound explained, the customer is using a reverse http proxy that handles the https part. They probably have one or more reasons why they want to do things this way. And in every case, fixing the problem should not require installing ssl/tls certificates on the AVideo server.

@guitarpound, looking at the http source of the site, it's clear that the problem has to do with the AVideo configuration. The base URL should start with https:// not http://. Because, for security reasons, browsers do not load insecure (non-encrypted) content when visiting a secure (encrypted) address.

Right at the beginning of the page source you can see:

`
<link rel="apple-touch-icon" sizes="180x180" href="http://media.camt.cmu.ac.th/video/videos/favicon.png?1595411478">
--
  | <link rel="icon" type="image/png" href="http://media.camt.cmu.ac.th/video/videos/favicon.png?1595411478">
  | <link rel="shortcut icon" href="http://media.camt.cmu.ac.th/video/videos/favicon.ico?1595411478" sizes="16x16,24x24,32x32,48x48,144x144">
  | <meta name="msapplication-TileImage" content="http://media.camt.cmu.ac.th/video/videos/favicon.png?1595411478">
  |  
  | 
  | <link href="http://media.camt.cmu.ac.th/video/view/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css"/>
  | <link href="http://media.camt.cmu.ac.th/video/view/js/webui-popover/jquery.webui-popover.min.css" rel="stylesheet" type="text/css"/>
  | <link href="http://media.camt.cmu.ac.th/video/view/css/fontawesome-free-5.5.0-web/css/all.min.css" rel="stylesheet" type="text/css"/>
  | <link href="http://media.camt.cmu.ac.th/video/view/css/flagstrap/css/flags.css" rel="stylesheet" type="text/css"/>
  | <link href="http://media.camt.cmu.ac.th/video/videos/cache/css/f9aaadfb25ab0efcac55ba66a62acff8.css?1595498932" rel="stylesheet" type="text/css"/>
`
Those are the lines that should make the browser load the CSS style sheet files. But because they are linked without the ssl/tls encryption, the browsers ignore loading them. 

All you have to do is to edit the parameter webSiteRootURL in your AVideo configuration file (located at YouPHPTube/videos/configuration.php). Currently, it's probably $global['webSiteRootURL'] = 'http://media.camt.cmu.ac.th/'; while it should be $global['webSiteRootURL'] = 'https://media.camt.cmu.ac.th/';

**Comment by akhilleusuggo** [comment]
@jyrihovila With respect , but that is not true . I just created a VM without SSL , and using only http , and works perfectly . This part =does the job : 

```
$global['webSiteRootURL'] = "http".(!empty($_SERVER['HTTPS'])?"s":"")."://".$_SERVER['SERVER_NAME'].$subDir;
}else{
    $global['webSiteRootURL'] = 'https://example.com/';
```

**Comment by jyrihovila** [comment]
> @jyrihovila With respect , but that is not true . I just created a VM without SSL , and using only http , and works perfectly . This part =does the job :
> 
> ```
> $global['webSiteRootURL'] = "http".(!empty($_SERVER['HTTPS'])?"s":"")."://".$_SERVER['SERVER_NAME'].$subDir;
> }else{
>     $global['webSiteRootURL'] = 'https://example.com/';
> ```

Well, I can't say exactly what's happening on your server, but (equally with respect) it clearly doesn't work on @guitarpound's site. Maybe because there's the reverse proxy that handles the SSL/TLS. If you go to the site maintained by @guitarpound and look into the source code, you'll see that all the references to images, CSS files etc. are http -- not https, as they should be. The site root url should definitely be configured to use https (instead of http) since it's the https version that's being delivered to the actual end users.

**Comment by jyrihovila** [comment]
> > @jyrihovila With respect , but that is not true . I just created a VM without SSL , and using only http , and works perfectly . This part =does the job :
> > ```
> > $global['webSiteRootURL'] = "http".(!empty($_SERVER['HTTPS'])?"s":"")."://".$_SERVER['SERVER_NAME'].$subDir;
> > }else{
> >     $global['webSiteRootURL'] = 'https://example.com/';
> > ```
> 
> Well, I can't say exactly what's happening on your server, but (equally with respect) it clearly doesn't work on @guitarpound's site. Maybe because there's the reverse proxy that handles the SSL/TLS. If you go to the site maintained by @guitarpound and look into the source code, you'll see that all the references to images, CSS files etc. are http -- not https, as they should be. The site root url should definitely be configured to use https (instead of http) since it's the https version that's being delivered to the actual end users. If the links point to http instead of https then the configuration is definitely wrong. It's a very bad idea to make references to non-SSL/TLS links within a SSL/TLS base URL.

**Comment by akhilleusuggo** [comment]
That is the issue ... The site SHOULD be under http . He's using an HTTPS when he doesn't have an SSL  . In that case the reverse proxy will require some extra configuration with port forwarding .
What I'm saying is , why not to SSL when you can ? NON-SSL only good if your site is hosted on the same host provider and you have a private network .

This is like cloudflare , ( cloudflare uses reverse proxy by NGINX ) . This picture is what I mean : 

![image](https://user-images.githubusercontent.com/52116577/89192805-bc187780-d5ad-11ea-8c97-c3230d8f0bb1.png)

Mixing HTTP with HTTPS on public networks , are like not using SSL at all ... Only on private networks are thinkable behind a NAT/Firewall .

**Comment by jyrihovila** [comment]
> @jyrihovila With respect , but that is not true . I just created a VM without SSL , and using only http , and works perfectly . This part =does the job :
> 
> ```
> $global['webSiteRootURL'] = "http".(!empty($_SERVER['HTTPS'])?"s":"")."://".$_SERVER['SERVER_NAME'].$subDir;
> }else{
>     $global['webSiteRootURL'] = 'https://example.com/';
> ```

The probable reason why the above solution does not work on the site that @guitarpound maintains is that from the server's perspective, the client appears to connect using http instead of https. This is because the SSL/TLS part is handled by a separate reverse proxy, and the traffic between the proxy and the YouPHPTube server works over http (not https).

YouPHPTube needs to know the root URL in the same form that the client browsers are using. The only way it can know it in a scenario like the one @guitarpound is having is through manual setting in the configuration file. Automatic detection can not work because of the reverse proxy.

**Comment by akhilleusuggo** [comment]
.htaccess can do the job [redirect] ( if he configured everything well )

**Comment by guitarpound** [comment]
Hi @jyrihovila & @akhilleusuggo ,

Thanks for kindly help reply the issue.

I just finished simulating the server in the same situation as the customer site.
I found to edit the file /videos/configuration.php & /Encoder/videos/configuration.php to $global['webSiteRootURL'] = 'https://example.com/';  isn't enough to solve the problem.

So, I will try to convert the AVideo site to https.

Thanks & BR,
