### ISSUE TITLE
ERR_RESPONSE_HEADERS_TOO_BIG while accessing Admin Panel and Dashboard

### ISSUE THREAD

**Issue by muzhdah** [WWBN/AVideo#3456]

**Comment by akhilleusuggo** [comment]
Very well known bug , there's a fix , but I don't know why @DanielnetoDotCom does not include the fix by default on every new installation ....
To fix this , you you had to add a line on the config file ( related to db timeout , or db requests = to unlimited ) ; but I don't remember it . @DanielnetoDotCom may assist here

**Comment by DanielnetoDotCom** [comment]
I am not sure what is the solution for that.

It does not happen with me, if you guys can provide me more details or guide me on how to reproduce, I may be able to fix it.

**Comment by akhilleusuggo** [comment]
Daniel you gave a solution to this time ago . I just don't remember it . It was adding a line on the config file .
You can't reproduce this error unless you have a lots of videos/views .

If you insist to reproduce this error . Go to the database and add high numbers to the views . You can do it with on DB with this command line : 

`UPDATE videos SET views_count = FLOOR(RAND()*(505761-5+1)+5);`

Just some random number will be added to the number of views . ( try to do it on a site where you don't care about the views )

**Comment by DanielnetoDotCom** [comment]
Tried at home

![image](https://user-images.githubusercontent.com/18009293/89210317-494fd200-d596-11ea-8df4-78383301f3a2.png)


Also on demo site

![image](https://user-images.githubusercontent.com/18009293/89210501-9633a880-d596-11ea-9ba4-1a5cd0360a81.png)


I could not reproduce it

**Comment by akhilleusuggo** [comment]
Yes but with 3000 videos for example you will not be able to enter that page without the async job enabled .

**Comment by DanielnetoDotCom** [comment]
In this case, I agree, that is why I have to redesign the stats page.

but I do not think the amount of videos is related to the ERR_RESPONSE_HEADERS_TOO_BIG

**Comment by akhilleusuggo** [comment]
It is related . Because you're asking for only 66 queries ( you only have 66 videos ). Try uploading to your home videos of just 3s , fast encoding . Make a 3000 videos and try it . 3000 queries will give you this error .

**Comment by DanielnetoDotCom** [comment]
I am saying this because I "think" I saw this error before in a site with not that many videos 

@muzhdah how many videos do you have?

@akhilleusuggo do you have this error in your site now?

**Comment by akhilleusuggo** [comment]
I have this error on another site where I have over 50k embeds yes .

**Comment by DanielnetoDotCom** [comment]
I see, I still not sure. 

For example, @JoshWho has about 20k videos and on his site, it does not appear.

![image](https://user-images.githubusercontent.com/18009293/89296137-51604e00-d638-11ea-8872-70729835de6f.png)

**Comment by muzhdah** [comment]
Find attached three snaps of the error I am get while click on Dashboard and Admin Panel please.


Rauf Khan 
Additional Director ICT
KUST, Kohat 
Phone: 92-922-554434 
Cell: 0334-8343004     

    On Tuesday, August 4, 2020, 05:53:35 PM GMT+5, Daniel Neto <notifications@github.com> wrote:  
 
 


I see, I still not sure.

For example, @JoshWho has about 20k videos and on his site, it does not appear.

**Comment by akhilleusuggo** [comment]
maybe he has the hidden $global on the configuration.php file .

**Comment by JoshWho** [comment]
I use an extra cache system that is not built into this site. Starting to learn a new system though that everyone will be able to use but still learning it all.

Cloudflare has a page rule you can use to cache on the Edge CDN servers. Using workers and strings to generate unique URLs for anon viewers so they all have their own separate cache keys and won't collide showing everyone the same cookies.

@DanielnetoDotCom You should look into this because it will basically give the website full CDN on every file including html but you have to make some changes around for it to work correctly. 

Having your site load from the CDN cuts down on CPU and makes your website 100 times faster, almost like having your site hosted by google kinda speeds.

Cloudflare has a option in business plans to bypass cookies under full page cache, but this is still achievable on the free plan if you know how to set cache headers on private for some things and public for all front end. 

This article was written for wordpress but I can see it implemented here maybe in the future some time. https://medium.com/homullus/fake-and-free-bypass-on-cookie-with-cloudflare-edge-cache-workers-for-wordpress-72c36d23c174

**Comment by JoshWho** [comment]
This wordpress plugin does exactly what I am talking about above if you want to reverse engineer it to see how it works. https://wordpress.org/plugins/edge-cache-html-cloudflare-workers/

**Comment by akhilleusuggo** [comment]
@JoshWho Do you also cache videos ? Because I wasn't able to cache the hls . 
And cloudflare would ban the proxy from MP4 videos ... Does your plan allows you to use the proxy for the videos too ?

**Comment by JoshWho** [comment]
I never had a problem with mp4s.

Currently I am back on the free plan and seems to work fine.

**Comment by JoshWho** [comment]
Here is more info on it here: https://support.cloudflare.com/hc/en-us/articles/200172516-Understanding-Cloudflare-s-CDN


bmp | ejs | jpeg | pdf | ps | ttf
-- | -- | -- | -- | -- | --
class | eot | jpg | pict | svg | webp
css | eps | js | pls | svgz | woff
csv | gif | mid | png | swf | woff2
doc | ico | midi | ppt | tif | xls
docx | jar | otf | pptx | tiff | xlsx

**Comment by JoshWho** [comment]
Using the Cache
Workers provide a way to customize cache behavior using Cloudflare's CDN for a zone’s private cache space. To learn about the benefits of caching see our Learning Center's article on What is Caching?

Interacting With The Cloudflare Cache
Cache is globally distributed and namespaced by zone of the incoming request, meaning a Worker script can not access or set a cache resource on an orange clouded zone’s namespace that differs from the zone of the incoming request.

Conceptually, there are two ways to interact with Cloudflare's Cache using a Worker:

Call to fetch() in a Workers script. Requests proxied through Cloudflare are cached even without Workers according to a zone's default or configured behavior (e.g. static assets like files ending in .jpg are cached by default). Workers can further customize this behavior by:
Setting Cloudflare cache rules (i.e. operating on the cf object of a request).
Store responses using the Cache API from a Workers script. This allows caching responses that did not come from an origin and also provides finer control by:
Customizing cache behavior of any asset by setting headers such as Cache-Control on the response passed to cache.put()
Caching responses generated by the Worker itself through cache.put()
The browser cache is controlled through the Cache-Control header sent in the response to the eyeball (the response passed or promised to event.respondWith()). Workers can customize browser cache behavior by setting this header on the response.

We won't discuss in this article, but other means to control Cloudflare's cache include: Page rules and Cloudflare cache settings. I highly recommend the article How to Control Cloudflare's cache if you wish to avoid writing JavaScript with still some granularity of control.

What should I use: the Cache API or fetch for caching objects on Cloudflare? For requests where Workers are behaving as middleware (i.e. they are sending a subrequest via fetch) it is recommended to use fetch. This is because pre existing settings are in place that optimize caching while preventing unintended dynamic caching. For projects where there is no backend (i.e. the entire project is on Workers as in Workers Sites) the Cache API is the only option to customize caching.

fetch
In the context of Workers a fetch provided by the runtime communicates with the Cloudflare cache. First, fetch checks to see if the URL matches a different zone. If it does, it reads through that zone's cache (or Worker!). Otherwise, it reads through its own zone's cache, even if the URL is for a non-Cloudflare site. Cache settings on fetch automatically apply caching rules based on your Cloudflare settings. fetch does not allow you to modify or inspect objects before they reach the cache, but does allow you to modify how it will cache.

When a response fills the cache, the response header contains CF-Cache-Status: HIT. You can tell an object is attempting to cache if one sees the CF-Cache-Status at all.

This template shows ways to customize Cloudflare cache behavior on a given request using fetch.

Cache API
The Cache API uses a cache key namespace on Cloudflare's CDN that is private to the Worker's zone. Cache objects are stored in the local datacenter handling the request and are not replicated to other datacenters.

When to use the Cache API:

When you need to read from cache without calling fetch. (i.e. send me the response from slow.com/resource if and only if it’s already a HIT on cache using caches.default.match(..).
Explicitly store a response in the cache using caches.default.put(..) and explicitly delete caches.default.delete(..). For example, say your origin is returning max-age:0 and you can't figure out how to change that header at your origin. You can explicitly tell Cloudflare to cache this response by setting cache-control: max-age=1000 on the response passed into cache.put().
This template shows ways to use the cache API. For limits of the cache API see limits.

https://developers.cloudflare.com/workers/about/using-cache/

**Comment by akhilleusuggo** [comment]
With the free plan does work fine ofc . The only issue is the future suspension .
On one of my domains , I had a suspension after 10TB of data transfer ( 15 days ) , they banned me , and requested me to change static files to non-proxies files .

On other domains I did not got any warning , but it could happen . The issue with cloudflare are the terms ( that nobody knows what they mean ) . 

> 2.8 Limitation on Serving Non-HTML Content
> The Service is offered primarily as a platform to cache and serve web pages and websites. Unless explicitly included as a part of a Paid Service purchased by you, you agree to use the Service solely for the purpose of serving web pages as viewed through a web browser or other functionally equivalent applications and rendering Hypertext Markup Language (HTML) or other functional equivalents. Use of the Service for serving video or a disproportionate percentage of pictures, audio files, or other non-HTML content is prohibited, unless purchased separately as a Paid Service.

Also they mension ''fair usage'' , witch they do not specify how much .

https://www.cloudflare.com/terms/

**Comment by JoshWho** [comment]
Those terms were written in 2012 JS.  CF is only ran by a handful of people. Lots of updating is lacking there. Edge Caching wasn't even a thing at the time they wrote those terms. Use to just use the main CF CDN to do it and that was why they would ban people. The Edge is data centers all over the world and is now considered the largest CDN network in the world. 

I think you are fine if you have a cloud storage that CF is connected with because they designed Amazon and Backblaze now to use the Edge.

They never updated the terms.

**Comment by akhilleusuggo** [comment]
I have a pro plan , never used the workers . ( I know they're the most ''expensive'' , since they're using CPU ) . Is the same with NGINX . 

> I think you are fine if you have a cloud storage that CF is connected with because they designed Amazon and Backblaze now to use the Edge.

Could you explain yourself a bit ? It must be the same , since I'll be still using the orange cloud .

**Comment by JoshWho** [comment]
Workers are now cheap. I just purchased unlimited workers for 5 bucks yesterday on one of my domains.

**Comment by akhilleusuggo** [comment]
Do you have any guide how to deploy the workers ?

**Comment by JoshWho** [comment]
Here you go https://blog.cloudflare.com/edge-side-includes-with-cloudflare-workers/

It is easier I think though to reverse engineer that wordpress plugin above. It auto creates the worker for the wordpress site and you can look at what it did in your cloudflare account.

**Comment by JoshWho** [comment]
> I have a pro plan , never used the workers . ( I know they're the most ''expensive'' , since they're using CPU ) . Is the same with NGINX .
> 
> > I think you are fine if you have a cloud storage that CF is connected with because they designed Amazon and Backblaze now to use the Edge.
> 
> Could you explain yourself a bit ? It must be the same , since I'll be still using the orange cloud .

Backblaze and Amazon did a deal with CF to serve your files on the edge and it will save you money on your cloud.
