### ISSUE TITLE
installing...I give up

### ISSUE THREAD

**Issue by whoalive** [WWBN/AVideo#3460]
4 times from a clean vm
your install instructions are horrible. 
google advice articles that are wrong cause their old or just incomplete. one even says done and never cloned the git. your sites install is horrible.  
got 1804 Ub setup on a 6core, 36g ram 1.5t vm(can add more) over MS datacenter. its nice  
installed apache2, php7.2, ffmpeg, mysql, and all the little stuff. but keep getting  unknown error in the install page. have tried every thing. if an err is set on the checkConfigeration.php it never makes it back to install.php cause theirs no error listed. really needed something later in the setup sequence.
ok ill pay the 70 setup fee, always wonder what was wrong

**Comment by jyrihovila** [comment]
@whoalive did you use php-fpm? There was a problem in version 9.2 of YouPHPTube that made it incompatible with php-fpm. The issue is now solved.

It's a fact that the instructions are outdated. We're trying to fix that by the force of the community. @DanielnetoDotCom is busy enough already taking care of the actual programming.
