### ISSUE TITLE
Is there a way to use less CPU when encoding?

### ISSUE THREAD

**Issue by freedomshare** [WWBN/AVideo#3570]
Is there a way to use less cpu when encoding? My cpu spikes up to%40 well encoding.

Make the site run like a turtle also sometime put a spining circle on videos I'm to assume it dude to high cpu usage

**Comment by akhilleusuggo** [comment]
40% is nothing . Should be 80-90% when encoding , and has really nothing to do with the site . ( not to me )
I bet the issue is coming from the hard-drive ( the IOPS ) on your drive .

I just wanna tell you something . Since I've seen your server configuration . If you have the chance to restart your entire configuration . I would install my server on an SSD `/` , this way your OS can run smoothly . Then install mount your drive ( the 3TB ) somewhere else to host the videos . 

This will speed up everything ( and most importantly the database and load pages ). And also you won't be needing to mount directories or drives for your nginx config .

You can mount the drive for a specific project or with symbolic-link https://github.com/WWBN/AVideo/wiki/Can-I-store-my-videos-in-another-location#creates-a-symbolic-link

Or in case you have YPT-Storage , you can install it on the same server , just on different location , and that will also help if case you have a CDN , will give you more control .

**Comment by freedomshare** [comment]
> 40% is nothing . Should be 80-90% when encoding , and has really nothing to do with the site . ( not to me )
> I bet the issue is coming from the hard-drive ( the IOPS ) on your drive .
> 
> I just wanna tell you something . Since I've seen your server configuration . If you have the chance to restart your entire configuration . I would install my server on an SSD `/` , this way your OS can run smoothly . Then install mount your drive ( the 3TB ) somewhere else to host the videos .
> 
> This will speed up everything ( and most importantly the database and load pages ). And also you won't be needing to mount directories or drives for your nginx config .
> 
> You can mount the drive for a specific project or with symbolic-link https://github.com/WWBN/AVideo/wiki/Can-I-store-my-videos-in-another-location#creates-a-symbolic-link
> 
> Or in case you have YPT-Storage , you can install it on the same server , just on different location , and that will also help if case you have a CDN , will give you more control .

I agree with you, just dont want to loose everything I also have the android app to, also all the effort you put in to get the live streaming working. Reinstall is on another server is not even a problem it would be the set up of configuration  that would be the problem for me.

**Comment by akhilleusuggo** [comment]
You can always backup the entire server .

tar --use-compress-program="pigz --best --recursive" -cf /var/backups/backup.tgz --exclude=/proc --exclude=/lost+found --exclude=/var/backups/backup.tgz --exclude=/mnt --exclude=/sys /

Note : I use `pigz` because it uses multi-threading for compression . ( I can't tell you for sure if it keeps permission ) . So the recommended is to backup, then manually open the files that you want to remember your old configuration and manually change them . Also , you'll need to install `pigz`

**Comment by freedomshare** [comment]
I will give this a try I have lots of server space an ips so i can run both at the same time well moving files  I'll probably remove gui from os this time

**Comment by freedomshare** [comment]
this is the error i got? tar: /var/backups/backup.tgz: Cannot write: Broken pipe

**Comment by akhilleusuggo** [comment]
I'm sure you haven't install the pigz
`sudo apt-get install pigz`

**Comment by freedomshare** [comment]
yes i did that first but i did sudo apt-get install -y pigz

**Comment by freedomshare** [comment]
also will it matter if i use desktop or server os when i back this up the current server is on Desktop?

i am installing os on another server right now

**Comment by freedomshare** [comment]
i forgot to sudo the command it might be working now

**Comment by akhilleusuggo** [comment]
I don't really understand what you mean . Why would you need ubuntu-desktop ?
It's heavier for no reason . Uses a lot of resources ( GUI etc )

**Comment by freedomshare** [comment]
That's what the current server has on it

**Comment by freedomshare** [comment]
i work with cpanel site's this was the first one that ran on it own server  and desktop was easy to learn

**Comment by freedomshare** [comment]
I'm installing none desktop to the new server right now

**Comment by freedomshare** [comment]
would you like to earn some cash doing a fresh install? on a fresh os

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
