### ISSUE TITLE
need plugin for vp9-dash

### ISSUE THREAD

**Issue by rkdoshi** [WWBN/AVideo#3602]
We have purchased HLS plugin but H265+HLS is not supported by chrome and VP9+HLD is also not supported.
Only choice for low bandwidth high quality delivery is VP9+DASH. Can we get similar plugin for DASH like HLS?
Regards,

**Comment by DanielnetoDotCom** [comment]
If you want you can hire me to add this feature.

If you are interested please email me at developer@youphptube.com

**Comment by DanielnetoDotCom** [comment]
Question! do you really think Dash is better than HLS?

I try to research about it and I could not find many comparisons regarding quality and HTML5 compatibility

**Comment by rkdoshi** [comment]
Hls does not work with vp9 and chrome does not work with hevc h265.


 Indian mobile networks are low bandwidths and use of high compressions
code  is essential,  What is choice if I have to use high compression codec
vp9 only option is dash.

Regards,

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom Google itself uses dash , is slightly faster load time , and gives you the posibility to add vp9 support . 
All the big companies right now are switching to vp9 . Try to download ANY 4K video from youtube , you gonna see it's in webm-vp9 codec .

Try this : youtube-dl -v https://youtu.be/LXb3EKWsInQ

**Comment by rkdoshi** [comment]
Yes, checked youtube video in india most of them are coded in vp9/h264.

Let me give our background, My company is traffic aggregator ( private IX)
since 2012. We have handled  google, akamai,amzon and netflix at network
layer to deliver best video quality almost buffer free to 1+ billion mobile
users.

We are network owners and admin. We  manage massive optic fiber network in
Mumbai Metro region about 50 million mobile and 300+TB of traffic, we are
also present in Delhi Chennai and Bangalore.

We know how to deploy nerwork  protocols and distribute content  by peering
thru bgp at IX. We have been part of growth from few gigs to thousands
gigs.

Now we want to use exprience in building own delivery platform, But we are
not coders and do not want to reinvent wheel by putting in house team for
coding.

At present in India DASH + VP9 is only available choice for us, vp9 alone
is working gine at small loads but will require DASH for higher load
situation.

Thanks for your timely guidance.

We are preparing full list of features and modifications, take professional
services to make the best platform.
Regards,

Ravindra

**Comment by DanielnetoDotCom** [comment]
Hi, 

I am willing to start to add vp9 support, can you guys provide me a good vp9 FFMPEG command line (encode speed/ video quality/ compression/ HTML compatible)? 
Does vp9  supports encryption like HLS?
Also, I will need one line to encode multiple resolutions like the one we have with HLS?

For example, this is the one we have for HLS ´ffmpeg -re -i {$pathFileName} -c:a aac -strict -2 -b:a 128k -c:v libx264 -vf scale=-2:360 -g 48 -keyint_min 48  -sc_threshold 0 -bf 3 -b_strategy 2 -b:v 800k -maxrate 856k -bufsize 1200k -b:a 96k -f hls -hls_time 6 -hls_list_size 0 -hls_key_info_file {$destinationFile}keyinfo {$destinationFile}low/index.m3u8 -c:a aac -strict -2 -b:a 128k -c:v libx264 -vf scale=-2:540 -g 48 -keyint_min 48 -sc_threshold 0 -bf 3 -b_strategy 2 -b:v 1400k -maxrate 1498k -bufsize 2100k -b:a 128k -f hls -hls_time 6 -hls_list_size 0 -hls_key_info_file {$destinationFile}keyinfo {$destinationFile}sd/index.m3u8 -c:a aac -strict -2 -b:a 128k -c:v libx264 -vf scale=-2:720 -g 48 -keyint_min 48 -sc_threshold 0 -bf 3 -b_strategy 2 -b:v 2800k -maxrate 2996k -bufsize 4200k -b:a 128k -f hls -hls_time 6 -hls_list_size 0 -hls_key_info_file {$destinationFile}keyinfo {$destinationFile}hd/index.m3u8´

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom Hello daniel ;

- VP9 is not supported on HLS , only dash .
- All vp9 are compatible on html and mobile apps 
- Encryption is only HLS as far as I know . Encryption on DASH is called CENC
-You can use one line to encode all ( YOU MUST ) . Also you may wanna go a step further , because vp9 is super slow compared to any other codec due to high compression . May need chunk support for later realizes .

A working line for testing purposes ( I can give you on 1 line , but I mean , without the dash script will not work ) .

`ffmpeg -i input.mp4 -vf scale=1280x720 -b:v 1800k -minrate 1000k -maxrate 2210k -tile-columns 2 -g 240 -threads 8 -crf 32 -c:v libvpx-vp9 -c:a libopus -quality good -speed 4 -y output.webm`

**quality** can be : **realtime** (for lives ) , **good** and **best** . ( don't use best , is for testing only , ultra super slow , slower then placebo )
**speed** can be  :  **1 , 2 , 3 , 4 ,** **5** to **8** only for realtime
**tile-columns** can be : 1 , 2 , 3 , 4 . This option is useful only if chunk encoding , and depending on the resolution , it's like dividing the frames . If the value is 2 , the the encoder will encode the frames into 4 rectangular regions .

There are many other option , specially for quicksync , witch I like so much . 
If you need more , check here : https://developers.google.com/media/vp9

**Comment by DanielnetoDotCom** [comment]
So the output is only 1 webm file? NOT multiple files like HLS?

If yes, why not just change the WEBM FFMPEG scripts?

![image](https://user-images.githubusercontent.com/18009293/92601059-b84dd400-f282-11ea-8cc2-d991135c09ef.png)

**Comment by akhilleusuggo** [comment]
Can be done ... The issue is : 

1- No automatic quality detection
2- VERY SLOW , since only process 1 at the time !
3- Dash gives better support .

NOTE : It is possible to run all on the same line , ofc it's possible . Take a look at this guide , will give you some ideas . 

http://wiki.webmproject.org/adaptive-streaming/instructions-to-playback-adaptive-webm-using-dash
