### ISSUE TITLE
Tags is not update in the My Videos pages

### ISSUE THREAD

**Issue by guitarpound** [WWBN/AVideo#3707]
Hi Daniel,

When click change video group in the My Videos pages.
The Tags is not change.  It always need to clear cache directory.

**Comment by DanielnetoDotCom** [comment]
thanks, this should do the trick

**Comment by guitarpound** [comment]
I already git pull.
But The problem is not fix.

**Comment by DanielnetoDotCom** [comment]
then please provide some screenshots and logs, maybe I did not understand what you mean.

can you reproduce it on github?

**Comment by akhilleusuggo** [comment]
@guitarpound I run into this same issue , because misunderstanding of the working process . Press `save` , and not `new` .
If you get errors on the logs , make sure you install the tables !

**Comment by guitarpound** [comment]
Hi Daniel & akhilleusuggo,

I tried force update to the latest version again today.
But the problem still there.
This video clip is the problem that I found.
https://drive.google.com/file/d/1xGHuGry0B0CC1E53-gw0jcuRgoEoW7dM/view?usp=sharing

**Comment by akhilleusuggo** [comment]
The real issue is not the cache . Are the boutons to add videos to user group .
If you go to edit video , and you add the user group manually , will show up immediately .

![image](https://user-images.githubusercontent.com/52116577/94946734-3cdbed00-04e5-11eb-8e91-678cf4352d50.png)

From my debugging , I've noticed that the bulk add user group , doesn't work properly .

**Comment by guitarpound** [comment]
Hi Daniel,

I tryout on demo site.
It's the same problem about bulk add/remove user group button.

**Comment by DanielnetoDotCom** [comment]
Thanks for confirming that, I am sending an update soon.
