### ISSUE TITLE
Alternative Directory for video thumbs

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#3786]
Currently my video thumbs seem to be storing in the same directory as my SSD drive I was originally thinking was just being used for the cache. 

This drive is not as big as my main drives any way to have new thumbnails and gifs save to a alternative directory and still keep the cache on the ssd?

**Comment by JoshWho** [comment]
Well Now my SSD is completely out of storage space and my whole site is unusable.

**Comment by JoshWho** [comment]
Ok manage to reboot the server and now it is not full anymore. Weird. Must been a temp directory that only deletes on reboot or something.

**Comment by JoshWho** [comment]
@DanielnetoDotCom  My SSD is running out of space

**Comment by DanielnetoDotCom** [comment]
what exactly directory is full?

with what kind of files?

**Comment by akhilleusuggo** [comment]
the way the cache work is wrong . The cache last let's say 1h . If you have 1000 users/h , then will generate 1000 caches of each page they visit . When they visit the next day , the cached file are not re-written , just staying there , occupying space .

I had to add a crontab to delete files older then 24h on `/var/www/html/AVideo/videos/cache/*` , because in matter of few house , only by bots ( google,bingo,yahoo,yandex ) etc will generate up to 10gb/day ( depending on how much videos you're hosting ofc ) , just by crawling pages . And I don't even have the option enabled of ''Generate cache per user" . With that enabled , it's gg

**Comment by JoshWho** [comment]
My only SSD drive that u set the cache too is full. You have it setup like a symlink or something

**Comment by DanielnetoDotCom** [comment]
> the way the cache work is wrong . The cache last let's say 1h . If you have 1000 users/h , then will generate 1000 caches of each page they visit . When they visit the next d

You are right, a crontab is the best way to clean up the cache.

**Comment by DanielnetoDotCom** [comment]
> My only SSD drive that u set the cache too is full. You have it setup like a symlink or something I see like 175k thumbnails and files in the /mnt/md0/videos directory.
> 
> I thought we was only using the SSD for the cache?

I am not sure the location of your cache folder, but the cache folder MUST be visible on the web, that is why we use it inside the videos folder

**Comment by JoshWho** [comment]
THank you all moved and fixed now.
