### ISSUE TITLE
Livestream video holder files

### ISSUE THREAD

**Issue by fakeologist** [WWBN/AVideo#3815]
I have one user livestreaming, but I don't save the videos.
There are endless filename/sessions in the video list at 0.00kb
How do I stop these entries from saving/being listed?
I don't want to have to delete them manually every day.
![image](https://user-images.githubusercontent.com/66537018/95698437-ed499f80-0c0f-11eb-8ec8-83e856f27dec.png)

**Comment by jengajenga** [comment]
I would also like to know this. I have thousands of those little files.

**Comment by DanielnetoDotCom** [comment]
for this we need to check the logs.

if the recorded live is too small (less than 1 MB) we do not process it.

but this looks like for me is some error on the encoder. but it must be confirmed on the log.

are you able to reproduce it or it does happen randomly?

**Comment by jengajenga** [comment]
I know this is not my thread, but I have the same problem.

For me it happens every time the livestream reaches the limit in nginx conf. so if nginx says 2048mb, when it reaches 2048mb, it creates that file under the videos section in admin.

and then in the videos folder, they appear there in full size which i have to delete every 2 or so days so that it doesn't take my space. 

See the screenshot. 

![little_files](https://user-images.githubusercontent.com/65451390/95863202-94434e00-0d6c-11eb-917f-b12b8d75ec08.png)

One time, I went into the videos page, unlisted ALL the 0.00kb files. ALL of my livestreams went off.

**Comment by DanielnetoDotCom** [comment]
do you still have disk space in your server? how is it?

and I still need the logs

**Comment by fakeologist** [comment]
Any update on this issue?

**Comment by fakeologist** [comment]
Bump

**Comment by DanielnetoDotCom** [comment]
@fakeologist can you please clarify what is the issue again?

**Comment by fakeologist** [comment]
![image](https://user-images.githubusercontent.com/66537018/100597476-82414e80-32cb-11eb-9f44-ebf662466f3a.png)

The above page is filled with livestream placeholder files. I don't want them in my saved videos if possible.

**Comment by DanielnetoDotCom** [comment]
you can disable the SendRecordedToEncoder plugin

currently, we do not have an option to save only specific users streams
