### ISSUE TITLE
Clean Github

### ISSUE THREAD

**Issue by wetubeclub** [WWBN/AVideo#3879]
Hello to all AvVideo members
I want to suggest the following
I would ask Daniel to open a category somewhere else just for suggestions
a category only with script errors
a category for customers
a category for those who want  to fix the problem that have  or the conversion to the script
github is full of many questions and free questions that if you look at it professionally I would not answer any question without pay if I were in the place of Daniel
forgive me but it is a rule of commerce
I personally have never had problems with upgrades or anything on my site
we have a free script very good in my opinion but we also have to give money to the developer to live and he
for the end all this in a friendly tone and without misunderstanding towards me
thanks
Ilias

**Comment by JoshWho** [comment]
Daniel does have this all in separate categories as I am sure u seen it when you opened this thread, you had to choose were correct?

Daniel answers questions because it is a open source code that is still in development. User input is one of the best things in the world when it comes to development. 

He does make sales and also has a paid support option. He is not greedy, which is what even made me look at this project to begin with. This is not only the best Video Live Stream script, but also has the best support and community to solving any future bugs.

Rules of commerce, wth is that? Something the Rockefellers said.

**Comment by jengajenga** [comment]
> Daniel does have this all in separate categories as I am sure u seen it when you opened this thread, you had to choose were correct?
> 
> Daniel answers questions because it is a open source code that is still in development. User input is one of the best things in the world when it comes to development.
> 
> He does make sales and also has a paid support option. He is not greedy, which is what even made me look at this project to begin with. This is not only the best Video Live Stream script, but also has the best support and community to solving any future bugs.
> 
> Rules of commerce, wth is that? Something the Rockefellers said.

I couldn't have put it any better. Good thing we have Daniel and not this guy ... :)

**Comment by wetubeclub** [comment]
you probably do not understand what I mean
let github stay only for bugs or if there is a forum for the rest so we can watch them sorted
as for Daniel I have only the best to say about him
Thank you
Ilias
