### ISSUE TITLE
Why am I seeing this?

### ISSUE THREAD

**Issue by jengajenga** [WWBN/AVideo#3964]
![on_pub](https://user-images.githubusercontent.com/65451390/98269144-76998b00-1f9e-11eb-96d1-65874c1382cc.PNG)

hi @DanielnetoDotCom , hi @akhilleusuggo 

I get this on my STAT page and not the usual. This is a Live Server I have set up.

Also, the video remains OFFLINE and the notification at the top says THERE'S NO STREAMING NOW.

But if I put the HLS in VLC, it plays perfectly.

Is there something I have missed?

Thanks

**Comment by jengajenga** [comment]
Helloo, some assistance kindly @DanielnetoDotCom , @akhilleusuggo 

Because of this I am
1. Unable to disconnect a stream since the controls only show up when the video says ONLINE
2. I am unable to publish more than one stream on this Live Server.

Thanks.

**Comment by Progressed36** [comment]
having the same problem but I'm not even able to livestream. OBS is sending, Visible in stats but video remains offline.

errorlog:
`[06-Nov-2020 15:05:44 Europe/Berlin] PHP Warning:  implode(): Invalid arguments passed in /var/www/AVideo/plugin/PlayerSkins/PlayerSkins.php on line 200
[06-Nov-2020 15:05:44 Europe/Berlin] PHP Warning:  implode(): Invalid arguments passed in /var/www/AVideo/plugin/PlayerSkins/PlayerSkins.php on line 235
[06-Nov-2020 15:11:23 Europe/Berlin] AVideoLog::DEBUG: User::loadFromUser(admin)  SCRIPT_NAME: /plugin/Live/index.php
[06-Nov-2020 15:11:23 Europe/Berlin] AVideoLog::DEBUG: User::loadFromUser json [{"file":"\/var\/www\/AVideo\/objects\/user.php","line":49,"function":"loadFromUser","class":"User","object":{},"type":"->","args":["admin"]},{"file":"\/var\/www\/AVideo\/plugin\/Live\/view\/modeYoutubeLive.php","line":31,"function":"__construct","class":"User","object":{},"type":"->","args":[0,"admin",false]},{"file":"\/var\/www\/AVideo\/plugin\/Live\/index.php","line":26,"args":["\/var\/www\/AVideo\/plugin\/Live\/view\/modeYoutubeLive.php"],"function":"include"}] SCRIPT_NAME: /plugin/Live/index.php
`

**Comment by akhilleusuggo** [comment]
this issue is coming from redirecting the https .
rtmp for now doesn't have native support for https .

If on your apache2 vhost config you're redirecting all traffic to https , then you will have this issue .
There are many repeated issues related to this . Daniel won't fix it . I've been looking into Daniels config setup , and it's working for him just because he hosted the nginx-rtmp and the main AVideo on the same server , and indicated it as localhost/AVideo/etcetc .

You need to bypass https on on_connect.php, on_done.php, on_play.php , on_publish.php , on_record_done.php
Conclusion : **If you pointing your on_done , on_publish , on_record , with http , your site url MUST be accessible with http, and not redirecting to https !**


########### Template message #############

Just to add some very important detail . I know why @DanielnetoDotCom does not have this issues on his installations . And that because the HTTPS redirect works ONLY if your nginx.conf is pointing to LOCALHOST . In other words , if you streamer site , and nginx-rtmp are hosted on the same server , you can use `http://localhost/Avideo/plugin/Live/on_publish.php` instead of your domain name , and will work without the need or any type of redirect , since it's locally hosted under the SAME SSL . 

If you're pointing to a domain name , or your nginx-rtmp is hosted somewhere else , this will not work !! 
My solution was this : 

```
RewriteEngine on
# Go to https if not on /plugin/Live/

RewriteCond %{SERVER_PORT} =80
RewriteCond %{THE_REQUEST} !/plugin/Live/ [NC]
RewriteRule ^(.*)$ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]

# Go to http if on /for on_connect.php, on_done.php, on_play.php , on_publish.php , on_record_done.php /

RewriteCond %{SERVER_PORT} !=80
RewriteCond %{THE_REQUEST} /plugin/Live/* [NC]
RewriteRule ^(.*)$ http://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]

</VirtualHost>
```

Adding this lines to the /etc/apache2/sites-available/yoursite.conf , or .htaccess will fix the issue .

This issue in known https://github.com/winshining/nginx-http-flv-module/issues/130
This would require the support on RTMPS if we want to use httpS://localhost/Avideo/plugin/Live/on_publish.php

Conclusion : **If you pointing your on_done , on_publish , on_record , with http , your site url MUST be accessible with http, and not redirecting to https !**

**Comment by jengajenga** [comment]
> this issue is coming from redirecting the https .
> rtmp for now doesn't have native support for https .
> 
> If on your apache2 vhost config you're redirecting all traffic to https , then you will have this issue .
> There are many repeated issues related to this . Daniel won't fix it . I've been looking into Daniels config setup , and it's working for him just because he hosted the nginx-rtmp and the main AVideo on the same server , and indicated it as localhost/AVideo/etcetc .
> 
> You need to bypass https on on_connect.php, on_done.php, on_play.php , on_publish.php , on_record_done.php
> Conclusion : **If you pointing your on_done , on_publish , on_record , with http , your site url MUST be accessible with http, and not redirecting to https !**
> 
> ########### Template message #############
> 
> Just to add some very important detail . I know why @DanielnetoDotCom does not have this issues on his installations . And that because the HTTPS redirect works ONLY if your nginx.conf is pointing to LOCALHOST . In other words , if you streamer site , and nginx-rtmp are hosted on the same server , you can use `http://localhost/Avideo/plugin/Live/on_publish.php` instead of your domain name , and will work without the need or any type of redirect , since it's locally hosted under the SAME SSL .
> 
> If you're pointing to a domain name , or your nginx-rtmp is hosted somewhere else , this will not work !!
> My solution was this :
> 
> ```
> RewriteEngine on
> # Go to https if not on /plugin/Live/
> 
> RewriteCond %{SERVER_PORT} =80
> RewriteCond %{THE_REQUEST} !/plugin/Live/ [NC]
> RewriteRule ^(.*)$ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]
> 
> # Go to http if on /for on_connect.php, on_done.php, on_play.php , on_publish.php , on_record_done.php /
> 
> RewriteCond %{SERVER_PORT} !=80
> RewriteCond %{THE_REQUEST} /plugin/Live/* [NC]
> RewriteRule ^(.*)$ http://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]
> 
> </VirtualHost>
> ```
> 
> Adding this lines to the /etc/apache2/sites-available/yoursite.conf , or .htaccess will fix the issue .
> 
> This issue in known [winshining/nginx-http-flv-module#130](https://github.com/winshining/nginx-http-flv-module/issues/130)
> This would require the support on RTMPS if we want to use [httpS://localhost/Avideo/plugin/Live/on_publish.php](httpS://localhost/Avideo/plugin/Live/on_publish.php)
> 
> Conclusion : **If you pointing your on_done , on_publish , on_record , with http , your site url MUST be accessible with http, and not redirecting to https !**

My brother, thank you very much! After 6 straight hours of playing with these settings, it has finally worked.

Thank you again very much.
