### ISSUE TITLE
aVideo Mobile android app

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo#4096]
I am having issues trying to access both my sites from the mobile app on android phone and this is the error I get.

![photo_2020-11-29 10 11 33](https://user-images.githubusercontent.com/58882903/100536780-9170bf80-322b-11eb-803a-8b36470dd913.jpeg)

The sites work fine and I don't see anything in logs. It was working few days ago so i am not sure what changed or what I should check. Can you please assist?

**Comment by wetubeclub** [comment]
the same to me!!

Thank you
Ilias

**Comment by DanielnetoDotCom** [comment]
does the same happen with the demo site?

do you have a valid SSL?

**Comment by wetubeclub** [comment]
how can we see if it has valid ssl och
in which file is it to check?

Thank you
Ilias

**Comment by DanielnetoDotCom** [comment]
Hi

I found an error in my platform after a server upgrade, please try again and let me know if it still appearing

**Comment by wetubeclub** [comment]
Thank you Daniel is ok for me!!
Working fine

**Comment by shanejsalter1** [comment]
I am having a similar issue with the IOS App.  Originally when I built my site I did not set the root to https://www.folmedia.org, the site runs from https://www.folmedia.org/YouPHPTube and I use a 301 redirect so that users can get to the site by going to https://www.folmedia.org

when I try to get to https://www.folmedia.org in the App I get the same error message above and when I look at the Apache2 error log it shows the APP trying to access index.php in /var/www/root/html instead of /var/www/html/YouPHPTube

If I put the full address https://www.folmedia.org/YouPHPTube in the IOS App it works fine, but this is cumbersome to have users go through.  I thought about moving everything to the /var/www/html directory but I have a Roku Channel that accesses files from https://www.folmedia.org/YouPHPTube and many other links from other sites that would be broken if I did so.

Any suggestions would be helpful.  I am running on the latest site code (as of today) and the latest IOS Avideo App.

**Comment by DanielnetoDotCom** [comment]
I guess it cannot be redirected, the URL must be the direct URL.

for example https://www.folmedia.org/YouPHPTube

**Comment by shanejsalter1** [comment]
Thanks, I will discuss with the Pastor the potential for having you package IOS and Android Apps specifically for us so that users can just install and go without having to input a URL.

Great Product, works great with Roku with a custom JSON file.

**Comment by DanielnetoDotCom** [comment]
Awesome, BT, what did you do on Roku? how do you use it?

**Comment by shanejsalter1** [comment]
I created a Channel on Roku that links back to the videos stored on my Avideo site.

Basically:
Created Roku Free Developer Acct
Downloaded JSON Feed Manager Software - https://github.com/rrirower/json-feed-manager
Recorded YPTuniqid value from the Avideo DB for each file that I wanted to publish on my Roku Channel
Linked the jpg and _720.mp4 file for each YPTuniqid into the Feed Manager and uploaded the configured JSON file to the root of my site
In the Roku Channel Manager Dashboard I point to the JSON file and it streams the videos from my site

My Roku Channel publish date/time is today at Noon Central so if you want to see what the channel looks like (if you have a Roku) you can search for "Fountain of Life Media" in the Roku Channel Directory any time after Noon Central Time today.

**Comment by DanielnetoDotCom** [comment]
I do not have a Roku setup now, but definitely I will check it in the future.

**Comment by bertalanimre** [comment]
The very same issue is with me. The application is installed and working on a CentOS 7 machine and available via SSL (wildcard is used).
However, when I try to connect with the Android application, I get the same error message.
The site is available only via SSL and everything on port 80 is redirected to 443. 
In NginX I've seen the following errors when I try to "Check Site" in the Android application:

```
2020/12/07 15:03:11 [error] 15221#15221: *404 open() "/var/www/html/mytube.mycompany.hu/status" failed (2: No such file or directory), client: 5.180.25.128, server: mytube.mycompany.hu, request: "GET /status HTTP/1.0", host: "mytube.mycompany.hu"
```
Indeed, there was no "status" folder inside the main git repository. So I've created one. The error message turned into this:
```
2020/12/07 15:03:57 [error] 15226#15226: *406 directory index of "/var/www/html/mytube.mycompany.hu/status/" is forbidden, client: 5.180.25.128, server: mytube.mycompany.hu, request: "GET /status/ HTTP/1.0", host: "mytube.mycompany.hu"
```

I don't understand the issue this time because the fodler has 775 towards the user who is running both PHP and NginX and owns the folder in the file system. Never the less, I've given 777 to status folder, but the error message is still the same. 

Am I the only one who sees this issue right now?

**Comment by bertalanimre** [comment]
A small addition:
If I install the whole stuff on Ubuntu with Apache, I get the same error message on the phone, but this appears only in any of the Apache logs:
```
==> /var/log/apache2/avideo.access.log <==
5.180.25.128 - - [08/Dec/2020:15:22:05 +0100] "GET /status HTTP/1.0" 200 5004 "-" "-"
```

And in `avideo.log`:
```
[08-Dec-2020 14:24:35 Africa/Abidjan] AVideoLog::DEBUG: Live::getStatsObject RTMP Server (https://mytube.mycompany.hu:8443/stat) is NOT responding we will wait less from now on => live_servers_id = (0)  SCRIPT_NAME: /plugin/Live/stats.json.php
[08-Dec-2020 14:24:35 Africa/Abidjan] AVideoLog::DEBUG: wget: ERROR the url download but is empty https://mytube.mycompany.hu:8443/stat, /var/www/AVideo/videos/cache/YPTurl_get_contents/6834ea7411077f53d2f359fad534f875 SCRIPT_NAME: /plugin/Live/stats.json.php
[08-Dec-2020 14:24:35 Africa/Abidjan] AVideoLog::ERROR: Live::getStatsObject RTMP Server (https://mytube.mycompany.hu:8443/stat) is OFFLINE, we could not connect on it => live_servers_id = (0)  SCRIPT_NAME: /plugin/Live/stats.json.php
```

**Comment by baoang** [comment]
![](https://i.imgur.com/ZiyfaC7.png)

some lines of error msg when I tried to connect to a streamer, the default one when launch the app on Android.

The app version is v8.6.

I also tried to connect to my own site, but with the same result/error codes. The website is working well from any browsers on pc computer, and on mobile browsers(Opera and FireFox).

Anyone with the same situation?

**Comment by DanielnetoDotCom** [comment]
Are you on a good internet connection?

I am testing on iOS and works fine

**Comment by baoang** [comment]
Thank you, @DanielnetoDotCom for your reply.

Yes, the internet connection is OK. I am connected via Wifi as well as the mobile network. My PC is connected via Wifi and browsers on PC work ok.

I downloaded APK files v8.6 and v7.1 from apkture since Google Play is not accessible directly by Android phone here.

My Android phone's version is v7.

Now my guess is somewhat related to the hardware/phone. It's Huawei brand and perhaps some components associated with the phone system is not compatible with SSL or sth.  Looks I'll have to wait some time and pick a new phone to try that.
