### ISSUE TITLE
Server requirements and its max amount of live viewers

### ISSUE THREAD

**Issue by Progressed36** [WWBN/AVideo#4109]
I want to get a clear view of the server requirements and how many users they could handle.

How many users for:

- 4 vCPU, 8GB RAM: ? livestreamviewers
- 8 vCPU, 16GB RAM: ? livesrteamviewers
- 16 vCPU, 32GB RAM: ? livestreamviewers

These servers have 1Gbs ports.

My plan is to allow a max of 720p to be viewed by the viewers.

**Comment by bbyrdhouse** [comment]
Get as much ram as you can afford ... the server I use has 16Gb of ram and I can have about 8-10 viewers and then the stream starts buffering real bad ... I broadcast in 720p and have 250Mbs upload speed to the streamer.

I am not sure what is more important, the ram or the cpu/threads.

**Comment by akhilleusuggo** [comment]
Don't get ram , get IOps . I've done stress tests of 24 simultaneous streams on a server with 2 cores / 2gb ram , and I had no issues .
The buffering is coming IOps bottleneck and packet-loss.

If you're planning on changing the /HLS directory for storing the hls_fragment , you could create a RAM disk , or additional disk drive ( ssd ). If you opt for RAM disk , you wont be able to use DVR ( or at the least , will not hold more then 5mn ) , since you gonna be space limited .

I have additional ssd , and my dvr can go up to 2h stream playback , without problem . Youtube does have 4h .
That's up to you .

NGINX doesn't require much of ram , but you need IOps

**Comment by bbyrdhouse** [comment]
This page indicates that IOPs are not that critical ... https://storageswiss.com/2015/02/23/what-are-iops-and-should-you-care/

I can't speak to the importance of IOPs with regards to live streaming and buffering because i have never run a livestreaming site before, so I am learning on the fly.

I've a ton of questions of things that I can do to get the best performance possible, I just feel kind of bad to keep asking them.

I'm using a dedicated server (rented from Daniel) to host the LiveStreamer and the Encoder, but I also manage a couple of VPS' that I wonder if I could utilize those to help in some way (encoder maybe) ... is that even possible?

**Comment by Progressed36** [comment]
This is exactly why i asked this question. My research told me this:

Encoding you need CPU and visitors you need RAM. 

For me personally i just need to know the visitors as my site isn't public and I want to embed 1 stream into a site, so I don't have multiple streamers. Just 1 livestreamer and multiple viewers.

**Comment by DanielnetoDotCom** [comment]
> I'm using a dedicated server (rented from Daniel) to host the LiveStreamer and the Encoder, but I also manage a couple of VPS' that I wonder if I could utilize those to help in some way (encoder maybe) ... is that even possible?

Yes you can install encoders in your VPSs

**Comment by akhilleusuggo** [comment]
@Progressed36 In your initial question you have not mentioned nothing regarding to encoding .
Visitors you don't need ram , not on nginx . It's a static file , not a dynamic one . IOps are required to create/convert as quick as possible the FLV live-stream ( from your local computer ) to the server into hls_fragments , then served to the viewers .

Encoding will require a GPU ( from my point of view , CPU is waste of resources ). + you need high clock speed , not only number of cores , or you won't be able to keep up decoding+encoding at the same time .

But you can give it a try .

**Comment by excitedbox** [comment]
If you look at what streaming sites calculate you should be able to host a LOT more than 10-20 viewers. You need a dedicated connection. 1gbit for roughly 1-2k viewers when streaming properly encoded video HD. A lot has to do with the codec you use. You will 100% want a GPU for encoding. A CPU will barely manage to encode 1-2 streams live while something like a encoding accelerator will do many at once. 

Another option is to build the encoding into your streaming app and use the streamers PC to encode the video before they upload the HLS chunks instead of the video stream. The upside is you no longer need a video encoding server and your bandwidth usage goes down a TON. OBS supports this and so do most other modern software.

You should also look into multicast. Multicast is more like a TV broadcast and your server sends the data out once to many viewers instead of an individual connection with each viewer. This means millions of people could watch the same stream but your server sees 1 connection. This saves bandwidth from your server by routing 1 connection of your stream from the US to Germany lets say and then having a router there connect to all your EU viewers from there instead of sending many copies of the data across the Atlantic.
Sadly even though most internet infrastructure can handle multicast it was never properly implemented by ISPs so now it is sent over specialized routers and you usually have to pay for it although from and ISP standpoint it costs them NOTHING and they should be happy to have you use it. It is really a win-win for ISP and Website but they are greedy. For something like a sporting event or even something like a twitch streamer it can still save a ton of money in server resources. This only helps in a live situation though.

If you really plan on getting big you will need a CDN. Companies like cloudflare use multiple locations around the world to host copies of your stream to get even higher efficiency than multicast while also offering those benefits on non live streams. Much like with multicast it uses server racks in many datacenters to host your chunks and viewers connect to whoever is closest. The added benefit is that you are only hosting a few connections per server instead of many on 1. If your encoding server connects to 10 CDN edge nodes it is as if you have 10 viewers while each of those edge nodes might connect with 100s of viewers.

When it comes down to it with the right setup a big server can handle 10-20k connections when you get into the 128gb+ range of RAM and 10gbit connections so divide 128gb by 10,000 and it will give you a rough estimate of what is possible. Even a raspberry pi can host 10 streams from an ssd once they are already encoded. It might even make sense to buy a few media server SBCs and use them as an encoding cluster to upload to a bigger server. At a 1 time cost of ~$20-40 each and $20 for a small SSD you could set up many of them in a small cluster and save a ton of money. A 4U co-location slot shouldn't be much and a 10gig network port to another server is almost free. You buy a cheap 24 port router used and use your server to send the encoding tasks to the SBCs. When you figure that an encoder server costs about $3k with 16 cards you can get down to about half the price using a cluster of ARM SOCs.

Something else to consider is that a 10gbit internet connection is not that expensive. I would pay $1200 a month here. That could host about 10k simultaneous views or 240k hours of streaming per day at 100% capacity. If you have an 8x8 area in your house you can place about 3 42U server racks there and host everything yourself. You could even provide your town with WiMax internet. (~15mi range depending on elevation) You would need about $4k worth of equipment but at $50-100 a month that 10gig line is paid for quickly. An ISP will put 500-1000 customers on those and promise 100-200Mbit speeds.
