### ISSUE TITLE
Are The NGINX hls_varient _low, _mid and _hi BANDWIDTH numbers pre-determined or can we change them?

### ISSUE THREAD

**Issue by bbyrdhouse** [WWBN/AVideo#4115]
In the NGINX.conf file there is the following snippet for HLS adaptive.
`application adaptive {
                        live on;
                        hls on; 

                        hls_path /HLS/live;
                        hls_nested on;
                        hls_playlist_length 60m;
                        hls_fragment 6s;
                        allow play all;
                        allow publish 127.0.0.1;
                        deny publish all;

                        hls_variant _low BANDWIDTH=400000;
                        hls_variant _mid BANDWIDTH=2100000;
                        hls_variant _hi  BANDWIDTH=4200000;
                    }`

My question is, the low, mid, and hi numbers, do they relate to live streams or vod?

Can they be changed (lowered)?

Will lowering these numbers = more people being able to watch a livestream with less buffering?

What do these numbers translate to wrt how a person views a video or stream? 720p, 590p, 480p, 360p etc ... 

Can we add another option in there? If yes, is this the only place we'd need to edit or are there other files that would necessitate changing?

Also, what does the `hls_playlist_length 60m;` reference?

**Comment by DanielnetoDotCom** [comment]
They are related to Live only.
and yes you can change them

Regarding your live server, [here](https://github.com/arut/nginx-rtmp-module) is the correct place to get help

**Comment by akhilleusuggo** [comment]
@bbyrdhouse hls playlist is the dvr option . Basically on a live-stream you can't go back and rewatch the stream until is over . With DVR you can playback the live-stream while the stream is playing . ( in your case is 60mn ) . So you can go back up to 60mn ( of the current time of the live-stream ) . Older hls_fragment then 60mn , will be deleted . Once the stream is over , the entire video will be sent to the encoder to get ready for storage and playback as a normal video .

PS: That's why is very important the IOps , with low iops , this feature gonna take for ever to load , and may even crash the stream .
