### ISSUE TITLE
How Can I Either Delete the "Default" Category or Force Users To Select a Category Other Than Default

### ISSUE THREAD

**Issue by bbyrdhouse** [WWBN/AVideo#4138]
Yes, I am aware that "CustomizeAdvanced" plugin has an option that says "forceCategory", however, this does not address the problem of people uploading videos and dumping them in "Default" and then I have to go back and manually select the category for them.

I tried to delete the "Default" category but it won't let me delete it even though there are currently no videos in that category.

Is there any way I can "force" people to select a proper category or to just delete the "Default" category?

**Comment by DanielnetoDotCom** [comment]
What about this

![image](https://user-images.githubusercontent.com/18009293/101414559-12335980-38c5-11eb-9ecc-91ca847a0526.png)

**Comment by techiesces** [comment]
I personally just changed default to other and if people dump into other then I guess they don't get filed at the top.  Change the other category to lowest priority so that it falls to the bottom.  Reward the ones who file properly.. give them an incentive to not just dump.. Don't do the work for them.  Give them a consequence of bad behavior haha

**Comment by bbyrdhouse** [comment]
@techiesces - I like that ... the "I'm to lazy to select a category" category ... ;-)
