### ISSUE TITLE
PPV plans user groups don't work

### ISSUE THREAD

**Issue by tonuzo** [WWBN/AVideo#4200]
Repoduced on demo site

Make a PPV plan and choose a user group for the plan.
![image](https://user-images.githubusercontent.com/63721378/102611291-50d3da00-4137-11eb-9b4b-01e888bfd27a.png)

Go to PPV videos tab and the plan you just created doesn't show up.
![image](https://user-images.githubusercontent.com/63721378/102611344-6517d700-4137-11eb-8c41-ead4d1dc2941.png)

Make a PPV plan without using a user group.
![image](https://user-images.githubusercontent.com/63721378/102611433-90022b00-4137-11eb-8f48-267b601e7c6d.png)

On PPV videos tab the plan is working.
![image](https://user-images.githubusercontent.com/63721378/102611473-a90adc00-4137-11eb-822c-091fef54b73d.png)

**Comment by DanielnetoDotCom** [comment]
Hi, this is not a bug, this is expected.

If you choose a user group for a plan, you cannot select a video for it. otherwise, it will be conflicting rules.

To add a video on this user group use the videos manager, edit the video and uncheck the **Public Media** option

![image](https://user-images.githubusercontent.com/18009293/102612121-f161d400-410e-11eb-9bdd-7b1ac0849dd5.png)

**Comment by tonuzo** [comment]
Ok, I see. Thanks for your response.

br,
T
