### ISSUE TITLE
live is not coming online

### ISSUE THREAD

**Issue by ricasht** [WWBN/AVideo#4258]
The streaming is being sent, but only being played on the administration panel, and the live is not being published on the website.
It has the markings in "offline" and where it should publish the live.

![Erro Live](https://user-images.githubusercontent.com/69056431/103236254-2944f480-4923-11eb-9636-d614de57f7ab.png)

**Comment by ricasht** [comment]
![Erro Live](https://user-images.githubusercontent.com/69056431/103236226-1500f780-4923-11eb-881a-70305367f911.png)

**Comment by akhilleusuggo** [comment]
#### template response ####

And that because the HTTPS redirect works ONLY if your nginx.conf is pointing to LOCALHOST . In other words , if you streamer site , and nginx-rtmp are hosted on the same server , you can use `http://localhost/Avideo/plugin/Live/on_publish.php` instead of your domain name , and will work without the need or any type of redirect , since it's locally hosted under the SAME SSL . 

If you're pointing to a domain name , or your nginx-rtmp is hosted somewhere else , this will not work !! 
My solution was this : 

```
RewriteEngine on
# Go to https if not on /plugin/Live/

RewriteCond %{SERVER_PORT} =80
RewriteCond %{THE_REQUEST} !/plugin/Live/ [NC]
RewriteRule ^(.*)$ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]

# Go to http if on /for on_connect.php, on_done.php, on_play.php , on_publish.php , on_record_done.php /

RewriteCond %{SERVER_PORT} !=80
RewriteCond %{THE_REQUEST} /plugin/Live/* [NC]
RewriteRule ^(.*)$ http://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]

</VirtualHost>
```

Adding this lines to the /etc/apache2/sites-available/yoursite.conf , or .htaccess will fix the issue .

This issue in known https://github.com/winshining/nginx-http-flv-module/issues/130
This would require the support on RTMPS if we want to use httpS://localhost/Avideo/plugin/Live/on_publish.php

Conclusion : **If you pointing your on_done , on_publish , on_record , with http , your site url MUST be accessible with http, and not redirecting to https !**

**Comment by ricasht** [comment]
thanks, it worked
