### ISSUE TITLE
Notification plugin

### ISSUE THREAD

**Issue by unconservo** [WWBN/AVideo#4316]
Hi hi. I bought the plugin and installed successful but im not getting any notfication on sections i check. I do receive email if I send messsge to subscribers

Also i get a blank screen with the folliwing (attached) when I click on test on notification plug in.

![20210107_212658](https://user-images.githubusercontent.com/76112286/103934873-69c81d80-512e-11eb-932d-06a2ddab7f59.jpg)

**Comment by unconservo** [comment]
PHP Fatal error:  Uncaught OneSignal\Exception\OneSignalException: Client error: `POST https://onesignal.com/api/v1/notifications` resulted in a `400 Bad Request` response:

**Comment by DanielnetoDotCom** [comment]
share more from your logs, should be something else.

**Comment by unconservo** [comment]
Which logs?

**Comment by DanielnetoDotCom** [comment]
https://github.com/WWBN/AVideo/wiki/How-to-find-errors-on-AVideo-Platform

**Comment by akhilleusuggo** [comment]
Same issue on demo site , but on demo is because probably because is not configured ( or the files does not exist ) .
Tested on my site , and works ;
![image](https://user-images.githubusercontent.com/52116577/104120709-9c962f80-5341-11eb-90cc-533a0244fb24.png)

Must be something that you have misconfigured . https://github.com/WWBN/AVideo/wiki/Notifications-Plugin

**Comment by unconservo** [comment]
Thanx. Ill reconfigure tomorrow and see :)
