### ISSUE TITLE
Network Encoder Configuration

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo#4457]
I have installed Network Encoder on one of my server bu I am not sure what it does really and how I use it. Basically I want to set a separate
![Screen Shot 5781-05-15 at 1 22 46](https://user-images.githubusercontent.com/58882903/106067581-aec8e980-6107-11eb-8247-be15e398f267.jpg)
 Encoder server and if possible maybe several encoders so to reduce the load on my server. Currently each server does its own encoding but I would like to move all encoding to a separate server. My questions are:

1. Do I need to install the whole site just to setup an encoder?
2. how do I control which server encodes where?
3. How do I use the Network Encoder interface and what does it mean when it says off line?

When I try to encode I do not see the queue updated on the Network encoder. The encoding still happens if I change my encoder URL to point to the network encoder domain.
Would be nice to use encoders the same way we use storage locations.

Also While trying to install getRecordedFile.php has the following error:

![Screen Shot 5781-05-15 at 1 18 32](https://user-images.githubusercontent.com/58882903/106068317-1cc1e080-6109-11eb-9b77-1b565fc58f1a.jpg)

**Comment by akhilleusuggo** [comment]
Regarding your downloading issue , I just updated the wiki with the new download url giving you error 404 .
Try this one , https://raw.githubusercontent.com/WWBN/AVideo/master/plugin/Live/standAloneFiles/getRecordedFile.php

Updated on ; https://github.com/WWBN/AVideo/wiki/Live-Plugin#getremotefile-getrecordedfilephp

About network encoder , is a site that basically will automatically pick what encoder to use based on ;
Latency ( ping to the server )
Queue ( number of queued video to encoder , the lower will have the highest priority )

What I on your screenshot is ;

1- Your server does not answer to ping ( that's why is stating that is offline , can't get a respose back ) . Make sure that your server is up and running , and that has ping packages installed .
Solution ; `sudo apt install iputils-ping`

2- On network encoder you shouldn't really see those videos displayed , maybe is due to your advanced configuration option plugin . Try disabling the option ''Open encoder on iFrame" , clear the cache afterwards .

3- Each encoder need to have his own URL , yes . Not necessary a new domain-name or subdomain , Could be a subdirectory .
Examples : 

encoder1.example.com , encoder2.example.com OR
www.example.com/encoder1 , www.example.com/encoder2

You will need to install the encoder project on the AVideo project directory ( or move it and rename it )

**Comment by guymass** [comment]
Perfect!! its working now, as you said I needed to use the URL with /Encoder and not the URL of the site.

![Screen Shot 5781-05-15 at 13 39 56](https://user-images.githubusercontent.com/58882903/106133802-68f33c00-616e-11eb-92d8-cf1d622bb8a1.jpg)

**Comment by guymass** [comment]
So last question just to clarify, if I want to add another Encoder server would it be enough to simply install Just the Encoder without the whole site? Setting a VirtualHost on apache just for it and attaching a sub-domain to it. So it only serves as an Encoder, no site, no video storage, just 100% resources are given to the encoder.

**Comment by akhilleusuggo** [comment]
you can do that , just everytime you wanna add a new encoder , you will need the install folder ( on network encode )

**Comment by guymass** [comment]
Much thanks, this will go in much testing as I am going to add few. I will close this issue.
