### ISSUE TITLE
help

### ISSUE THREAD

**Issue by houssem2055** [WWBN/AVideo#4669]
Where is the problem
![20210311_171317](https://user-images.githubusercontent.com/65106630/110818430-89de9f00-828d-11eb-9991-183ed11ea296.jpg)

**Comment by DanielnetoDotCom** [comment]
check the PC and inspect your HTML source code.

**Comment by houssem2055** [comment]
I am a story of all the blades and all are true the problem of the site

**Comment by houssem2055** [comment]
I am a story of all the blades and all are true the problem of the site

**Comment by peterflitz** [comment]
The problem is real.

I have the problem its approx update to 10.03 or in this time.

It's way too complicated to explain in a foreign language ...

But I try:
The problem is only visible if the first page is set in default.
3 members on the site.
Admin also creates a category for each member.

User1 = Category / Members / User1
(www.domain.com/cat/User1)

User2 = Category / Members / User2
(www.domain.com/cat/User2)

User3 = Category / Members / User3
(www.domain.com/cat/User3)

Now it is like this, in the FirstPage-default the latest video is displayed at the top.
I klick to the Category from User1 (www.domain.com/cat/User1)
If the latest video is from User1, it will be displayed correctly in the / Members / User1 category.

In:
User2 = Category / Members / User2
User3 = Category / Members / User3
The Problem you see in the Picture.

If I switch the view of the first page to gallery, the error is gone or just a small error in the top left.

This error, it seems to be a permission issue.

![bug-in-default-first-page](https://user-images.githubusercontent.com/76056428/110868223-7d2b6c80-82c8-11eb-986f-648b432fe1a2.png)

**Comment by houssem2055** [comment]
thanks
