### ISSUE TITLE
Subscription plugin

### ISSUE THREAD

**Issue by fxp66** [WWBN/AVideo#4694]
When using the subscription plugin only the Id of the plan is showed in left menubar. Is it possible to display the title instead?
Thx for quick response

**Comment by DanielnetoDotCom** [comment]
Where are you talking about?

**Comment by fxp66** [comment]
Excuse me for being not clear. I've made a paypal plan called 'test' and expected to see  the title 'test' in the left menu.
![screen-1](https://user-images.githubusercontent.com/40458047/111151754-2bb50300-8590-11eb-89d6-bdedbbdb59ed.jpg)
Did I miss a configuration?

**Comment by DanielnetoDotCom** [comment]
That is what I see on my side

![image](https://user-images.githubusercontent.com/18009293/111155901-d4a13500-8573-11eb-877b-2f8d579cd9a9.png)

![image](https://user-images.githubusercontent.com/18009293/111155958-e97dc880-8573-11eb-8b7b-35f0ad65c28a.png)


If you see a checkbox instead of an input text, means your plugin configuration is corrupted, so you need to delete all configuration and let the script recreate it.

![image](https://user-images.githubusercontent.com/18009293/111156202-3a8dbc80-8574-11eb-9ae8-5db1099210e2.png)

**Comment by fxp66** [comment]
Thx Daniel, this fixed it for me.
