### ISSUE TITLE
How to make Last live broadcast loop

### ISSUE THREAD

**Issue by milehighkaraoke** [WWBN/AVideo#4792]
Is there a way to make my last live broadcast loop in my embedded player until I go live again?

**Comment by akhilleusuggo** [comment]
No.

**Comment by milehighkaraoke** [comment]
No, is not a solution. If there is not currently a way to do this we are looking for a solution to make it happen.

**Comment by akhilleusuggo** [comment]
Sorry for sounding so direct , just answered your question . Is there anyway ? _NO_ is the answer

How to make it if there's none ? Well you need to do it manually , but is not automatic . I do it for myself with ffmpeg ( from the server itself ) .

Create a script that runs from the tmp folder ( where you saved your stream ) . When the stream is over launch the script , make sure you loop it with a playlist , or create a playlist long enough to never end .

Example ;

`playlist.txt` should look like this ;

file 'my_stream.flv'
file 'my_stream.flv'
file 'my_stream.flv'
file 'my_stream.flv'

**Comment by akhilleusuggo** [comment]
Sorry for sounding so direct , just answered your question . Is there anyway ? _NO_ is the answer

How to make it if there's none ? Well you need to do it manually , but is not automatic . I do it for myself with ffmpeg ( from the server itself ) .

Create a script that runs from the tmp folder ( where you saved your stream ) . When the stream is over launch the script , make sure you loop it with a playlist , or create a playlist long enough to never end .

Example ;

`playlist.txt` should look like this ;

```
file 'my_stream.flv'
file 'my_stream.flv'
file 'my_stream.flv'
file 'my_stream.flv'
.....
```

`ffmpeg -f concat -i playlist.txt -c copy -f mp4 output.mp4`
`ffmpeg -i output.mp4 -c copy -f flv rtmp://......`


There's another better way explained here , but I don't use it .https://stackoverflow.com/questions/11647868/using-ffmpeg-to-stream-continuously-videos-files-to-a-rtmp-server

Actually is better for your use-case , the problem is that if you enable the save live-stream you will also save the looping streamed videos . And if you don't have it enabled , you won't be able to create the loop .

**Comment by milehighkaraoke** [comment]
Thank you for this solution
