### ISSUE TITLE
Search results doesnt filter videos without rights

### ISSUE THREAD

**Issue by morbificagent** [WWBN/AVideo#4930]
Hey there,

As i have hidden the private videos from the gallery and bought the LiveSearch plugin today i saw that my hidden videos are part of the search results :-(

Could you make this possible to select like in the gallery-settings:

![Screenshot_20210413-233217_Chrome.jpg](https://user-images.githubusercontent.com/50199132/114624155-8be2b600-9cb0-11eb-9151-31a68c77cc7a.jpg)

Like this i cant use it if all the hidden files are seen in the search results.

**Comment by morbificagent** [comment]
Only for clarify: its about the videos which are only accessable for a GROUP.
These i have hidden from the gallery but are part of the search results.

**Comment by DanielnetoDotCom** [comment]
Are you using the live search?

I guess this is a feature I will need to implement on the plugin. 

currently show private videos on search is good because you may be using a subscription or PPV plugin, and trying to play this movie will send to the payment screen
but I understand some times you may not want that, so I think it should be a separate option on the plugin itself

**Comment by morbificagent** [comment]
> Are you using the live search?

yes

**Comment by DanielnetoDotCom** [comment]
Livesearch V1.4 will have the hidePrivateVideos option

it will be released today

**Comment by morbificagent** [comment]
You are the best :-)
