### ISSUE TITLE
I CANNOT ACCESS MY WEBSITE

### ISSUE THREAD

**Issue by naluv4u2** [WWBN/AVideo#5090]
Why am I not able access my website?  My domain name is http://www.biggsexxxy.com

My email address is:  phat4lifetv@gmail.com

**Comment by akhilleusuggo** [comment]
I don't know, I doesn't seem to work , but I can only guess if you were banned is because of "porn content" ? 

https://github.com/WWBN/AVideo#this-software-must-be-used-for-good-never-evil-it-is-expressly-forbidden-to-use-avideo-platform-open-source-to-build-porn-sites-violence-racism-terrorism-or-anything-else-that-affects-human-integrity-or-denigrates-the-image-of-anyone

> This Software must be used for Good, never Evil. It is expressly forbidden to use AVideo Platform Open-Source to build porn sites, violence, racism, terrorism, or anything else that affects human integrity or denigrates the image of anyone.

**Comment by naluv4u2** [comment]
IT WAS NOT A PORN SITE BUT IS GUESS THE NAME OF MY DOMAIN MAKES IT A PROBLEM.  HOW CAN I OBTAIN A BACKUP COPY OF THE CONTENT?

________________________________

**Comment by akhilleusuggo** [comment]
I don't know , did you get the server from @DanielnetoDotCom ?

**Comment by naluv4u2** [comment]
YES I GOT IT. ITS WORKING NOW
Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
