### ISSUE TITLE
Bitchute import 

### ISSUE THREAD

**Issue by fakeologist** [WWBN/AVideo#5108]
Bitchute used to import without issue.
Now it gives this error.
![Screenshot_20210509-082539_Brave.jpg](https://user-images.githubusercontent.com/66537018/117572297-498a7a00-b0a0-11eb-9eed-61f2ce89748b.jpg)
Can this be fixed?

**Comment by RememberForgottenHits** [comment]
You need to upgrade your youtube-dl version. 

$ sudo -H pip3 install --upgrade youtube-dl 
See here is a guide on how to install and upgrade https://www.linuxbabe.com/ubuntu/install-avideo-youphptube-ubuntu-20-04-server.

Just two hours ago, I imported 15+ videos from the Bitchute website.

I'm using Avideo version 11.0 (try upgrading on your own if version 11.0 isn't already in use

**Comment by fakeologist** [comment]
Thanks appreciate it.

**Comment by RememberForgottenHits** [comment]
What version do you have of avideo? 11.0 or older?
What happens when you click the OK button in this dialog?
![NNNNNNNNNNN](https://user-images.githubusercontent.com/34457020/117575976-ac096780-b0ec-11eb-9bd2-fd2cd98ff838.png)
This is not a bug!!!  You are using an old version of youtube-dl

Uploaded to my site today
![bitchute](https://user-images.githubusercontent.com/34457020/117576018-de1ac980-b0ec-11eb-8810-3a1610c4c74c.png)

**Comment by fakeologist** [comment]
Using 11 and upgraded as advised. Daniel can check and see what is wrong @DanielnetoDotCom

**Comment by RememberForgottenHits** [comment]
For me, this link is working properly
![WORKING-OK](https://user-images.githubusercontent.com/34457020/117682783-19d09480-b1bc-11eb-89a8-5b5c14e434c7.png)
![working-OK1](https://user-images.githubusercontent.com/34457020/117683294-995e6380-b1bc-11eb-8195-6db03c36b318.png)

You can see it https://mustream.info/video/127/update-the-experimental-injection-results-must-watch?channelName=IFFILIVE

**Comment by fakeologist** [comment]
It's the characters after the final "/" including a space that caused the failure.
I never had to remove them before.
Thanks.
