### ISSUE TITLE
[v11.0] Server crashed during encode. Reason unknown. 

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#5149]
**Describe the bug**
I queued a lot of videos into the encoder. While I was editing metadata, server died, unresponsive to ping.

Force rebooted server, came up in a bad state, went into recovery mode, diagnostics passed, rebooted.

AVideo recovered, encoder queue started, first file in the queue was the one that got interrupted.

Nothing of interest in the encoder or site log that I could see.

I'm vexed. I don't really know which log files to check to know why two reboots were required.

**Comment by akhilleusuggo** [comment]
It happens when server raid can't handle that much IOps.
Your server config is certainly the issue, max_connection database, apache2 max_request , hardware etc. In my experience, raid drive causes for me this issue, also VM with low IO, bad hard-drives or lack of RAM. 

It has nothing to do with the script, and it's not a bug as labeled. As you mentioned it by yourself, after reboot everything worked well.
