### ISSUE TITLE
How should the administrator use locale translation

### ISSUE THREAD

**Issue by chenjian9885** [WWBN/AVideo#5376]
Hello
How can the administrator use locale translation
![image](https://user-images.githubusercontent.com/47063171/124111052-72752d00-da9b-11eb-8d8a-c6d70c435b63.png)

**Comment by DanielnetoDotCom** [comment]
This is just a helper, I really recommend you to directly edit the locale file and send it as a pull request, so your changes will not be overwritten on updates

**Comment by chenjian9885** [comment]
Yes, but after all, each person’s category and some tags or descriptions will be different
I still hope to have this auxiliary function

**Comment by chenjian9885** [comment]
Yes, but after all, each person’s category and some tags or descriptions will be different
I still hope to have this auxiliary function

**Comment by DanielnetoDotCom** [comment]
We do not have this kind of support

**Comment by chenjian9885** [comment]
I have more than 200 words that need to be translated into simplified Chinese, traditional Chinese, Korean, and Japanese. How can I quickly replace the translated words with this $t['Title and description'] = "标题和描述";
![image](https://user-images.githubusercontent.com/47063171/124159212-76ba3e00-dacd-11eb-99f5-3777ee57cad2.png)

**Comment by Maikuolan** [comment]
> I really recommend you to directly edit the locale file and send it as a pull request, so your changes will not be overwritten on updates

I agree with this.

But alternatively, if the user wants customised localisations (i.e., not something for contributing back towards the project or community overall), in order to avoid those customised localisations being overwritten, the user could just copy/paste some existing localisation file, rename it something else (i.e., a new name, different than any of the existing localisation files), and then work from that copy. I imagine, in theory, those files should then be safe from being overwritten, seeing as they wouldn't exist at the upstream repository (but, I would recommend keeping backup copies anyway, just in case).

Could maybe rename it just using a fake language code, or, for something which feels more standardised, by using the "x" prefix convention, which indicates that the code used isn't a formal/standard code (e.g., like `x_zh_CJ` to indicate {x} "non-standard/custom" {zh} "Chinese translation" {CJ} "written/used by CJ", or `x_ja_CJ` to indicate {x} "non-standard/custom" {ja} "Japanese translation" {CJ} "written/used by CJ", etc and etc). Anyway, this is merely an idea. Use it or disregard it at your own discretion. :-)

> How can I quickly replace

For performing quick search/replace operations across multiple files/translations, using a text editor to manually edit the files would probably be easiest, I think.

**Comment by chenjian9885** [comment]
Okay, I’ve seen you have tutorial videos in this area before. Since there is none, I’ll use text editing.

**Comment by chenjian9885** [comment]
Request to update translation
[zh1.php.zip](https://github.com/WWBN/AVideo/files/6767398/zh1.php.zip)
[zh_Hant_TW1.php.zip](https://github.com/WWBN/AVideo/files/6767406/zh_Hant_TW1.php.zip)

**Comment by DanielnetoDotCom** [comment]
Here is the update

**Comment by chenjian9885** [comment]
Hello
very sorry! I have pointed out the translation that needs to be replaced in my translation file, and he needs to replace the incorrect translation. I neglected to indicate it in English and let you overwrite the error directly. Now I have updated the entire translation file.

Just overwrite

[zh.php_JWynpd.tar.gz](https://github.com/WWBN/AVideo/files/6772327/zh.php_JWynpd.tar.gz)
[zh_Hant_TW.php_Skyykx.tar.gz](https://github.com/WWBN/AVideo/files/6772328/zh_Hant_TW.php_Skyykx.tar.gz)

**Comment by DanielnetoDotCom** [comment]
Instead of sending files please try this

https://docs.github.com/en/github/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request
