### ISSUE TITLE
avideo translation failed

### ISSUE THREAD

**Issue by mostafaaalii** [WWBN/AVideo#5416]
i am translated Avideo to persian but it can not recognize its flag icon and renamed it as null. my translated file name in the locale folder is ir.php
![Screenshot (6)](https://user-images.githubusercontent.com/72271443/125196685-9bba5980-e20f-11eb-892a-31215eedc781.png)

**Comment by Maikuolan** [comment]
Instead of `ir` ([ISO 3166-1](https://en.wikipedia.org/wiki/ISO_3166-1) code for Iran), try using either `fa` ([ISO 639-2](https://en.wikipedia.org/wiki/List_of_ISO_639-2_codes) code for Farsi/Persian/فارسی), or `fa_IR` (for Iranian Farsi). Given that the languages are represented by *country* flags, it is reasonable to assume that ISO 3166-1 codes would be required. However, based on the code used for handling languages and language representation (*see: [bcp47](https://github.com/WWBN/AVideo/blob/master/objects/bcp47.php)*), I believe we should be naming files according either to ISO 639-2 or to [IANA's registry](https://www.iana.org/assignments/language-subtag-registry/language-subtag-registry) (e.g., `en`, `en_US`, `fa`, `fa_IR`, etc).

PS.. If you've fully translated everything at your end, and manage to get it working, you should consider creating a pull request here, so that the new translations can be included at the repository here, for everyone to benefit. ;-)

**Comment by mostafaaalii** [comment]
> Instead of `ir` ([ISO 3166-1](https://en.wikipedia.org/wiki/ISO_3166-1) code for Iran), try using either `fa` ([ISO 639-2](https://en.wikipedia.org/wiki/List_of_ISO_639-2_codes) code for Farsi/Persian/فارسی), or `fa_IR` (for Iranian Farsi). Given that the languages are represented by _country_ flags, it is reasonable to assume that ISO 3166-1 codes would be required. However, based on the code used for handling languages and language representation (_see: [bcp47](https://github.com/WWBN/AVideo/blob/master/objects/bcp47.php)_), I believe we should be naming files according either to ISO 639-2 or to [IANA's registry](https://www.iana.org/assignments/language-subtag-registry/language-subtag-registry) (e.g., `en`, `en_US`, `fa`, `fa_IR`, etc).
> 
> PS.. If you've fully translated everything at your end, and manage to get it working, you should consider creating a pull request here, so that the new translations can be included at the repository here, for everyone to benefit. ;-)

Thanks sir. I will share my translate file with everyone. Do you have an education about changing site direction to rtl in Persian language?
