### ISSUE TITLE
Backup always writes to the AVideo plugins folder. Needs to be configurable. Causes "issues"… lol

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#5714]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when running the Backup plugin, and having it fill my boot volume to capacity, and I can't log back into the server again.

**Describe the solution you'd like**
In my case the Linux/Avideo volume is very small, and my encoder/streamer folders are located on another volume.

Trying to backup, it is trying to compress a large multi TB RAID onto a tiny SSD, fills the SSD, now you can't login again.

Specifically it always is writing to /var/www/html/AVIdeo/plugins/Backup/...

**Describe alternatives you've considered**
Need to be able to configure a path here. This is why my backup of 2GB was failing when I had 6GB free. It was not using the 6GB, it was filling my 480GB SSD.

**Comment by DanielnetoDotCom** [comment]
I understand you,

the problem is that to be able to download the backup file the directory must be in a place where apache can access it. so it MUST be in a valid web directory

buy you can move the Backup plugin to another mounted drive and then create a symbolic link to replace the Backup folder inside the plugin folder

For example 
```
sudo mv /home/daniel/Dropbox/htdocs/AVideo/plugins/Backup /home/anotherDrive/Backup
sudo ln -s /home/anotherDrive/Backup /home/daniel/Dropbox/htdocs/AVideo/plugins/Backup 

```
I have never tested it, but I suspect it may work

**Comment by walt93** [comment]
That totally makes sense. I was thinking about other users that may run into the same problem. I'm sticking with rsync because .. incremental diffs! Ok you can close this, thanks.
