### ISSUE TITLE
How to change languages

### ISSUE THREAD

**Issue by toplive24** [WWBN/AVideo#5911]
Hello everyone, 
I am new in this world.
I need to understand how to connect to change part of the languages and where to intervene.

Thanks in advance

**Comment by DanielnetoDotCom** [comment]
Hi

thanks for opening this issue.
do you mean you want to add a different translation?

or a different language file?

**Comment by toplive24** [comment]
I translate the italian language but when i try to upload with filezilla tell me that i can not.
look photo

thank

![filezilla](https://user-images.githubusercontent.com/93554732/139960063-b9c7fa64-cc10-4388-9cb6-05253cd28330.png)



> 
> 
> Hi
> 
> thanks for opening this issue. do you mean you want to add a different translation?
> 
> or a different language file?

**Comment by DanielnetoDotCom** [comment]
Hi

I see now what you mean.
First I need to tell you a few things.

## 1. Pull request 
if you need to add or change something on the translation avoid direct changing the file. always prefer to make a pull request https://docs.github.com/en/github/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request

If you do not do that you will lose all your translations on the next update.

If you send a pull request the modifications will be permanent.

In case you cannot make a pull request attach the file here and I will update it for you.

## 2. The permission

You cannot overwrite the file because you need to change the permission on your server by command line

usually the command is `chmod -R 777 /var/www/html/AVideo/locale`

**Comment by DanielnetoDotCom** [comment]
This is old but maybe useful https://github.com/WWBN/AVideo/wiki/How-to-translate-AVideo-Platform-to-your-idiom-using-google-translate

**Comment by toplive24** [comment]
> This is old but maybe useful https://github.com/WWBN/AVideo/wiki/How-to-translate-AVideo-Platform-to-your-idiom-using-google-translate

Hello Neto

With pc and phone don't change nothing and if I select the language don't appear the words at left and I don't have in the menu *create a new translations*. 
![Screenshot_20211103_055414_com android chrome](https://user-images.githubusercontent.com/93554732/140012423-a38390cb-f001-4939-8ca9-387f4cb7f7b7.jpg)
![Screenshot_20211103_055435_com android chrome](https://user-images.githubusercontent.com/93554732/140012426-9c98aa57-aae3-4a63-8c48-825f99aee79b.jpg)
![Screenshot_20211103_055447_com android chrome](https://user-images.githubusercontent.com/93554732/140012428-992625ee-8420-4e20-a6dd-a66fa33e861a.jpg)
![Screenshot_20211103_055033_com android chrome](https://user-images.githubusercontent.com/93554732/140012429-d6492639-df27-4f41-87fc-e40914421c93.jpg)

The folder that you say local i can not change permission it's fix at 755.

For fix this?

**Comment by DanielnetoDotCom** [comment]
1. if you want to use the locale tool I recommend you to use a PC NOT a mobile
2. to use putty, if you have never used it before, I recommend you to search on google how to use it or hire someone that knows how to deal with it.

for now, I will change the permission for you. but you may need to learn how to use SSH

**Comment by toplive24** [comment]
I try but dont come language at left

![immagine](https://user-images.githubusercontent.com/93554732/140183900-557cc5d0-f00c-47af-8fbf-0ae015f5b402.png)

**Comment by DanielnetoDotCom** [comment]
I see. sorry but this feature may not work, it is an old feature and it may need to be revisited to check if works or not.. 

currently, the best option is to manually edit the translation file.

**Comment by toplive24** [comment]
Ok I close this but if you can solve thus its more good
