### ISSUE TITLE
Language 

### ISSUE THREAD

**Issue by toplive24** [WWBN/AVideo#5917]
Hello all 
I need know where I change some word's in the many language why in the file .php (es. it.php) missing some line and after I have a different language together. 

Thank for the answer 
![Screenshot_20211104_094259](https://user-images.githubusercontent.com/93554732/140284258-0e307283-5d95-43e2-adf6-0dde3007929f.jpg)

**Comment by Maikuolan** [comment]
I created a PR just now, which fixes this particular missing language entry.

Also, for changing the Italian language strings, you want `locale/it.php`. :-)

**Comment by toplive24** [comment]
This i know, but inside the Duke missing some linees

**Comment by Maikuolan** [comment]
I compared the US English (`locale/en_US.php`) against the Italian (`locale/it.php`) files just now, to see which strings existed in one but not the other (using WinMerge), but couldn't find any strings in one missing from the other, so I think, if there are strings missing, those strings are currently missing from both (although, I did find some typos in the names of some of those strings, but those typos aren't related to the problem here, so we can deal with those later).

Are you able to list here the exact things which aren't currently being translated? I think, what we'll need to do, is go over the code, to locate exactly which string names the code is looking for for those non-translated things, and then add some locale strings for those things to both locale files (plus whichever other files they may be missing from).

**Comment by toplive24** [comment]
Ok after I look.
Can to  be the problem inside the Plugins that take the words?
It's only a my think.

Thank

**Comment by DanielnetoDotCom** [comment]
Hi

maybe missing some words in some plugins. or maybe the word is not even translated.

if you want to get the update @Maikuolan sent, you may need to update your AVideo first. the updates are not automatic.
check this to update https://github.com/WWBN/AVideo/wiki/How-to-Update-your-AVideo-Platform

For example, "My Subscribers" word is here https://github.com/WWBN/AVideo/blob/65c7aad6cbc9653054c812a333a87539bb2e260b/view/include/navbar.php#L708

and the Italian translation file is here https://github.com/WWBN/AVideo/blob/65c7aad6cbc9653054c812a333a87539bb2e260b/locale/it.php#L224

but you need to follow the update above to get it

if you find a word that is not translated you can screenshot it here and we may be able to fix

**Comment by Maikuolan** [comment]
I've written a small script at my local machine to automatically scan through the entire codebase, in an attempt to detect any translation strings missing from the locale files, to normalise, and to add any missing strings to their respective locale files. I'm running it now, double-checking over the results, and if all goes well, I'll send a new PR shortly, so that we'll hopefully be able to see what's missing, and then translate as per needed.

**Comment by toplive24** [comment]
Maikuolan
Great

Thank

**Comment by Maikuolan** [comment]
Done (#5926).

**Comment by toplive24** [comment]
Maikuolan you have news?
I see the file language it.php
I waiting?

thank

**Comment by Maikuolan** [comment]
If you git pull to the latest version, you should see the latest version of the file appear there. In the latest version of the file, you'll notice, the strings have now been separated into three sections, by two comments in the file, *"previously missing from file"* and *"extras ..."*.

Under the *"previously missing from file"* comment, there should be some new strings, which weren't included in the file previously. For the non-translated strings (referring to the missing lines mentioned, when this issue was first created here), do you see any of them in the updated file?

**Comment by toplive24** [comment]
Hello

What i to do?
I use the line correct that you put inside the file it.php?

thank

**Comment by DanielnetoDotCom** [comment]
Hi

@toplive24 if you want to add some translations you will need to edit the language file.
Once you change it you may want to make it permanent. so I strongly recommend you to make a fork of this project, update your fork and make a pull request.

https://www.jetbrains.com/help/pycharm/contribute-to-projects.html

https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-pull-requests

**Comment by toplive24** [comment]
Hello Neto

I translate all the lines that Mazalevskis found and i translate also the
last 2 lines.
Inside dont have error.
I add the file it.php to you for i dont to do wrong for upload the file and
if you can insert.

Thank



Il lun 8 nov 2021, 14:03 Daniel Neto ***@***.***> ha scritto:

**Comment by DanielnetoDotCom** [comment]
Hi

please attach the translated file here and I will add it for you

**Comment by toplive24** [comment]
Hello Neto
this its the file it.php translate of all script

tha
[it.zip](https://github.com/WWBN/AVideo/files/7534500/it.zip)
nk

**Comment by DanielnetoDotCom** [comment]
Done, lang file updated

now you need to make a git pull on your server 

https://github.com/WWBN/AVideo/wiki/How-to-Update-your-AVideo-Platform

**Comment by toplive24** [comment]
Neto you remember tgst I can not enter on the server?
And I can kor to do this :

1 - Git Pull (Recommended)

go to your AVideo dir and type git pull

cd /var/www/html/AVideo/ && sudo git pull

you can update the encoder the same way you do for the Streamer

cd /var/www/html/AVideo/Encoder && sudo git pull

Il lun 15 nov 2021, 14:29 Daniel Neto ***@***.***> ha scritto:

**Comment by DanielnetoDotCom** [comment]
When I installed your server I sent you an email with SSH credentials.

I will update you this time, but you may need to be able to figure out how to use SSH

**Comment by toplive24** [comment]
Ok thank for now, I go to learn

Thank

Il lun 15 nov 2021, 14:42 Daniel Neto ***@***.***> ha scritto:

**Comment by toplive24** [comment]
I see the new language but missing again some translation

**Comment by DanielnetoDotCom** [comment]
I just update with the file you sent to me

if you want to review just send me a new file.

**Comment by toplive24** [comment]
All ok now
