### ISSUE TITLE
Ver 9.7 Git pull did't work crash the site 

### ISSUE THREAD

**Issue by thushy07** [WWBN/AVideo#5923]
site was at 9.7 
try to upgrate the site to newer version, after the pull Site crashed
>>>

array(4) { ["type"]=> int(1) ["message"]=> string(121) "Cannot redeclare Aws\manifest() (previously declared in /var/www/YouPHPTube/vendor/aws/aws-sdk-php/src/functions.php:385)" ["file"]=> string(55) "/var/www/YouPHPTube/plugin/AWS_S3/aws/Aws/functions.php" ["line"]=> int(322) } array(4) { ["type"]=> int(1) ["message"]=> string(121) "Cannot redeclare Aws\manifest() (previously declared in /var/www/YouPHPTube/vendor/aws/aws-sdk-php/src/functions.php:385)" ["file"]=> string(55) "/var/www/YouPHPTube/plugin/AWS_S3/aws/Aws/functions.php" ["line"]=> int(322) }
  
  
 attached image from terminal any help would be appreciated
 Thank you 
![image0](https://user-images.githubusercontent.com/44659184/140445903-044d8afe-8a06-47de-9b33-f9f9d5a7997b.jpeg)

**Comment by DanielnetoDotCom** [comment]
Hi

for an update like that, you will need to follow the following steps.

## force to update and overwrite all your files

instead of git pull run this `sudo git fetch --all && sudo git reset --hard origin/master`


## Before accessing the site

on update 11 requires you this 

https://github.com/WWBN/AVideo/issues/5075#issuecomment-833764155

## update all paid plugins

If some plugin crashes just delete the folder. download the new plugins and update them.

**Comment by thushy07** [comment]
Thank you, the result was same, this time i remove the AWS_S3 plugin and update. it' worked, then in install the new AWS_S3 plugin again, All good now

Thank you

**Comment by DanielnetoDotCom** [comment]
So you are all set now?
is it working?
