### ISSUE TITLE
My SSL certificate is suddenly missing from the website-www.maritimeplatform.com-Please help to restrore

### ISSUE THREAD

**Issue by vraghavans** [WWBN/AVideo#6022]
**Describe the question**
Self had installed SSL certificate as per the instructions during deployement of the website,however now the website is not SSL,how do we reinstall the same please.

**Screenshots**
Provide some screenshots to help us understand and explain your problem.

**Comment by DanielnetoDotCom** [comment]
try this ...

`certbot renew`

if fails google how to reinstall lets encrypt certificate

**Comment by vraghavans** [comment]
Cert is due for renewal, auto-renewing...
Plugins selected: Authenticator apache, Installer apache
Renewing an existing certificate
Performing the following challenges:
http-01 challenge for seafarerstube.com
Waiting for verification...
Cleaning up challenges
Attempting to renew cert (seafarerstube.com-0001) from /etc/letsencrypt/renewal/                                                                             seafarerstube.com-0001.conf produced an unexpected error: Failed authorization p                                                                             rocedure. seafarerstube.com (http-01): urn:ietf:params:acme:error:unauthorized :                                                                             : The client lacks sufficient authorization :: Invalid response from http://seaf                                                                             arerstube.com/.well-known/acme-challenge/fFVMLS7AxjRku5YtMgxIgmWIeylAvRhml1QitfW                                                                             P-cE [15.197.142.173]: 404. Skipping.

This is the error showing,the domain is pointing to my old domain "Seafarerstube.com"

**Comment by DanielnetoDotCom** [comment]
Looks to me your domain or server is misconfigured not the certificate.

![image](https://user-images.githubusercontent.com/18009293/143510731-a28d6cbd-6301-46e2-8bfb-a804833b847c.png)

![image](https://user-images.githubusercontent.com/18009293/143510757-bc3696d3-db03-41bd-b6e4-08c3ec5d21b6.png)

careful on trying to renew because letsencrypt has a week limit or requests.

First, try to contact your domain provider company, and try to roll back whatever change you made on your server.
but you may need to hire someone to help you with the domain as long as seems to me you do not know how to deal with it.

for sure to fix it will require server access/intervention. but I do not know what is wrong.


![image](https://user-images.githubusercontent.com/18009293/143510687-56c35f0f-4199-42e7-86f4-baaad107145d.png)

**Comment by vraghavans** [comment]
<img width="845" alt="image" src="https://user-images.githubusercontent.com/65802024/143523048-2f3c7b55-893d-42e1-8422-dab38505cafe.png">
Website is there only the SSL is pointing to my previous domain name of the same website.Have checked with the domain provider and there seems to be no issues there.

Kindly advise how do i change the cert to point to the correct domain please

**Comment by DanielnetoDotCom** [comment]
Try to google and find how to install a letsencrypt SSL

I cannot teach you how to install SSL, that is not the purpose of this project.

**Comment by akhilleusuggo** [comment]
your should renew the current active site, not the old site.
also this issue is pointing that your apache config is incorrect. Maybe you're looping the requests.

**Comment by gbrn** [comment]
> This server has failed to prove that it is www.maritimeplatform.com. His security certificate expired 18 days ago. This could be caused by a misconfiguration or by an attacker who intercepted your connection.

**Comment by vraghavans** [comment]
it was pretty simple actually
Just ran Sudo certbot
it gave me the option of reinstalling the SSL

Thanks fro your help!
