### ISSUE TITLE
PWA Full Screen Support 

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#6065]
The PWA mobile app doesn't allow widescreen full screen.

When you click full screen it wont turn sideways.

**Comment by DanielnetoDotCom** [comment]
I am not 100% about this. 

what device are you using?

what do you have here?
![image](https://user-images.githubusercontent.com/18009293/145625258-fc2b050c-394a-4c9d-9758-b241852775a9.png)

I can see yours here 
https://www.joshwhotv.com/manifest.json

![image](https://user-images.githubusercontent.com/18009293/145625440-bdc5e503-2268-41d0-9124-d080be07723f.png)


Also, I reviewed the code and I suspect I was missing something, I am sending updates

**Comment by JoshWho** [comment]
I ran the git pull and I see full screen is enabled but it still keeps the screen in vertical when I click full screen.

![Screenshot_20211210-133609](https://user-images.githubusercontent.com/39392449/145631812-51560851-d879-4956-baef-150237ea879d.jpg)

![Screenshot_20211210-133557](https://user-images.githubusercontent.com/39392449/145631914-3c034c89-a5e0-469b-abf1-f374c596e0b8.jpg)

**Comment by DanielnetoDotCom** [comment]
try this update

**Comment by JoshWho** [comment]
nope that didnt do it

**Comment by DanielnetoDotCom** [comment]
I tested on my side and I could rotate on iPhone

**Comment by JoshWho** [comment]
I use android

**Comment by DanielnetoDotCom** [comment]
First delete the pwa app from your android and install again

Make sure your autorotate is enabled

## Auto-rotate screen
When this accessibility setting is on, the screen automatically rotates when you move your device between portrait and landscape.

If you're using TalkBack, you might want to turn off auto-rotate, since rotating the screen can interrupt spoken feedback.

To change your auto-rotate setting, follow these steps:

Open your device's Settings app Settings app.
Tap Accessibility.
Tap Auto-rotate screen.

**Comment by JoshWho** [comment]
Yay it works I had to uninstall like u said. Now it works Thank you.
