### ISSUE TITLE
dumb question im sure but why does the article plugin show like this after posting? 

### ISSUE THREAD

**Issue by Liberty-library** [WWBN/AVideo#6082]
![test art](https://user-images.githubusercontent.com/96153776/146100723-d3ac5dd9-bb51-438b-ba75-003abd5e9aa2.JPG)

**Comment by DanielnetoDotCom** [comment]
Not sure. 

try on [demo ](https://demo.avideo.com/) site to see if you will have the same result.

**Comment by Liberty-library** [comment]
It works there! but why not for me?

**Comment by Liberty-library** [comment]
every quote, even in video titles shows like this. I can give you admin access to look and see what I broke. And yes I'll pay you.

**Comment by DanielnetoDotCom** [comment]
We do not offer partial installations because it is a lot easier to make a clean install than find bugs on preinstalled systems.

If you want to hire me, please purchase some hours [here](https://youphp.tube/marketplace/) and email me your server SSH and admin credentials. I can try to fix but as long as the main installation was not made by me, I cannot guarantee it 100%

**Comment by Liberty-library** [comment]
I fixed it, It was the Customize Advanced plugin. The utf8Encode, utf8Decode enabled. Thanks!
