### ISSUE TITLE
Copyrighted Materials

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo#6130]
We recently receive a law suite against our site where on of the publishing channels have used a copy-righted photo on its video post. Although we have an agreement with our users and we are not a commercial site nor do we use copyrighted materials as far as we can check.

Is there a way to incorporate a way to test for copyrighted materials? How can we prevent such legal actions against us in the future as we cannot check and verify all content.

**Comment by DanielnetoDotCom** [comment]
Hi

this feature would be awesome but I have no idea how to check it

do you have any idea where and how to verify it the media is copyrighted?

**Comment by guymass** [comment]
I currently don't have a solution, we need to figure our agains what are we first checking the content. I think that on AVideo side this could be done even using the video thumbnail plugin that create images and those could be tested I guess. I will consult some friends and see what we can come up with as this is a much needed feature IMO.

**Comment by The-Do-It-Yourself-World** [comment]
This has been a concern for me as well since we have a growing number of users on our site. The solution would be an automatic image search like google has to look for related content. But I think that is too large for us Daniel?

Did they actually proceed with the lawsuit or just send you a warning to remove the material or else?

I figure if our terms and conditions state that we do not allow copyrighted content and that we will remove anything that is copyrighted then we should be safe from lawsuit as long as we immediately comply with the warning. Am I wrong?

**Comment by DanielnetoDotCom** [comment]
I think it is too large, we do not have an image database. maybe if there is any public feature that we can use to consult copyrighted things. (imagea, sound, etc)

**Comment by guymass** [comment]
We checked, even google doesn't have such API they also lack checking and there is no real way I know to defend against someone deliberately uploading such content to put the site at risk. We have been offered a very high amount to settle and we are consulting a lawyer to see the extent of "fair use". As we only serve as a platform the problem in our case is that the domain itself is another site which is to some extent a commercial site while the subdomain is the free AVideo platform we offer with no charge and no ads just news and for educational purposes.

**Comment by The-Do-It-Yourself-World** [comment]
Ouch. That is terrible. I had some YouTube trolls intentionally post brand new full featured movies to cause me harm but I remove them as fast as I see them. Fortunately I have someone who is watching our site day and night for such issues.

If I find anything that can help I will let Daniel know.

**Comment by guymass** [comment]
Much thanks we will also post any solution we may find.

**Comment by The-Do-It-Yourself-World** [comment]
I found a lot of online services but nothing you can download yet.

**Comment by Maikuolan** [comment]
Due to how copyright laws work in many countries, I don't think it would be truly technically possible to implement a purely automated solution (e.g., API lookup) with any meaningful reliability. In order for an API lookup to work, there needs to be a trustworthy and reliable database behind that API, and in order for a database to be considered trustworthy and reliable, trustworthy and reliable data needs to be contributed to that database (with untrustworthy or unreliable data being rejected/filtered away from that database). If the data you need doesn't exist in that database, that database won't be reliable.

Different countries with different laws, most countries don't have centralised offices/organisations/etc responsible for managing copyrights, and material is often considered automatically copyrighted to the creators of that content the moment that content is created (assuming no existing contracts or work agreements to the contrary), with enforcement being merely a matter of being capable of proving themselves to be the creators of that content (work being dated, physical copies sealed in a signed envelope, witness by a "justice of the peace" or equivalent legal entity, etc).

What this means is that it's possible for material to be copyrighted without that material being listed in any database anywhere, which means that relying entirely on an API lookup doesn't eliminate the risk of being sued.

I think, the best solution to this problem won't strictly be a technical solution. Probably, some kind of legal solution would be necessary. Perhaps implementing strong AUPs (Acceptable Use Policies), ToS (Terms of Service), legal and copyright disclaimers, etc at the platforms in question, in addition to strong moderation controls, tight restrictions to the kinds of content which newly registered, unverified users are able to contribute could help.

In part, YouTube generally doesn't require content to be vetted prior to being uploaded, is able to utilise various in-house algorithms and databases to determine whether material is "copyrighted" (sometimes correctly, often incorrectly), and is often able to get away with acting on copyright violations only after they've been reported, because they're a wealthy corporation backed by Google and can afford teams of specialist lawyers, which makes it difficult for most law firms to bully them or to make unreasonable demands.

It's an unfortunate reality that, if you're not rich, it's easier to be bullied, and easier for those with money and power to make unreasonable demands and get away with it (e.g., YouTube deletes something copyrighted: Firm says, content is now gone, so won't push any further, because fighting YouTube's lawyers is too expensive for us. Someone other poorer platform does the same thing: Firm says, already deleted? Too bad, we're still going to fight you because of that old violation anyway, because we know we can away with squeezing you for it). Of course, different countries, different laws, and depending on which country the platform is location in, and also depending on whether the firm is location somewhere different, it might be more/less difficult to take action (or to prevent action, for that matter), depending on the exact nature of the laws in the respective countries, context, circumstances, etc.

But, in any case, I'm not a lawyer, so I would avoid giving anyone concrete advice personally, and this is something a proper lawyer would need to be consulted about, I think.

**Comment by akhilleusuggo** [comment]
> It's an unfortunate reality that, if you're not rich, it's easier to be bullied, and easier for those with money and power to make unreasonable demands and get away with it 

You have just resumed the entire world we're living in it on this sentence.

**Comment by guymass** [comment]
Yeah, sad but true.

**Comment by The-Do-It-Yourself-World** [comment]
There is software that you can put into your site which scans the internet for duplicate content. Steem, the crypto blogging site, uses something like that. They tell you if your content is copied or not automatically and flag it. 

I think you could make an api call to a google search and scan the results. With video content this is not as simple but with text, like the video description and title, it is. You could get a flag sent to your email or in your admin panel to look into manually.

I am often finding some very filthy stuff on my site as I browse through it. Having a keyword search for certain keywords would help too.

**Comment by guymass** [comment]
Maybe start with a plugin that can scan soundtracks and movies already listed in a database that can be built by the community. So at least all the new advertised movies and music can be scanned and with time the community can enlrage the database as a group effort. This can at et least cover 80% of top copyrighted content and will give a good headache for those who wish to close sites based on some silly mistake.

**Comment by ganddser** [comment]
Maybe an API that searches IMDB for video and searches Google images, and for audio Apple music, amazon music , Tidal and the like at least those sources will contain reliable data on copyrighted video, images and audio. The question is how implement efficiently so as not to slowdown sites.
