### ISSUE TITLE
I bought the plugin's "LiveUsers" 

### ISSUE THREAD

**Issue by JeanDavis91** [WWBN/AVideo#6206]
Hello

I bought the plugin's "LiveUsers" and I activated the "YPTSocket (YPTSocket) Version: @1.2" but the problem it does not work on the synology server there is no error and I do not know how to fix it. activate on this server

Thanks for your help 

![ypt](https://user-images.githubusercontent.com/61474191/150702464-2aba8622-4a91-410f-8e09-3fd7caf53761.jpg)

**Comment by DanielnetoDotCom** [comment]
Hi

I do not know what a "synology server"  is

but in most of cases the problem is a port blocked

try to shut down your firewall

also, try this ...

## Stop the socket

`php /var/www/html/AVideo/plugin/YPTSocket/stopServer.php`

## run the socket again

`php /var/www/html/AVideo/plugin/YPTSocket/server.php`

## make a test

keep this terminal opened and open a new one and run this 

`php /var/www/html/AVideo/plugin/YPTSocket/test.php`
