### ISSUE TITLE
Log in credentials not working on mobile app

### ISSUE THREAD

**Issue by barrunning** [WWBN/AVideo#6242]
Members can log into main website but can’t log into mobile app.. mismatch password and username is what is returned.
iPhone and iPad.

Is this a setting issue or individual phone issue?

**Comment by barrunning** [comment]
![Uploading 3F262ACE-24DC-4458-9C2D-8E3819C33CEE.png…]()

**Comment by barrunning** [comment]
Emailed to you

**Comment by DanielnetoDotCom** [comment]
The login is working, the problem is you have enabled the Netflix style and unchecked all the rows on the MobileManager plugin

![image](https://user-images.githubusercontent.com/18009293/152357539-f21ce14e-537f-42e3-9167-8655e1a931a6.png)


Please be careful when you change things, it took me a while to figure out your misconfiguration.
