### ISSUE TITLE
Code validation

### ISSUE THREAD

**Issue by gbrn** [WWBN/AVideo#6293]
Hi Daniel, I've been doing some SEO checks and found some alerts. Could you check if it's a pertinent correction?

node_modules/infinite-scroll/dist/infinite-scroll.pkgd.min.js
Line 11, Column 3775, Unexpected token ...

Line 33, Column 155, The attribute [ href ] of the tag [ link ] must have a value.:

`<link href="http://cnetv.com.br/videos/cache/css/5d7d9a317b5a571d63459c7b0f75f65c.css?cache=1644984225_1644984225" rel="stylesheet" type="text/css"/><link href="" rel="stylesheet" type="text/css"/>`

----------------------------------
Line 35, Column 98, The attribute [ href ] of the tag [ link ] must have a value:

`<!-- theme is not default --><!-- showCustomCSS is empty --><!-- css file does not exist --><link href="" rel="stylesheet" type="text/css" id="pluginCustomCss" /><link href="http://cnetv.com.br/videos/cache/css/187a37e9a97f02763a40e1a86e22e9d8.css?cache=1644984225_1644984225" rel="stylesheet" type="text/css"/><script src="http://cnetv.com.br/node_modules/jquery/dist/jquery.min.js?cache=1641246408_1641428403"></script>`

**Comment by Maikuolan** [comment]
> node_modules/infinite-scroll/dist/infinite-scroll.pkgd.min.js Line 11, Column 3775, Unexpected token ...

According to the included `package.json` information, [AVideo is using infinite-scroll v4.0.1](https://github.com/WWBN/AVideo/blob/bbffba7cea7fdf98f41363ff50cb0c623168e7c8/node_modules/infinite-scroll/package.json#L3). According to the [available tags/releases at the repository for infinite-scroll](https://github.com/metafizzy/infinite-scroll/tags), v4.0.1 is also currently the latest available release. So, trying to update AVideo's version of that package *right now* won't do anything (and I don't recommend messing around with files belonging to included dependencies from directly within AVideo ourselves, because any changes made will be undone as soon as we next try to update any of those dependencies from the upstream source, plus not foregoing the maintainability nightmare that directly messing around with them would introduce to AVideo).

That said, the two best approaches I can see for trying to resolve problems with dependencies such as these would be:
1. (Active approach): Trying to resolve the problem at the upstream source (e.g., trying to contact the maintainer there to let them know about it, creating an issue there, etc). *Or..*
2. (Passive approach): Just waiting it out, hoping the maintainer notices the problem themselves, fixing it when they've got the time to do so.

..and then, later, after the problem has been fixed at the upstream, and after the maintainer has tagged a new release at their end, *then* we update AVideo's copy of the dependency from the upstream source.

If the problem is urgent (e.g., it breaks something here at AVideo), the *active approach* would be preferable (seeing as it should lead to quicker results). If the problem is *not* urgent (i.e., nothing broken), the passive approach *may* be preferable (seeing as it avoids potentially annoying maintainers over there, frees up time to work on other things over here, etc). But, this depends on one's own personal opinions/tastes/preferences/etc.

> `<link href="http://cnetv.com.br/videos/cache/css/5d7d9a317b5a571d63459c7b0f75f65c.css?cache=1644984225_1644984225" rel="stylesheet" type="text/css"/><link href="" rel="stylesheet" type="text/css"/>`
> 
> Line 35, Column 98, The attribute [ href ] of the tag [ link ] must have a value:

I *doubt* that an empty href value would be sufficient to adversely affect SEO to a noticeable extent, but someone else with a little more recent experience/knowledge in that field may need to chime in here, seeing as I haven't bothered working much on SEO stuff for a while now. (The rules/guidelines for what to do, what to not do, what works, what doesn't work, etc changes quite often, and often differently from one search engine to another).
