### ISSUE TITLE
Cannot cancel live stream recording

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo#6316]
We have now a live stream which is running like a radio show almost all day long, problem is we have tried to cancel the recording for this stream but it doesn't seem to work, it keeps encoding the stream every hour and creating a file.

We need to be able to live stream without recording or encoding, just streaming.

**Comment by DanielnetoDotCom** [comment]
How is your Nginx control section?

is it set `record all manual;`

https://github.com/WWBN/AVideo/blob/87a23fa13b97c7a9ca8a14701e0ba569e60a6713/plugin/Live/install/nginx.conf#L41-L49

when you try to cancel you should see something on Nginx log and also on avideo log

**Comment by guymass** [comment]
This is my recorder:

                            recorder video{
                                record all;
                                record_path /var/www/tmp;
                                record_notify on;
                                record_max_size 2048M;
                                record_suffix -%d-%b-%y-%T.flv;
                            }

**Comment by DanielnetoDotCom** [comment]
I guess to cancel the live recording you need the manual. 

also, you have to make sure your controls are working.

https://github.com/WWBN/AVideo/blob/87a23fa13b97c7a9ca8a14701e0ba569e60a6713/plugin/Live/install/nginx.conf#L131-L136

you will need to change your nginx.conf to manual and also check your streamer and nginx log files

**Comment by guymass** [comment]
This option keeps resetting to On:
![Screen Shot 5782-07-01 at 16 26 56](https://user-images.githubusercontent.com/58882903/156781189-e95dccd2-f266-4fc6-b4cd-cc11df6ceb2a.jpg)

**Comment by DanielnetoDotCom** [comment]
check your streamer log when you save it.

**Comment by guymass** [comment]
you mean my videos/avideo.log?

**Comment by guymass** [comment]
I cleared my log and tried again, here is the log file:
[avideo.log](https://github.com/WWBN/AVideo/files/8186875/avideo.log)

**Comment by DanielnetoDotCom** [comment]
I did not see any record attempt or on_publish or control event on your log

are you runing any live on this log?

did you clicked on the stop or start record?

**Comment by guymass** [comment]
No I didn't actually start the live I was just setting the post and wanted the option of record to off before I begin the stream.

**Comment by guymass** [comment]
here is a new log where I start the stream and than I go into the page and click the Stop Recording button there.
[avideo.log](https://github.com/WWBN/AVideo/files/8187271/avideo.log)

**Comment by DanielnetoDotCom** [comment]
Hi, 

on this new log I saw the control requests. and all seems to be fine.

I also saw the on_publish_done but I did not see the on_record_done

is the on_record_done URL properly setup in your nginx.conf?

## Also try this ...

comment out the control restrictions ...

````
location /control { 
         # replace this with the IP of your AVideo site 
         # allow 127.0.0.1; 
         # deny all; 
         rtmp_control all; 
 } 
````

than access the control URL whenever you have a live runing

http://yourliveserver.com:8080/control/record/start?app=live&name=6212762429f23-1&rec=video

what is the output?

**Comment by guymass** [comment]
Yes on record done is set:
![Screen Shot 5782-07-01 at 21 28 35](https://user-images.githubusercontent.com/58882903/156829383-3e0db0e0-05e3-4de4-8ed0-d77e5e2a021b.jpg)

I set the control like you said but I don't have this URL working in my case it was:
[6212762429f23-2](https://live.ahava528.com:8080/control/record/start?app=live&name=6212762429f23-2&rec=video)

**Comment by guymass** [comment]
So now the live stream is not getting encoded at all. Even after I press the start record and get the success message there is no indication that the recording is actually running, the state of the button doesn't change its appearence to reflect it is in recording mode.
![Screen Shot 5782-07-01 at 21 46 28](https://user-images.githubusercontent.com/58882903/156832062-05f01676-f23f-4f9a-98a8-cb99644449e4.jpg)

Record button looks the same after pressing it.

**Comment by guymass** [comment]
OK I now noticed where the recording directory is located and im going to clear it and test live stream again. I want to have the option to encode or record it and it seems these are two different options. I will check to see if it is still recording in the backgroud without pressing the record button and then with pressing it and see what happenes.

**Comment by guymass** [comment]
Here is a fresh log where I start a stream, then I click the record button, wait for 30sec, then I click the stop recording button and then about 10sec after I stop the stream.
[avideo.log](https://github.com/WWBN/AVideo/files/8188578/avideo.log)

**Comment by guymass** [comment]
OK I removed the "manual" keyword from the record all; line and now its back to recording the stream however click the cancel record button will not do any thing and im back to square one where I want to have the option if to save and encode the live stream or not as shown in the post choices.

**Comment by DanielnetoDotCom** [comment]
Hi

the way you describer the error seems to be on the ocntrol

as long as you do not have this url working ....


https://live.ahava528.com:8080/control/record/start?app=live&name=6212762429f23-2&rec=video

you MUST make sure it will work, probably your port 8080 is not properly configured, and than use http instead of https

**Comment by guymass** [comment]
How do I configure this URL? This is the first time I see control needs this configuration setup. Can You show me an example config?

**Comment by DanielnetoDotCom** [comment]
this URL should be available as long as your Nginx have the proper port opened

for more details check here 

https://github.com/arut/nginx-rtmp-module/wiki/Control-module

**Comment by matheusfillipe** [comment]
Thanks @DanielnetoDotCom. I am helping @guymass on this issue.
One thing that was missing was setting `worker_processes 1;` on the nginx config.

Now I can curl the control api like this to stop and start the recording and it works.

```bash
$ curl http://127.0.0.1:8444//control/record/start\?app\=live\&name\=${my-serial-key}\&rec\=video
$ curl http://127.0.0.1:8444//control/record/stop\?app\=live\&name\=${my-serial-key}\&rec\=video
```

I've set the right ip and port on the Live plugin configuration and it also works now from these buttons after the stream has started:

![image](https://user-images.githubusercontent.com/24435787/156909305-5407b9b8-8a57-42ea-a1d7-ba20def54540.png)

Clicking on stop and start there does successfully stop and start the recording.

![image](https://user-images.githubusercontent.com/24435787/156909395-30f671b4-a7c7-411a-992f-6963a9a67de5.png)


Now the problem is with the settings part of Live. Even though you change  `Auto record this live` and the request is sent correctly, if you reload the page it is back toggled on. Both of those toggle boxes seem to have misleading behavior.

 We don't want recording to be enabled by default. These are the logs from when that is toggled off: [record_error.log](https://github.com/WWBN/AVideo/files/8191959/record_error.log)

Doesn't seem to be any errors besides trying to clean an non existing cache file. 

I set up a debug proxy and pointed the live plugin to send the control requests to it and even though I have just disabled that auto record toggle it keeps sending:

```
"GET /control/record/start?app=live&name=${my-serial-key}&rec=video HTTP/1.0" 404 -
```

Repeatedly. I believe it should be sending stop instead because if I curl with stop it stops immediately. 

That's the info I could gather for now, I believe that's either a problem with that cache or with that information not being properly saved.

We are on the latest git commit and Live plugin `Version: @10.5`

**Comment by DanielnetoDotCom** [comment]
Hi, @matheusfillipe 

there is an option on the record plugin that forces to save all the lives

![image](https://user-images.githubusercontent.com/18009293/157029790-eb966dcd-7449-430d-84aa-befc9d36e69f.png)

**Comment by guymass** [comment]
Great! that fixes the selection issue, now its selectable, I think we can close this one, much thanks, God bless.

**Comment by guymass** [comment]
I need to reopen this issue for one final problem. In regards to the recording starting and stopping everything is OK, however the issue now is that the recording will only record the last stream that was started, so if I am running more than one stream from my account and I press record on each of those streams it will only control the last stream that was initiated.

**Comment by DanielnetoDotCom** [comment]
I found something.

it will be fixed on SendRecordedToEncoder version 7.5

but it will also requires you a streamer update (git pull)

**Comment by guymass** [comment]
I already have version 7.5, did you mean 7.6?

![Screen Shot 5782-07-06 at 18 35 54](https://user-images.githubusercontent.com/58882903/157487063-7523dd8c-a4ab-49e0-8b51-87c70c361e57.jpg)

Let me know when I can update my streamer and I will test it after. Much thanks!

**Comment by DanielnetoDotCom** [comment]
Please make a git pull and download version 7.6

**Comment by guymass** [comment]
OK Made an update to 7.6 and ran a pull, also cleared cache, so in regards to this issue should we now test to see if each stream can be recorded/controlled separately?

**Comment by DanielnetoDotCom** [comment]
yes, supposed to

**Comment by guymass** [comment]
OK this is fixed its now controlling each stream's recording cool!! brilliant!
