### ISSUE TITLE
Pasting hebrew text in article is causing a mirror effect

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo#6538]
When I try to copy and paste Hebrew text into the article I get reversed letters. Also when pasting source code that contains Hebrew text it gets mirrored. Here is a screen shot:
![Screen Shot 5782-08-26 at 19 00 26](https://user-images.githubusercontent.com/58882903/165561973-0d44c8f1-4949-4870-970f-2b02f741eb1e.jpg)

**Comment by DanielnetoDotCom** [comment]
I am not sure the solution for that. 

sorry but I am not used to an RTL text, but your help will be very welcome

there is any CSS code that resolves that?

**Comment by Maikuolan** [comment]
The solution I use, whenever mixing left-to-right and right-to-left text together in the same sentence/paragraph/etc, is to just be really explicit in my HTML/markdown/etc in regards to text directionality, generally, firstly, encapsulating the entire block of text to mark the overall primarily directionality of the text, and then encapsulating each part of the text whereby the directionality changes.

As an example, for this arbitrary sentence, which combines both Hebrew and English in the same paragraph, as well as some names which use Latin alphabet mixed into the Hebrew sentences, the first version is just the text by itself (directionality not marked by any HTML or otherwise), while the second version has its directionality explicitly marked by HTML spans:

```HTML
This is a test. שלום עולם. שמו היה John Doe. שמה היה Jane Doe.

<span dir="rtl"><span dir="ltr">This is a test.</span> שלום עולם. שמו היה <span dir="ltr">John Doe</span>. שמה היה <span dir="ltr">Jane Doe</span>.</span>
```

The results of that:

This is a test. שלום עולם. שמו היה John Doe. שמה היה Jane Doe.

<span dir="rtl"><span dir="ltr">This is a test.</span> שלום עולם. שמו היה <span dir="ltr">John Doe</span>. שמה היה <span dir="ltr">Jane Doe</span>.</span>

**Comment by Maikuolan** [comment]
You can even do something similar with entire blocks of quoted code here at GitHub too, for that matter, simply by explicitly marking the directionality for the markdown in question around said markdown, using HTML:

<span dir="rtl">

```HTML
שים אותו בצד ימין.
```

</span>

**Comment by Maikuolan** [comment]
But yeah.. In general, explicitly marking directionality would be the best way to go, I think. The only major limitation to that solution I can think of offhandedly, is that *within* certain elements of the page, specifically those where text can't be readily split up in order to be styled or formatted in multiple different ways, or marked distinctly (e.g., text boxes, input fields, etc, where the presented text, as far as HTML is concerned, is just that – text, and nothing more), we don't really have any means of explicitly marking the different parts of the text in the first place. So, where HTML is rendered, we can make it look nice by marking explicitly, but where text is just shown as text (i.e., not rendered as HTML), it probably won't work the same way.

**Comment by DanielnetoDotCom** [comment]
Thanks @Maikuolan 

so I suspect the solution would be to make the markup directly into the editor correct?

**Comment by Maikuolan** [comment]
Yep. :-)

**Comment by guymass** [comment]
Thank you @Maikuolan I think that this is a good solution, however this is not just about text formatting but also how it effects how it is presented on the page and some times it will require us editing the RTL CSS, but for that I need to do it manually in the file and once I git pull that code will be removed. So I think there should also be a way to add rules to the RTL from within AVideo Admin panel, just like they do with the english version.
