### ISSUE TITLE
FTP Storage plugin

### ISSUE THREAD

**Issue by guitarpound** [WWBN/AVideo#6737]
Hi Daniel,

I have a few question about FTP storage plugin.

1) If I already have video keep in Local server but it is full.
I can use the FTP storage plugin to extend storage.  Right ?

2) The new video will keep in the FTP server and the Old video still keep in the Local storage.  Right?

Thanks

**Comment by DanielnetoDotCom** [comment]
https://github.com/WWBN/AVideo/wiki/Storage-Options

**Comment by guitarpound** [comment]
Hi Daniel,

I tried test the FTP Storage plugin on your demo site.
I can Direct upload & Encode the video to your FTP server.

But when I remove the video files in the "My Video pages"
The video files still show in the FTP server.

Is it normal for this plugin right?

**Comment by DanielnetoDotCom** [comment]
Not supposed to, but if you remove one of the videos that were already there it may fail because this is the demo site, and we restore the videos and database 4 times a day, and the user we use to restore is the root. so the FTP user cannot delete the root files. 

I hope it makes sense. but if you upload a video now, and delete it, it supposes to delete your new video.
