### ISSUE TITLE
CustomizeUser Keeps resetting what is going on

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#6985]
All my settings keep getting reset every day. What is going on with this?

**Comment by JoshWho** [comment]
There has to be a way to make this read only PLEASE

**Comment by DanielnetoDotCom** [comment]
there is no way to make it read-only

you must pay attention to what you are adding to this plugin.

if for some reason the JSON cannot be decoded it will reset the plugin

Be careful with the text areas

![image](https://user-images.githubusercontent.com/18009293/184020930-a0d7be26-2722-4b0e-9e2f-57ea352c1321.png)


try to change all you need except the text areas. and then see if it will reset again

**Comment by JoshWho** [comment]
If you look at my site right now. I do not have anything set in there that will cause this. Come back tomorrow and you will see it reset again.

**Comment by JoshWho** [comment]
So far hasn't changed yet. Not sure if it is fixed or not but will keep an eye out for a few more days.

**Comment by JSY-Ben** [comment]
Hope you don't mind my jumping in on this thread, not sure if It's linked, but currently on our server since the recent couple of updates, when users log in, it resets their 'Name' back to their email address. They change it, and it resets again once they log back in. This is with the LoginLDAP plugin specifically. It doesn't create a new user or change their videos, just resets their name back to there email address. This is all that appears in the log:


`[14-Aug-2022 17:50:50 Europe/London] AVideoLog::DEBUG: CustomizeUser::userMustBeLoggedIn basename: index.php SCRIPT_NAME: /streamer/view/index.php
[14-Aug-2022 17:50:53 Europe/London] AVideoLog::DEBUG: Password check Old not encoded pass SCRIPT_NAME: /streamer/plugin/LoginLDAP/view/login.json.php
[14-Aug-2022 17:50:53 Europe/London] AVideoLog::DEBUG: Password check Old not found SCRIPT_NAME: /streamer/plugin/LoginLDAP/view/login.json.php
[14-Aug-2022 17:50:53 Europe/London] AVideoLog::DEBUG: Password check Old encoded pass SCRIPT_NAME: /streamer/plugin/LoginLDAP/view/login.json.php
[14-Aug-2022 17:50:53 Europe/London] AVideoLog::DEBUG: Password check Old not found SCRIPT_NAME: /streamer/plugin/LoginLDAP/view/login.json.php
[14-Aug-2022 17:50:53 Europe/London] AVideoLog::DEBUG: loginFromRequest NOT FOUND redactedusername SCRIPT_NAME: /streamer/plugin/LoginLDAP/view/login.json.php`

**Comment by JoshWho** [comment]
Yes that is the same issue. Still not sure exactly what is causing it.

**Comment by DanielnetoDotCom** [comment]
@JSY-Ben the LoginLdap may reset their credentials. 

if it is authenticated on the LDAP, all the user info will be updated. the only valid and permanent info is the one stored on the LDAP

@JoshWho I do not think your issue has something to do with @JSY-Ben issue

**Comment by JSY-Ben** [comment]
> @JSY-Ben the LoginLdap may reset their credentials.
> 
> if it is authenticated on the LDAP, all the user info will be updated. the only valid and permanent info is the one stored on the LDAP
> 
> @JoshWho I do not think your issue has something to do with @JSY-Ben issue

Hi Daniel. Thanks for the reply.

In the past, the name has stayed the same, it's only recently it has been reset. Is there any way in the config to grab the User's Full Name from the LDAP database (in this case Active Directory)

**Comment by DanielnetoDotCom** [comment]
Currently no. to make this change I will need to see exactly what is your LDAP response.

**Comment by JoshWho** [comment]
I haven't had any changes happen since the last time. Not sure what was causing it but it seems to have stopped. I will close this for now.
