### ISSUE TITLE
Is this a SQL injectino risk?

### ISSUE THREAD

**Issue by elico** [WWBN/AVideo#7088]
I have seen the SQL code at:
https://github.com/WWBN/AVideo/blob/master/objects/video.php#L1813

and I was wondering about the direct request access.
I am not sure but there is no filtering or sanitation at all for the category name.

**Comment by DanielnetoDotCom** [comment]
No, this is not possible due to [this script ](https://github.com/WWBN/AVideo/blob/00cdf102c370358bafc2477f488439e63e5b9a5c/objects/security.php#L4)


![image](https://user-images.githubusercontent.com/18009293/188322088-6b7a67d9-921b-4a56-a2be-594eb870fbd9.png)

![image](https://user-images.githubusercontent.com/18009293/188322139-ee40e8d7-262d-46dc-baa0-991747681516.png)

**Comment by elico** [comment]
Thanks!
