### ISSUE TITLE
Ads not working for me

### ISSUE THREAD

**Issue by mankota** [WWBN/AVideo#7183]
I am struggling to configure the  ads. I created an ads for testing but I cannot get it to work at all. I believe I am missing something.  Need help

**Comment by DanielnetoDotCom** [comment]
you need to provide a lot more details to let us help you

**Comment by mankota** [comment]
I created an ads using the advertising manager. Add a video to the ads. However, it is not working
![image](https://user-images.githubusercontent.com/25535711/192615627-061ba1a1-31fe-458e-bc2d-ae8361c7eae0.png)

**Comment by LightRO** [comment]
Same Problem i have too. The videos are in the Add Video but the Ads are not showing.

I get a message in the browser console:

`AdsLoader error: AdError 1005: There was a problem requesting ads from the server. Caused by: Error: 6
r.onAdsLoaderError @ videojs.ima.min.js?cache=1664459930_1664459930:1
jk @ ima3.js:147
l.dispatchEvent @ ima3.js:145
UI.P @ ima3.js:691
jk @ ima3.js:147
l.dispatchEvent @ ima3.js:145
ZA.D @ ima3.js:489
fk @ ima3.js:144
b @ ima3.js:142
video.min.js?cache=1664459926_1664459926:12 

VIDEOJS: ADS: adserror (BeforePreroll)
script.js?cache=1664462799_1664462799:1137 setCurrentTime canplaythrough 2`
