### ISSUE TITLE
Entering wrong login data by user

### ISSUE THREAD

**Issue by gbrn** [WWBN/AVideo#7424]
@DanielnetoDotCom working with database data. I verified that the system accepts entering the login information in all caps. I believe it is more interesting to force the insertion of data if login all in lower case. It eliminates the wrong login problem and makes the data more organized.

Have you already checked this?

![image](https://user-images.githubusercontent.com/37880073/204113762-0d9bd86a-2fd6-4714-8681-59f0b03af74d.png)

**Comment by Maikuolan** [comment]
Careful about Unicode non-awareness when enforcing the casing for email addresses, due to the potential effect on [non-ANSI email addresses](https://en.wikipedia.org/wiki/International_email). In PHP, we have functions like `mb_strtoupper` and `mb_strtolower` to use instead of `strtoupper` and `strtolower` when dealing with Unicode, but they require [mbstring](https://www.php.net/manual/en/mbstring.installation.php) to be installed in order to work correctly, and not all PHP installations have mbstring available. Could potentially be resolved by using polyfills, but with that comes greater project complexity as well.

**Comment by DanielnetoDotCom** [comment]
I agree with @Maikuolan but I disagree that changing the case of the email makes any difference, in my opinion currently this is a waste of resources and time.

only passwords should be case-sensitive, a username should make no difference to the case when we query it. 

but we can change case when we display it. so for now I will not change it
