### ISSUE TITLE
git pull throwing the error-please help

### ISSUE THREAD

**Issue by vraghavans** [WWBN/AVideo#7714]
![image](https://user-images.githubusercontent.com/65802024/221349737-526a59ad-65a1-42e4-80ec-f8b63461041b.png)

**Comment by Maikuolan** [comment]
I guess, there are merge conflicts, because that file had appeared here at the upstream repository 4 days ago, but the downstream AVideo installation had already generated that file, thus meaning that checking out the file fetched from the upstream would "overwrite the untracked working tree file" (i.e., because of the changes already made automatically by the downstream installation).

@DanielnetoDotCom That file (`nohup.out`) looks like a log file generated by AVideo. Does that file need to exist here at the upstream repository at all, or can we just delete it? I assume, AVideo installations would just automatically regenerate it anyway.

**Comment by DanielnetoDotCom** [comment]
just delete the nohup.out

`rm nohup.out`

then run the git pull again

**Comment by vraghavans** [comment]
thanks!
