### ISSUE TITLE
WebSocket Connection Error

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo#8202]
The site I have proxied used to have its WebSocket working but lately since last couple of updates it now gone and I get the following error trying to restart the socket service:

![Screenshot 5783-11-02 at 18 47 08](https://github.com/WWBN/AVideo/assets/58882903/42eb5cc2-ebbe-4225-b934-9552d34cc1a8)

**Comment by walt93** [comment]
I was recently stuck in a weird loop, kill -9'ing the thing repeatedly and starting it, I think the Scheduler plug-in was restarting it, I don't really have it characterized other than it took probably like ten tries before the fscking thing started.

That, and you have to be prepared to reconfigure its path to your SSL cert (plugins->scheduler) if you've enabled/disabled any sites in your apache conf since the last cert was issued... And again, dance with the thing stopping and starting it until it figures out how to talk to itself again…

**Comment by milehighkaraoke** [comment]
mine has been doing the same stupid thing. I found on mine no matter what port I use for the socket itcwill disconnect and then show the port is busy. I tried 60 different ports and it's the same thing.

change port, open port on firewall, reboot server... 
Maybe it comes on maybe it doesn't.... So freaking frustrated....

**Comment by guymass** [comment]
Its really sometimes like a lottery, at time it connects and after it crashes for some reason and want's to restart, it goes into an endless loop, really sometimes requiring a server restart (not always), which I don't like to do. Still thinking of a proper solution a proper to create a round-robin back from my proxy server to my VM, at times it works, but for every installation I try, strange.

**Comment by guymass** [comment]
Well this is for sure a port forwarding or proxy issue, sometimes it works on other config it doesn't, hopefully in the future we will fine a more stable proxy configuration method. I know there is an option for the docker installation would be nice to have a more clear tutorial on setting up AVideo as a docker behind a reverse proxy for nginx and apache.
