### ISSUE TITLE
What is CachesInDB used for? It creates really bad performance problems when it grows too large.

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#8489]
**Describe the question**
Site performance was near unusable, I just watched mysql sitting at 4000% CPU (40 cores!) maxing out the server for some time. Analysis showed mysql was running ≈80 concurrent accesses to CachesInDB

CachesInDB was observed to be ≈4x the database size. Truncating it solved the performance issue.

Questions:

1) What does it do / why do we need it?
2) What did I lose when I purged it?
3) Can we turn it off - or - is it safe to script truncating it on a cron task or something?

**Comment by para2022** [comment]
I have never used the cache it is not practical. Not good for a production site for these reasons:

1. Users think the site is broken because editing there videos has no affect. They complain saying they cannot edit videos and thumbnails ect, because they do not know that they have to wait for the cache to change for their changes to take affect. Not practical for a website.
2. Views on the main page do not update only when the cache updates so users think the site is broken for that reason.
3. The big video and all recommended videos do not change until the cache updates.
4. Anything that is meant to change in realtime and does not will always confuse the hell out of people and they will go away and not use it. Channel owners will not be happy with a system like that.

So why would you use this on a production site giving the illusion to users that things are broken? I want my site to update in real time so no the cache from me! You need to be super tech savvy with a lot of knowledge in building solid server infrastructure to get AVideo working properly. I have learned this over the years.

**Comment by DanielnetoDotCom** [comment]
1. **Purpose of CachesInDB**: It's a caching mechanism to enhance site speed by storing frequently accessed data.
2. **On Purging**: Purging `CachesInDB` doesn't result in any data loss. It's merely a temporary store to improve access speed.
3. **Turning Off/Scheduled Truncation**: Please ensure you're using the latest AVideo version. We've recently improved `CachesInDB` to address such concerns. Also, the Scheduler and Cache plugins, when active, help manage the cache size daily.

It's worth noting that **CachesInDB** is functioning efficiently on several large sites with over 600 concurrent users and thousands of videos. It's possible there may be other factors related to your server hardware or configuration that might be impacting performance.

**Comment by walt93** [comment]
In my experience "CachesInDB" does nothing but slow your site down. Every couple of months you have to nuke it. I just cleared millions of entries. While clearing the cache, literally a few seconds later I hit the up arrow twice/carriage return to re-run the SQL command to get the number of entries and there were 700. I did a couple other things, checked again, over 7,000.  I have no idea what is being "cached" - it seems we have to spend a great deal of time searching through this "cache" for anything useful!

I watched my server take two minutes to serve a page and it actually took >95% its resources to do it, it was running 42 cores for an extended period of time to parse this "cache". I don't have 50 users on my site at a time now because of this other bug that scares users away - on every page load they are asked to store 200GB on their device!

Recommend sitting down with the AI for a weekend and learning about caching techniques. Then throw this code away and rewrite it from scratch.

**Comment by para2022** [comment]
Cache and the search function are 2 biggest fixes that need to happen. Cache is not worthy of production and search in totally unusable on large sites. Takes 2-3 mins to complete a search, really? As the site grows further that timeframe would continue to grow. It is a tragedy that AVideo has no viable search function.

**Comment by DanielnetoDotCom** [comment]
Make sure you have the Scheduler and Cache plugin enabled. 

I have huge sites running AVideo smoothly.

**Comment by para2022** [comment]
In the above it looks like a schedular issue not running and resetting those numbers. I had this issue. id have many hundreds of users (total online) but if i manually reset the socket it would then flush and show the true numbers online which was very different.

**Comment by DanielnetoDotCom** [comment]
before I showed you I did a socket restart

**Comment by walt93** [comment]
Well I'm flummoxed then. I had a database that was like 200MB, which is nothing, and CachesInDB was like 800MB. 

Not sure why mysql is spinning up 40 cores to 100% for 5-10 minutes at a time trying to do a page load. My total users online was averaging 300 but now is down to ≈50. Between the site being unusably slow and the dialog box asking for 200GB of storage on every page load, I'm surprised the 50 are sticking around.

I turned off cache to see if the site might start doing better. I thought throwing a 48-core 128GB server would be enough resources for AVideo...

**Comment by DanielnetoDotCom** [comment]
I do not know why you keep opening similar issues. it only makes harder for me to help you

https://github.com/WWBN/AVideo/issues/8500
