### ISSUE TITLE
Video Title being cut off on WPA version

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#9294]
![Screenshot_20240804-215654](https://github.com/user-attachments/assets/41020f9d-d445-44e6-a4b0-97c91298cb75)

Only see the second letters of the titles on Mobile WPA

**Comment by DanielnetoDotCom** [comment]
you have this in your custom code

.mainArea {
 padding: 0px;
}

this is causing the issue

I've noticed that many of the layout issues you've been experiencing are due to custom code that's being added. Unfortunately, I can't continue troubleshooting and fixing problems caused by these custom changes, as I need to focus on other tasks.

**Comment by JoshWho** [comment]
> you have this in your custom code
> 
> .mainArea { padding: 0px; }
> 
> this is causing the issue
> 
> I've noticed that many of the layout issues you've been experiencing are due to custom code that's being added. Unfortunately, I can't continue troubleshooting and fixing problems caused by these custom changes, as I need to focus on other tasks.

Thank you fixed it.
