### ISSUE TITLE
Lately I have been noticing around the evening time YPT Socket stops working I have to restart it every day

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#9313]
Is there a service script that can check to see when it stops running and to auto restart it?

**Comment by milehighkaraoke** [comment]
Are you getting the infamous  2053 is busy?

**Comment by JoshWho** [comment]
Not sure I am never on when it happens and by the time I am it is way far in the logs

**Comment by milehighkaraoke** [comment]
Mine does it also.  Does not matter what port number is entered it still shows busy with php. I have not seen that issue on mine since the update to 14.4. It only does it now if I restart my server but it somehow corrects itself within 5 minutes and makes the connection leaving behind the log error that 2053 is busy.

**Comment by JoshWho** [comment]
I think you are right. I haven't seen it crash in the last 2 days. I will close this for now.
