### ISSUE TITLE
A way to forward banned users to a page or anything I want them to see. 

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#9516]
Instead of flat out IP banning I would like to shame them more. I get benning from nginx but I want them to see a custom page of me personally telling them to F off basically. 

Like when I click ban user allow me to redirect them to any page or thing I want instead of just dc ing them. 

Even make a public page where it will post that they are banned and for what reason, Call it the wall of shame.

**Comment by DanielnetoDotCom** [comment]
I understand the idea, but I wouldn’t recommend it—it’s not the most professional approach. Redirecting banned users to a custom page or a "wall of shame" could give them unnecessary info, which might make it easier for them to find ways around the ban.

A blank page works best because it keeps them in the dark. They won’t know if the site’s down, if it’s an internet issue, or something else. The less they know, the harder it is for them to cause more trouble.

It’s really better to keep things simple and not engage with unwanted visitors.
