### ISSUE TITLE
This file won't upload 

### ISSUE THREAD

**Issue by fakeologist** [WWBN/AVideo#9539]
I have a few files stuck in the queue that won't upload please advise

**Comment by DanielnetoDotCom** [comment]
As I can see in your encoder, it is working fine. did you also update the encoder?

make sure it is also up to date

**Comment by fakeologist** [comment]
I always do.
It's getting stuck in encoding after upload.

**Comment by DanielnetoDotCom** [comment]
there is any video sample now?

**Comment by fakeologist** [comment]
Still not working.
These are Samsung screen recordings that did not work before, you fixed it, broken again.

**Comment by DanielnetoDotCom** [comment]
can you please share the video source with me?

**Comment by fakeologist** [comment]
https://we.tl/t-97t50PPLcG

**Comment by DanielnetoDotCom** [comment]
I’ve reviewed the video, and it turns out that the file has an extremely high frame rate of approximately 90,000 FPS, which is far beyond normal and is causing the encoding process to slow down significantly. This frame rate is absurd and not practical for video playback or processing.

To resolve this, I am now forcing all your videos to be encoded at 30 FPS, which is a standard and efficient frame rate. This adjustment has significantly improved the encoding speed, and the process is running much faster now.

Ideally, the frame rate should follow the source, but it seems to be a recurring issue with the videos you’re sending, where they have an unusually high FPS. I recommend checking the source settings or the recording method to prevent this from happening in the future.

**Comment by fakeologist** [comment]
It's Samsung screen record, and it's set at 480p. There is nowhere to set the FPS rate. The video portion is a mostly static image with a text scroll bar.

**Comment by DanielnetoDotCom** [comment]
I am not sure how this happen then, but looks like force 30 FPS is working fine
